using System.Globalization;
using System.Text;
using BoomHud.Abstractions.Capabilities;
using BoomHud.Abstractions.Generation;
using BoomHud.Abstractions.IR;
using BoomHud.Generators;

namespace BoomHud.Gen.UGui;

public sealed partial class UGuiGenerator : IBackendGenerator
{
    public string TargetFramework => "Unity uGUI";
    public ICapabilityManifest Capabilities => UGuiCapabilities.Instance;

    public GenerationResult Generate(HudDocument document, GenerationOptions options)
    {
        var diagnostics = new List<Diagnostic>();
        var files = new List<GeneratedFile>();

        try
        {
            foreach (var component in document.Components.Values)
            {
                Emit(new HudDocument
                {
                    Name = component.Name,
                    Metadata = component.Metadata,
                    Root = component.Root,
                    Styles = document.Styles,
                    Components = document.Components
                }, options, diagnostics, files);
            }

            var plan = Emit(document, options, diagnostics, files);
            if (options.Motion != null)
            {
                EmitMotion(document, plan, options, diagnostics, files);
            }
        }
        catch (Exception ex)
        {
            diagnostics.Add(Diagnostic.Error($"Generation failed: {ex.Message}"));
        }

        return new GenerationResult { Files = files, Diagnostics = diagnostics };
    }

    private static PlanDocument Emit(HudDocument document, GenerationOptions options, List<Diagnostic> diagnostics, List<GeneratedFile> files)
    {
        var plan = Planner.Create(document, diagnostics, options.RuleSet);
        files.Add(new GeneratedFile { Path = $"{document.Name}View.ugui.cs", Content = GenerateView(document, plan, options, diagnostics), Type = GeneratedFileType.SourceCode });
        if (options.EmitViewModelInterfaces)
        {
            files.Add(new GeneratedFile { Path = $"I{document.Name}ViewModel.g.cs", Content = GenerateInterface(document.Name, plan.Properties, options), Type = GeneratedFileType.SourceCode });
        }

        return plan;
    }

    private static string GenerateView(HudDocument document, PlanDocument plan, GenerationOptions options, List<Diagnostic> diagnostics)
    {
        var builder = new StringBuilder();
        if (options.IncludeComments)
        {
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine($"// Generated by BoomHud.Gen.UGui from {document.Name}");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine();
        }

        if (options.UseNullableAnnotations)
        {
            builder.AppendLine("#nullable enable");
            builder.AppendLine();
        }

        builder.AppendLine("using System;");
        builder.AppendLine("using PropertyChangedEventArgs = System.ComponentModel.PropertyChangedEventArgs;");
        builder.AppendLine("using System.Globalization;");
        builder.AppendLine("using UnityEngine;");
        builder.AppendLine("using UnityEngine.UI;");
        builder.AppendLine();
        builder.AppendLine($"namespace {options.Namespace}");
        builder.AppendLine("{");
        builder.AppendLine($"public sealed class {document.Name}View");
        builder.AppendLine("{");
        builder.AppendLine($"    private I{document.Name}ViewModel? _viewModel;");
        builder.AppendLine("    public RectTransform Root { get; }");
        foreach (var node in plan.Nodes)
        {
            builder.AppendLine($"    public {node.FieldType} {node.FieldName} {{ get; }}");
        }

        builder.AppendLine();
        builder.AppendLine($"    public I{document.Name}ViewModel? ViewModel");
        builder.AppendLine("    {");
        builder.AppendLine("        get => _viewModel;");
        builder.AppendLine("        set");
        builder.AppendLine("        {");
        builder.AppendLine("            if (ReferenceEquals(_viewModel, value)) return;");
        builder.AppendLine("            if (_viewModel != null) _viewModel.PropertyChanged -= OnChanged;");
        builder.AppendLine("            _viewModel = value;");
        builder.AppendLine("            if (_viewModel != null) _viewModel.PropertyChanged += OnChanged;");
        builder.AppendLine("            Refresh();");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine($"    public {document.Name}View(Transform? parent = null, I{document.Name}ViewModel? viewModel = null)");
        builder.AppendLine("    {");
        builder.AppendLine($"        Root = CreateRect(\"{plan.Root.Name}\", parent);");
        AppendSetup(builder, plan.Root, "Root", parentLayout: null, document.Components, diagnostics, 2);
        foreach (var child in plan.Root.Children)
        {
            AppendCreate(builder, child, "Root", plan.Root.Source.Layout?.Type, document.Components, diagnostics, 2);
        }
        builder.AppendLine("        ViewModel = viewModel;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine($"    private {document.Name}View(RectTransform root, I{document.Name}ViewModel? viewModel)");
        builder.AppendLine("    {");
        builder.AppendLine("        Root = root;");
        AppendBindExisting(builder, plan.Root, parentPath: null, indentLevel: 2);
        builder.AppendLine("        ViewModel = viewModel;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine($"    public static {document.Name}View Bind(RectTransform root, I{document.Name}ViewModel? viewModel = null) => new(root, viewModel);");
        builder.AppendLine();
        builder.AppendLine("    public void Refresh()");
        builder.AppendLine("    {");
        builder.AppendLine("        if (_viewModel == null) return;");
        AppendRefresh(builder, plan.Root, plan, 2);
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private void OnChanged(object? sender, PropertyChangedEventArgs e) => Refresh();");
        builder.AppendLine();
        builder.Append(HelperCode);
        builder.AppendLine("}");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string GenerateInterface(string name, IReadOnlyList<ViewModelProperty> properties, GenerationOptions options)
    {
        var builder = new StringBuilder();
        if (options.IncludeComments)
        {
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine($"// Generated by BoomHud.Gen.UGui from {name}");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine();
        }

        if (options.UseNullableAnnotations)
        {
            builder.AppendLine("#nullable enable");
            builder.AppendLine();
        }

        builder.AppendLine("using System.ComponentModel;");
        builder.AppendLine();
        builder.AppendLine($"namespace {options.ViewModelNamespace ?? options.Namespace}");
        builder.AppendLine("{");
        builder.AppendLine($"public interface I{name}ViewModel : INotifyPropertyChanged");
        builder.AppendLine("{");
        foreach (var property in properties)
        {
            builder.AppendLine($"    object? {property.Identifier} {{ get; }}");
        }
        builder.AppendLine("}");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendCreate(StringBuilder builder, PlannedNode node, string parentAccessor, LayoutType? parentLayout, IReadOnlyDictionary<string, HudComponentDefinition> components, List<Diagnostic> diagnostics, int indentLevel)
    {
        var indent = new string(' ', indentLevel * 4);
        if (node.ComponentView != null)
        {
            var local = ToCamel(node.FieldName) + "View";
            builder.AppendLine($"{indent}var {local} = new {node.ComponentView}View({parentAccessor});");
            builder.AppendLine($"{indent}{node.FieldName} = {local}.Root;");
            builder.AppendLine($"{indent}{node.FieldName}.name = \"{node.Name}\";");
            AppendSetup(builder, node, node.FieldName, parentLayout, components, diagnostics, indentLevel);
            return;
        }

        builder.AppendLine($"{indent}{node.FieldName} = {CreateCall(node, parentAccessor)};");
        AppendSetup(builder, node, node.FieldName, parentLayout, components, diagnostics, indentLevel);
        foreach (var child in node.Children)
        {
            AppendCreate(builder, child, ChildParent(node), node.Source.Layout?.Type, components, diagnostics, indentLevel);
        }
    }

    private static void AppendSetup(StringBuilder builder, PlannedNode node, string accessor, LayoutType? parentLayout, IReadOnlyDictionary<string, HudComponentDefinition> components, List<Diagnostic> diagnostics, int indentLevel)
    {
        var indent = new string(' ', indentLevel * 4);
        var rect = accessor == "Root" ? "Root" : $"RectOf({accessor})";
        var layout = node.Source.Layout;
        var style = node.Source.Style;
        var absolute = parentLayout == LayoutType.Absolute || LayoutPolicyService.HasAbsolutePlacement(node.Source, node.Policy);
        var widthDimension = layout?.Width ?? style?.Width;
        var heightDimension = layout?.Height ?? style?.Height;
        var anchorPreset = LayoutPolicyService.ResolveAnchorPreset(node.Policy);
        var pivotPreset = LayoutPolicyService.ResolvePivotPreset(node.Policy);
        var rectTransformMode = LayoutPolicyService.ResolveRectTransformMode(node.Policy);
        var edgeInsetPolicy = LayoutPolicyService.ResolveEdgeInsetPolicy(node.Policy);

        builder.AppendLine($"{indent}ConfigureRect({rect}, width: {ToNullableFloatLiteral(Pixels(widthDimension))}, height: {ToNullableFloatLiteral(Pixels(heightDimension))}, left: {ToNullableFloatLiteral(absolute ? AbsoluteOffset(node.Source, static x => x.Left, BoomHudMetadataKeys.PencilLeft, node.Policy, "x") : null)}, top: {ToNullableFloatLiteral(absolute ? AbsoluteOffset(node.Source, static x => x.Top, BoomHudMetadataKeys.PencilTop, node.Policy, "y") : null)}, absolute: {Bool(absolute)});");
        if (!string.IsNullOrWhiteSpace(anchorPreset))
        {
            builder.AppendLine($"{indent}ApplyRectAnchorPreset({rect}, {ToStringLiteral(anchorPreset)});");
        }

        if (!string.IsNullOrWhiteSpace(pivotPreset))
        {
            builder.AppendLine($"{indent}ApplyRectPivotPreset({rect}, {ToStringLiteral(pivotPreset)});");
        }

        if (!string.IsNullOrWhiteSpace(rectTransformMode))
        {
            builder.AppendLine($"{indent}ApplyRectTransformMode({rect}, {ToStringLiteral(rectTransformMode)});");
        }

        if (!string.IsNullOrWhiteSpace(edgeInsetPolicy))
        {
            builder.AppendLine($"{indent}ApplyEdgeInsetPolicy({rect}, {ToStringLiteral(edgeInsetPolicy)});");
        }

        builder.AppendLine($"{indent}ApplyLayoutSizing({rect}, ignoreLayout: {Bool(absolute)}, preferredWidth: {ToNullableFloatLiteral(!absolute ? PreferredSize(node, widthDimension, "width") : null)}, preferredHeight: {ToNullableFloatLiteral(!absolute ? PreferredSize(node, heightDimension, "height") : null)}, flexibleWidth: {ToNullableFloatLiteral(!absolute ? FlexibleSize(node, widthDimension, "width", parentLayout) : null)}, flexibleHeight: {ToNullableFloatLiteral(!absolute ? FlexibleSize(node, heightDimension, "height", parentLayout) : null)});");
        builder.AppendLine($"{indent}ApplyContentSizeFit({rect}, horizontal: {Bool(!absolute && ShouldContentFit(node, widthDimension, "width", parentLayout))}, vertical: {Bool(!absolute && ShouldContentFit(node, heightDimension, "height", parentLayout))});");

        if (layout != null && ShouldEmitLayoutGroup(node))
        {
            switch (layout.Type)
            {
                case LayoutType.Horizontal:
                    builder.AppendLine($"{indent}ApplyHorizontalLayout({rect}, {ToFloatLiteral(Gap(LayoutPolicyService.ResolveGap(layout.Gap, node.Policy), true))}, {ToRectOffsetArgs(LayoutPolicyService.ResolvePadding(layout.Padding, node.Policy))});");
                    break;
                case LayoutType.Vertical:
                case LayoutType.Stack:
                    builder.AppendLine($"{indent}ApplyVerticalLayout({rect}, {ToFloatLiteral(Gap(LayoutPolicyService.ResolveGap(layout.Gap, node.Policy), false))}, {ToRectOffsetArgs(LayoutPolicyService.ResolvePadding(layout.Padding, node.Policy))});");
                    break;
                case LayoutType.Grid:
                case LayoutType.Dock:
                    diagnostics.Add(Diagnostic.Warning($"Unity uGUI falls back to vertical layout for '{layout.Type}'.", node.Source.Id, "BHUG1001"));
                    builder.AppendLine($"{indent}ApplyVerticalLayout({rect}, {ToFloatLiteral(Gap(LayoutPolicyService.ResolveGap(layout.Gap, node.Policy), false))}, {ToRectOffsetArgs(LayoutPolicyService.ResolvePadding(layout.Padding, node.Policy))});");
                    break;
            }
        }

        if (style != null || node.Source.Type == ComponentType.Icon)
        {
            builder.AppendLine(
                $"{indent}ApplyStyle({accessor}, " +
                $"fg: {ToNullableStringLiteral(style?.Foreground?.ToHex())}, " +
                $"bg: {ToNullableStringLiteral(style?.Background?.ToHex())}, " +
                $"fontFamily: {ToNullableStringLiteral(TextPolicyService.ResolveFontFamily(node.Source, node.Policy))}, " +
                $"fontSize: {ToNullableIntLiteral(TextPolicyService.ResolveFontSize(node.Source, widthDimension, heightDimension, node.Policy))}, " +
                $"borderColor: {ToNullableStringLiteral(style?.Border?.Color?.ToHex())}, " +
                $"borderWidth: {ToNullableFloatLiteral(style?.Border is { Width: > 0 } border ? border.Width : null)}, " +
                $"treatAsIcon: {Bool(IsIconTextNode(node))});");
        }

        if (IsIconTextNode(node))
        {
            var width = Pixels(widthDimension) ?? 16d;
            var height = Pixels(heightDimension) ?? 16d;
            builder.AppendLine(
                $"{indent}ApplyIconMetrics({accessor}, boxWidth: {ToFloatLiteral(width)}, boxHeight: {ToFloatLiteral(height)}, baselineOffset: {ToFloatLiteral(IconPolicyService.ResolveBaselineOffset(node.Policy))}, opticalCentering: {Bool(IconPolicyService.UseOpticalCentering(node.Policy))}, sizeMode: {ToStringLiteral(IconPolicyService.ResolveSizeMode(node.Policy))}, explicitFontSize: {ToFloatLiteral(IconPolicyService.ResolveFontSize(node.Policy) ?? 0d)});");
        }

        if (ShouldApplyTextMetrics(node))
        {
            builder.AppendLine($"{indent}ApplyTextMetrics({accessor}, lineSpacing: {ToNullableFloatLiteral(TextPolicyService.ResolveLineSpacing(node.Source, widthDimension, heightDimension, node.Policy))}, wrapText: {Bool(TextPolicyService.ShouldWrapText(node.Source, node.Policy))});");
        }

        foreach (var pair in Bindings(node.Source).Where(static pair => pair.StaticValue != null))
        {
            if (TryAssignment(node, pair.Property, pair.StaticValue!, staticValue: true, out var assignment))
            {
                builder.AppendLine($"{indent}{assignment}");
            }
        }

        if (!node.Source.Visible.IsBound)
        {
            builder.AppendLine($"{indent}{accessor}.gameObject.SetActive({Bool(node.Source.Visible.Value != false)});");
        }

        if (!node.Source.Enabled.IsBound && IsSelectable(node))
        {
            builder.AppendLine($"{indent}ApplyEnabled({accessor}, {Bool(node.Source.Enabled.Value != false)});");
        }

        if (node.Source.ComponentRefId != null && node.ComponentView == null && !components.ContainsKey(node.Source.ComponentRefId))
        {
            diagnostics.Add(Diagnostic.Warning($"Component reference '{node.Source.ComponentRefId}' was not found for uGUI generation.", node.Source.Id, "BHUG1004"));
        }
    }

    private static void AppendBindExisting(StringBuilder builder, PlannedNode node, string? parentPath, int indentLevel)
    {
        foreach (var child in node.Children)
        {
            var indent = new string(' ', indentLevel * 4);
            var path = string.IsNullOrEmpty(parentPath) ? child.Name : parentPath + "/" + child.Name;
            builder.AppendLine($"{indent}{child.FieldName} = {BindLookup(child, path)};");
            AppendBindExisting(builder, child, path, indentLevel);
        }
    }

    private static void AppendRefresh(StringBuilder builder, PlannedNode node, PlanDocument plan, int indentLevel)
    {
        var indent = new string(' ', indentLevel * 4);
        var accessor = node.FieldName == "Root" ? "Root" : node.FieldName;
        if (node.Source.Visible.IsBound && TryIdentifier(plan, node.Source.Visible.BindingPath!, out var visible))
        {
            builder.AppendLine($"{indent}{accessor}.gameObject.SetActive(AsBool(_viewModel.{visible}, true));");
        }

        if (node.Source.Enabled.IsBound && IsSelectable(node) && TryIdentifier(plan, node.Source.Enabled.BindingPath!, out var enabled))
        {
            builder.AppendLine($"{indent}ApplyEnabled({accessor}, AsBool(_viewModel.{enabled}, true));");
        }

        foreach (var pair in Bindings(node.Source).Where(static pair => pair.BindingPath != null))
        {
            if (TryIdentifier(plan, pair.BindingPath!, out var identifier) && TryAssignment(node, pair.Property, "_viewModel." + identifier, staticValue: false, out var assignment))
            {
                builder.AppendLine($"{indent}{assignment}");
            }
        }

        foreach (var child in node.Children)
        {
            AppendRefresh(builder, child, plan, indentLevel);
        }
    }

    private static bool TryAssignment(PlannedNode node, string property, string value, bool staticValue, out string assignment)
    {
        assignment = string.Empty;
        var accessor = node.FieldName == "Root" ? "Root" : node.FieldName;
        var normalized = Normalize(property);
        var textValue = staticValue ? value : $"AsString({value})";

        if (IsIconTextNode(node) && normalized is "text" or "content" or "value")
        {
            assignment = $"{accessor}.text = ResolveIconText({textValue});";
            return true;
        }

        switch (node.FieldType)
        {
            case "Text":
                if (normalized is "text" or "content" or "value") { assignment = $"{accessor}.text = {textValue};"; return true; }
                break;
            case "Button":
                if (normalized is "text" or "content" or "value") { assignment = $"SetButtonText({accessor}, {textValue});"; return true; }
                break;
            case "InputField":
                if (normalized is "text" or "content" or "value") { assignment = $"{accessor}.text = {textValue};"; return true; }
                break;
            case "Toggle":
                if (normalized is "checked" or "value") { assignment = $"{accessor}.isOn = {(staticValue ? value : $"AsBool({value}, false)")};"; return true; }
                if (normalized is "text" or "content") { assignment = $"SetToggleText({accessor}, {textValue});"; return true; }
                break;
            case "Slider":
                if (normalized == "value") { assignment = $"{accessor}.value = {(staticValue ? value : $"AsFloat({value})")};"; return true; }
                break;
            case "Image":
                if (normalized is "source" or "src" or "value") { assignment = $"SetImage({accessor}, {textValue});"; return true; }
                break;
        }

        return false;
    }

    private static string BindLookup(PlannedNode node, string path)
        => node.FieldType == "RectTransform"
            ? $"RequireRect(Root, \"{path}\")"
            : $"RequireComponent<{node.FieldType}>(Root, \"{path}\")";

    private static IEnumerable<(string Property, string? StaticValue, string? BindingPath)> Bindings(ComponentNode node)
    {
        foreach (var binding in node.Bindings) yield return (binding.Property, null, binding.Path);
        foreach (var property in node.Properties)
        {
            yield return property.Value.IsBound ? (property.Key, null, property.Value.BindingPath) : (property.Key, Literal(property.Value.Value), null);
        }
    }

    private static bool TryIdentifier(PlanDocument plan, string path, out string identifier)
    {
        var match = plan.Properties.FirstOrDefault(p => string.Equals(p.Path, path, StringComparison.Ordinal));
        if (match == null)
        {
            identifier = string.Empty;
            return false;
        }

        identifier = match.Identifier;
        return true;
    }

    private static double? AbsoluteOffset(ComponentNode node, Func<LayoutSpec, Dimension?> selector, string metadataKey, ResolvedGeneratorPolicy policy, string axis)
    {
        double? value = null;
        if (node.Layout != null && selector(node.Layout) is { Unit: DimensionUnit.Pixels } dimension)
        {
            value = dimension.Value;
        }
        else if (node.InstanceOverrides.TryGetValue(metadataKey, out var raw) && raw != null)
        {
            value = raw switch
            {
                double d => d,
                float f => f,
                int i => i,
                long l => l,
                _ => null
            };
        }

        var adjustment = LayoutPolicyService.ResolveOffsetAdjustment(axis, policy);
        if (value == null)
        {
            return Math.Abs(adjustment) > double.Epsilon ? adjustment : null;
        }

        return value + adjustment;
    }

    private static double? Pixels(Dimension? dimension)
        => dimension switch
        {
            { Unit: DimensionUnit.Pixels } pixels => pixels.Value,
            { Unit: DimensionUnit.Cells } cells => cells.Value,
            _ => null
        };

    private static double? FlexibleSize(PlannedNode node, Dimension? dimension, string axis, LayoutType? parentLayout)
        => LayoutPolicyService.ResolveFlexibleSize(dimension, axis, parentLayout, IsFlexibleContainer(node), node.Policy);

    private static double? PreferredSize(PlannedNode node, Dimension? dimension, string axis)
        => LayoutPolicyService.ResolvePreferredSize(dimension, axis, node.Policy);

    private static bool IsFlexibleContainer(PlannedNode node)
        => node.ComponentView != null
            || node.Source.Children.Count > 0
            || node.FieldType is "RectTransform" or "ScrollRect";

    private static bool ShouldEmitLayoutGroup(PlannedNode node)
        => node.Source.Children.Count > 0
            && node.ComponentView == null
            && node.FieldType is "RectTransform" or "ScrollRect";

    private static bool ShouldContentFit(PlannedNode node, Dimension? dimension, string axis, LayoutType? parentLayout)
        => LayoutPolicyService.ShouldPreferContentSize(axis, parentLayout != null, node.Source.Layout, IsFlexibleContainer(node), node.Policy);

    private static bool ShouldApplyTextMetrics(PlannedNode node)
        => node.FieldType is "Text" or "Button" or "Toggle" or "InputField";

    private static double Gap(Spacing? spacing, bool horizontal)
        => spacing == null ? 0d : horizontal ? Math.Max(spacing.Value.Left, spacing.Value.Right) : Math.Max(spacing.Value.Top, spacing.Value.Bottom);

    private static string ToRectOffsetArgs(Spacing? spacing)
    {
        var top = ToRectOffsetLiteral(spacing?.Top);
        var right = ToRectOffsetLiteral(spacing?.Right);
        var bottom = ToRectOffsetLiteral(spacing?.Bottom);
        var left = ToRectOffsetLiteral(spacing?.Left);
        return $"{left}, {right}, {top}, {bottom}";
    }

    private static string ToRectOffsetLiteral(double? value)
        => Convert.ToInt32(Math.Round(value ?? 0d, MidpointRounding.AwayFromZero), CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture);

    private static string ChildParent(PlannedNode node)
        => node.FieldType == "ScrollRect" ? $"{ToCamel(node.FieldName)}Content" : $"RectOf({node.FieldName})";

    private static string CreateCall(PlannedNode node, string parentAccessor)
        => node.FieldType switch
        {
            "Text" => $"CreateText(\"{node.Name}\", {parentAccessor})",
            "Button" => $"CreateButton(\"{node.Name}\", {parentAccessor})",
            "InputField" => $"CreateInput(\"{node.Name}\", {parentAccessor}, {Bool(node.Source.Type == ComponentType.TextArea)})",
            "Toggle" => $"CreateToggle(\"{node.Name}\", {parentAccessor})",
            "Slider" => $"CreateSlider(\"{node.Name}\", {parentAccessor}, {Bool(node.Source.Type == ComponentType.Slider)})",
            "Image" => $"CreateImage(\"{node.Name}\", {parentAccessor})",
            "ScrollRect" => $"CreateScroll(\"{node.Name}\", {parentAccessor}, out var {ToCamel(node.FieldName)}Content)",
            _ => $"CreateRect(\"{node.Name}\", {parentAccessor})"
        };

    private static bool IsSelectable(PlannedNode node)
        => node.FieldType is "Button" or "Toggle" or "Slider" or "InputField";

    private static bool IsIconTextNode(PlannedNode node)
        => node.Source.Type == ComponentType.Icon && node.FieldType == "Text";

    private static string Normalize(string property)
        => new string(property.Where(char.IsLetterOrDigit).ToArray()).ToLowerInvariant();

    private static string? Literal(object? value)
        => value switch
        {
            null => null,
            string s => ToStringLiteral(s),
            bool b => Bool(b),
            float f => ToFloatLiteral(f),
            double d => d.ToString(CultureInfo.InvariantCulture),
            int i => i.ToString(CultureInfo.InvariantCulture),
            long l => l.ToString(CultureInfo.InvariantCulture),
            _ => ToStringLiteral(value.ToString() ?? string.Empty)
        };

    private static string ToStringLiteral(string value)
        => "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal).Replace("\r", "\\r", StringComparison.Ordinal).Replace("\n", "\\n", StringComparison.Ordinal) + "\"";

    private static string Bool(bool value) => value ? "true" : "false";
    private static string ToFloatLiteral(double value) => value.ToString("0.###", CultureInfo.InvariantCulture) + "f";
    private static string ToNullableFloatLiteral(double? value) => value == null ? "null" : ToFloatLiteral(value.Value);
    private static string ToNullableIntLiteral(double? value) => value == null ? "null" : Convert.ToInt32(Math.Round(value.Value, MidpointRounding.AwayFromZero), CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture);
    private static string ToNullableStringLiteral(string? value) => value == null ? "null" : ToStringLiteral(value);
    private static string ToCamel(string value) => string.IsNullOrEmpty(value) ? "value" : char.ToLowerInvariant(value[0]) + value[1..];
    private static string ToPropertyIdentifier(string path) => SanitizeIdentifier(Pascalize(path), "Value");
    private static string Pascalize(string value) => string.Concat(value.Split(['.', ':', '-', '/', ' ', '_'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).Select(static part => char.ToUpperInvariant(part[0]) + part[1..]));
    private static string SanitizeIdentifier(string value, string fallbackPrefix)
    {
        var cleaned = new string(value.Where(ch => char.IsLetterOrDigit(ch) || ch == '_').ToArray());
        if (string.IsNullOrEmpty(cleaned))
        {
            return fallbackPrefix;
        }

        return char.IsLetter(cleaned[0]) || cleaned[0] == '_'
            ? cleaned
            : fallbackPrefix + cleaned;
    }

    private static readonly string HelperCode = """
    private static RectTransform CreateRect(string name, Transform? parent){var go=new GameObject(name,typeof(RectTransform));var rect=go.GetComponent<RectTransform>();if(parent!=null)rect.SetParent(parent,false);rect.localScale=Vector3.one;rect.anchorMin=new Vector2(0f,1f);rect.anchorMax=new Vector2(0f,1f);rect.pivot=new Vector2(0f,1f);return rect;}
    private static RectTransform RequireRect(Transform root,string path){var target=root.Find(path);if(target==null||!target.TryGetComponent<RectTransform>(out var rect))throw new InvalidOperationException($"Required RectTransform '{path}' was not found beneath '{root.name}'.");return rect;}
    private static T RequireComponent<T>(Transform root,string path) where T : Component{var target=root.Find(path);if(target==null||!target.TryGetComponent<T>(out var component))throw new InvalidOperationException($"Required component '{typeof(T).Name}' at '{path}' was not found beneath '{root.name}'.");return component;}
    private static Text CreateText(string name, Transform? parent){var rect=CreateRect(name,parent);rect.gameObject.AddComponent<CanvasRenderer>();var text=rect.gameObject.AddComponent<Text>();text.font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");text.horizontalOverflow=HorizontalWrapMode.Overflow;text.verticalOverflow=VerticalWrapMode.Overflow;text.supportRichText=true;return text;}
    private static Image CreateImage(string name, Transform? parent){var rect=CreateRect(name,parent);rect.gameObject.AddComponent<CanvasRenderer>();return rect.gameObject.AddComponent<Image>();}
    private static Button CreateButton(string name, Transform? parent){var image=CreateImage(name,parent);var button=image.gameObject.AddComponent<Button>();button.targetGraphic=image;var label=CreateText("Label",image.transform);Stretch(RectOf(label));label.alignment=TextAnchor.MiddleCenter;return button;}
    private static Toggle CreateToggle(string name, Transform? parent){var root=CreateRect(name,parent);var toggle=root.gameObject.AddComponent<Toggle>();var bg=CreateImage("Background",root);ConfigureRect(RectOf(bg),18f,18f,0f,0f,true);var check=CreateImage("Checkmark",RectOf(bg));Stretch(RectOf(check));var label=CreateText("Label",root);ConfigureRect(RectOf(label),null,18f,24f,0f,true);toggle.targetGraphic=bg;toggle.graphic=check;return toggle;}
    private static Slider CreateSlider(string name, Transform? parent,bool interactable){var root=CreateRect(name,parent);var bg=CreateImage("Background",root);Stretch(RectOf(bg));var fillArea=CreateRect("Fill Area",root);Stretch(fillArea);var fill=CreateImage("Fill",fillArea);Stretch(RectOf(fill));var handleArea=CreateRect("Handle Slide Area",root);Stretch(handleArea);var handle=CreateImage("Handle",handleArea);ConfigureRect(RectOf(handle),12f,12f,0f,0f,true);var slider=root.gameObject.AddComponent<Slider>();slider.fillRect=RectOf(fill);slider.handleRect=RectOf(handle);slider.targetGraphic=handle;slider.interactable=interactable;return slider;}
    private static InputField CreateInput(string name, Transform? parent,bool multiline){var bg=CreateImage(name,parent);var text=CreateText("Text",bg.transform);Stretch(RectOf(text),6f,6f,6f,6f);text.alignment=multiline?TextAnchor.UpperLeft:TextAnchor.MiddleLeft;var input=bg.gameObject.AddComponent<InputField>();input.textComponent=text;input.lineType=multiline?InputField.LineType.MultiLineNewline:InputField.LineType.SingleLine;return input;}
    private static ScrollRect CreateScroll(string name, Transform? parent,out RectTransform content){var root=CreateImage(name,parent);var viewport=CreateImage("Viewport",root.transform);Stretch(RectOf(viewport));viewport.gameObject.AddComponent<Mask>().showMaskGraphic=false;content=CreateRect("Content",RectOf(viewport));Stretch(content);ApplyVerticalLayout(content,0f,0,0,0,0);var scroll=root.gameObject.AddComponent<ScrollRect>();scroll.viewport=RectOf(viewport);scroll.content=content;scroll.horizontal=false;scroll.vertical=true;return scroll;}
    private static void ApplyHorizontalLayout(RectTransform rect,float spacing,int paddingLeft,int paddingRight,int paddingTop,int paddingBottom){var group=rect.gameObject.GetComponent<HorizontalLayoutGroup>()??rect.gameObject.AddComponent<HorizontalLayoutGroup>();group.spacing=spacing;group.padding=new RectOffset(paddingLeft,paddingRight,paddingTop,paddingBottom);group.childControlWidth=true;group.childControlHeight=true;group.childForceExpandWidth=false;group.childForceExpandHeight=false;}
    private static void ApplyVerticalLayout(RectTransform rect,float spacing,int paddingLeft,int paddingRight,int paddingTop,int paddingBottom){var group=rect.gameObject.GetComponent<VerticalLayoutGroup>()??rect.gameObject.AddComponent<VerticalLayoutGroup>();group.spacing=spacing;group.padding=new RectOffset(paddingLeft,paddingRight,paddingTop,paddingBottom);group.childControlWidth=true;group.childControlHeight=true;group.childForceExpandWidth=false;group.childForceExpandHeight=false;}
    private static void ApplyLayoutSizing(RectTransform rect,bool ignoreLayout,float? preferredWidth,float? preferredHeight,float? flexibleWidth,float? flexibleHeight){var element=rect.gameObject.GetComponent<LayoutElement>()??rect.gameObject.AddComponent<LayoutElement>();element.ignoreLayout=ignoreLayout;element.preferredWidth=preferredWidth??-1f;element.preferredHeight=preferredHeight??-1f;element.flexibleWidth=flexibleWidth??-1f;element.flexibleHeight=flexibleHeight??-1f;}
    private static void ApplyContentSizeFit(RectTransform rect,bool horizontal,bool vertical){var fitter=rect.gameObject.GetComponent<ContentSizeFitter>()??rect.gameObject.AddComponent<ContentSizeFitter>();fitter.horizontalFit=horizontal?ContentSizeFitter.FitMode.PreferredSize:ContentSizeFitter.FitMode.Unconstrained;fitter.verticalFit=vertical?ContentSizeFitter.FitMode.PreferredSize:ContentSizeFitter.FitMode.Unconstrained;}
    private static void ConfigureRect(RectTransform rect,float? width,float? height,float? left,float? top,bool absolute){if(absolute){rect.anchorMin=new Vector2(0f,1f);rect.anchorMax=new Vector2(0f,1f);rect.pivot=new Vector2(0f,1f);rect.anchoredPosition=new Vector2(left??0f,-(top??0f));}if(width.HasValue)rect.SetSizeWithCurrentAnchors(RectTransform.Axis.Horizontal,width.Value);if(height.HasValue)rect.SetSizeWithCurrentAnchors(RectTransform.Axis.Vertical,height.Value);}
    private static void ApplyRectAnchorPreset(RectTransform rect,string preset){switch(NormalizeRectPreset(preset)){case "top-left":case "start":rect.anchorMin=new Vector2(0f,1f);rect.anchorMax=new Vector2(0f,1f);break;case "top-center":rect.anchorMin=new Vector2(0.5f,1f);rect.anchorMax=new Vector2(0.5f,1f);break;case "top-right":case "end":rect.anchorMin=new Vector2(1f,1f);rect.anchorMax=new Vector2(1f,1f);break;case "center":case "middle-center":rect.anchorMin=new Vector2(0.5f,0.5f);rect.anchorMax=new Vector2(0.5f,0.5f);break;case "stretch":rect.anchorMin=new Vector2(0f,0f);rect.anchorMax=new Vector2(1f,1f);break;case "stretch-horizontal":rect.anchorMin=new Vector2(0f,1f);rect.anchorMax=new Vector2(1f,1f);break;case "stretch-vertical":rect.anchorMin=new Vector2(0f,0f);rect.anchorMax=new Vector2(0f,1f);break;}}
    private static void ApplyRectPivotPreset(RectTransform rect,string preset){switch(NormalizeRectPreset(preset)){case "top-left":case "start":rect.pivot=new Vector2(0f,1f);break;case "top-center":rect.pivot=new Vector2(0.5f,1f);break;case "top-right":case "end":rect.pivot=new Vector2(1f,1f);break;case "center":case "middle-center":rect.pivot=new Vector2(0.5f,0.5f);break;case "bottom-left":rect.pivot=new Vector2(0f,0f);break;case "bottom-center":rect.pivot=new Vector2(0.5f,0f);break;case "bottom-right":rect.pivot=new Vector2(1f,0f);break;}}
    private static void ApplyRectTransformMode(RectTransform rect,string mode){switch(NormalizeRectPreset(mode)){case "stretch-parent":case "stretch":Stretch(rect);break;case "absolute-overlay":rect.anchorMin=new Vector2(0f,1f);rect.anchorMax=new Vector2(0f,1f);rect.pivot=new Vector2(0f,1f);break;case "top-left":ApplyRectAnchorPreset(rect,"top-left");ApplyRectPivotPreset(rect,"top-left");break;case "center":ApplyRectAnchorPreset(rect,"center");ApplyRectPivotPreset(rect,"center");break;}}
    private static void ApplyEdgeInsetPolicy(RectTransform rect,string policy){switch(NormalizeRectPreset(policy)){case "match-parent":Stretch(rect);break;case "zero-offsets":rect.offsetMin=Vector2.zero;rect.offsetMax=Vector2.zero;break;}}
    private static string NormalizeRectPreset(string? value)=>string.IsNullOrWhiteSpace(value)?string.Empty:value.Trim().ToLowerInvariant();
    private static void Stretch(RectTransform rect,float left=0f,float right=0f,float top=0f,float bottom=0f){rect.anchorMin=new Vector2(0f,0f);rect.anchorMax=new Vector2(1f,1f);rect.pivot=new Vector2(0.5f,0.5f);rect.offsetMin=new Vector2(left,bottom);rect.offsetMax=new Vector2(-right,-top);}
    private static void ApplyStyle(Component component,string? fg,string? bg,string? fontFamily,int? fontSize,string? borderColor,float? borderWidth,bool treatAsIcon){if(!string.IsNullOrWhiteSpace(bg))EnsureImage(component.gameObject).color=ParseColor(bg,Color.white);if(!string.IsNullOrWhiteSpace(borderColor)&&borderWidth.HasValue&&borderWidth.Value>0f)ApplyBorder(component.gameObject,ParseColor(borderColor,Color.white),borderWidth.Value);if(component is Text text){if(!string.IsNullOrWhiteSpace(fg))text.color=ParseColor(fg,text.color);if(!string.IsNullOrWhiteSpace(fontFamily)&&TryFont(fontFamily,out var font))text.font=font;if(fontSize.HasValue)text.fontSize=fontSize.Value;if(treatAsIcon){text.alignment=TextAnchor.MiddleCenter;text.horizontalOverflow=HorizontalWrapMode.Overflow;text.verticalOverflow=VerticalWrapMode.Overflow;}}else if(component is Button button&&TryLabel(button.gameObject,out var label)){if(!string.IsNullOrWhiteSpace(fg))label.color=ParseColor(fg,label.color);if(!string.IsNullOrWhiteSpace(fontFamily)&&TryFont(fontFamily,out var font))label.font=font;if(fontSize.HasValue)label.fontSize=fontSize.Value;}else if(component is Toggle toggle&&TryLabel(toggle.gameObject,out var toggleLabel)){if(!string.IsNullOrWhiteSpace(fg))toggleLabel.color=ParseColor(fg,toggleLabel.color);if(!string.IsNullOrWhiteSpace(fontFamily)&&TryFont(fontFamily,out var font))toggleLabel.font=font;if(fontSize.HasValue)toggleLabel.fontSize=fontSize.Value;}else if(component is InputField input&&input.textComponent!=null){if(!string.IsNullOrWhiteSpace(fg))input.textComponent.color=ParseColor(fg,input.textComponent.color);if(!string.IsNullOrWhiteSpace(fontFamily)&&TryFont(fontFamily,out var font))input.textComponent.font=font;if(fontSize.HasValue)input.textComponent.fontSize=fontSize.Value;}}
    private static void ApplyIconMetrics(Component component,float boxWidth,float boxHeight,float baselineOffset,bool opticalCentering,string sizeMode,float explicitFontSize){if(component is not Text text)return;var iconSize=explicitFontSize>0f?explicitFontSize:string.Equals(sizeMode,"match-height",StringComparison.OrdinalIgnoreCase)?Mathf.Max(1f,boxHeight):Mathf.Max(1f,Mathf.Min(boxWidth,boxHeight));text.fontSize=Mathf.RoundToInt(iconSize);text.alignment=opticalCentering?TextAnchor.MiddleCenter:TextAnchor.UpperCenter;text.horizontalOverflow=HorizontalWrapMode.Overflow;text.verticalOverflow=VerticalWrapMode.Overflow;var rect=RectOf(text);if(opticalCentering&&Mathf.Approximately(baselineOffset,0f)&&boxHeight>iconSize){baselineOffset=-1f;}rect.anchoredPosition=new Vector2(rect.anchoredPosition.x,baselineOffset);}
    private static void ApplyTextMetrics(Component component,float? lineSpacing,bool wrapText){if(component is Text text){if(lineSpacing.HasValue)text.lineSpacing=lineSpacing.Value;text.horizontalOverflow=wrapText?HorizontalWrapMode.Wrap:HorizontalWrapMode.Overflow;text.verticalOverflow=VerticalWrapMode.Overflow;return;}if(component is Button button&&TryLabel(button.gameObject,out var label)){if(lineSpacing.HasValue)label.lineSpacing=lineSpacing.Value;label.horizontalOverflow=wrapText?HorizontalWrapMode.Wrap:HorizontalWrapMode.Overflow;label.verticalOverflow=VerticalWrapMode.Overflow;return;}if(component is Toggle toggle&&TryLabel(toggle.gameObject,out var toggleLabel)){if(lineSpacing.HasValue)toggleLabel.lineSpacing=lineSpacing.Value;toggleLabel.horizontalOverflow=wrapText?HorizontalWrapMode.Wrap:HorizontalWrapMode.Overflow;toggleLabel.verticalOverflow=VerticalWrapMode.Overflow;return;}if(component is InputField input&&input.textComponent!=null){if(lineSpacing.HasValue)input.textComponent.lineSpacing=lineSpacing.Value;input.textComponent.horizontalOverflow=wrapText?HorizontalWrapMode.Wrap:HorizontalWrapMode.Overflow;input.textComponent.verticalOverflow=VerticalWrapMode.Overflow;}}
    private static void ApplyEnabled(Component component,bool enabled){if(component is Selectable selectable){selectable.interactable=enabled;return;}component.gameObject.SetActive(enabled);}
    private static void SetButtonText(Button button,string? value){if(TryLabel(button.gameObject,out var label))label.text=value??string.Empty;}
    private static void SetToggleText(Toggle toggle,string? value){if(TryLabel(toggle.gameObject,out var label))label.text=value??string.Empty;}
    private static void SetImage(Image image,string? path){image.sprite=string.IsNullOrWhiteSpace(path)?null:Resources.Load<Sprite>(path);}
    private static bool TryLabel(GameObject go,out Text label){label=go.GetComponentInChildren<Text>(true);return label!=null;}
    private static bool TryFont(string familyName,out Font font){var resourcePath=familyName switch{"Press Start 2P"=>"BoomHudFonts/PressStart2P-Regular","lucide"=>"BoomHudFonts/lucide",_=>familyName};font=Resources.Load<Font>(resourcePath)??Resources.Load<Font>(familyName);return font!=null;}
    private static void ApplyBorder(GameObject go,Color color,float width){var outline=go.GetComponent<Outline>()??go.AddComponent<Outline>();outline.effectColor=color;outline.effectDistance=new Vector2(width,-width);outline.useGraphicAlpha=false;}
    private static Image EnsureImage(GameObject go){var image=go.GetComponent<Image>();if(image==null){if(go.GetComponent<CanvasRenderer>()==null)go.AddComponent<CanvasRenderer>();image=go.AddComponent<Image>();}return image;}
    private static RectTransform RectOf(Component component)=>component.GetComponent<RectTransform>();
    private static RectTransform RectOf(RectTransform rect)=>rect;
    private static string ResolveIconText(string? value)=>value switch{"cross"=>"\uE1E5","flame"=>"\uE0D2","flask-conical"=>"\uE0D5","moon"=>"\uE11E","shield"=>"\uE158","sparkles"=>"\uE412","sword"=>"\uE2B3","swords"=>"\uE2B4","wand"=>"\uE246","wand-2"=>"\uE357","wand-sparkles"=>"\uE357",_=>value??string.Empty};
    private static bool AsBool(object? value,bool fallback)=>value is bool b?b:value is string s&&bool.TryParse(s,out var parsed)?parsed:fallback;
    private static float AsFloat(object? value)=>value switch{float f=>f,double d=>(float)d,int i=>i,long l=>l,decimal m=>(float)m,string s when float.TryParse(s,NumberStyles.Float,CultureInfo.InvariantCulture,out var parsed)=>parsed,_=>0f};
    private static string AsString(object? value)=>value?.ToString()??string.Empty;
    private static Color ParseColor(string? value,Color fallback)=>!string.IsNullOrWhiteSpace(value)&&ColorUtility.TryParseHtmlString(value,out var color)?color:fallback;
""";

    private sealed class Planner
    {
        public static PlanDocument Create(HudDocument document, List<Diagnostic> diagnostics, GeneratorRuleSet? ruleSet)
        {
            var names = new HashSet<string>(StringComparer.Ordinal);
            var props = new Dictionary<string, ViewModelProperty>(StringComparer.Ordinal);
            var ruleResolver = new RuleResolver(ruleSet, "ugui");
            var root = CreateNode(document.Root, document.Name + "Root", document, diagnostics, names, props, ruleResolver, document.Name, forceRoot: true);
            return new PlanDocument
            {
                Root = root,
                Nodes = Flatten(root).Where(static n => n.FieldName != "Root").ToList(),
                Properties = props.Values.OrderBy(static p => p.Identifier, StringComparer.Ordinal).ToList()
            };
        }

        private static PlannedNode CreateNode(ComponentNode source, string fallbackName, HudDocument document, List<Diagnostic> diagnostics, HashSet<string> names, Dictionary<string, ViewModelProperty> props, RuleResolver ruleResolver, string documentName, bool forceRoot = false)
        {
            Track(source, props);
            var baseName = forceRoot ? document.Name + "Root" : Pascal(source.Id ?? fallbackName);
            var fieldName = forceRoot ? "Root" : Unique(baseName, names);
            var policy = ruleResolver.Resolve(documentName, source);
            var fieldType = ResolveFieldType(source, document, diagnostics, policy, out var componentView);
            var children = componentView == null
                ? source.Children.Select((child, index) => CreateNode(child, child.Id ?? child.Type + (index + 1).ToString(CultureInfo.InvariantCulture), document, diagnostics, names, props, ruleResolver, documentName)).ToList()
                : [];
            return new PlannedNode { Name = forceRoot ? document.Name + "Root" : fieldName, FieldName = fieldName, FieldType = fieldType, ComponentView = componentView, Source = source, Policy = policy, Children = children };
        }

        private static void Track(ComponentNode node, Dictionary<string, ViewModelProperty> props)
        {
            if (node.Visible.IsBound) Add(props, node.Visible.BindingPath!);
            if (node.Enabled.IsBound) Add(props, node.Enabled.BindingPath!);
            foreach (var binding in node.Bindings) Add(props, binding.Path);
            foreach (var property in node.Properties.Values.Where(static p => p.IsBound)) Add(props, property.BindingPath!);
        }

        private static void Add(Dictionary<string, ViewModelProperty> props, string path)
        {
            if (!props.ContainsKey(path)) props[path] = new ViewModelProperty { Path = path, Identifier = ToPropertyIdentifier(path) };
        }

        private static string ResolveFieldType(ComponentNode source, HudDocument document, List<Diagnostic> diagnostics, ResolvedGeneratorPolicy policy, out string? componentView)
        {
            componentView = null;
            if (source.ComponentRefId != null && source.Children.Count == 0 && document.Components.TryGetValue(source.ComponentRefId, out var component))
            {
                componentView = component.Name;
                return "RectTransform";
            }

            if (!string.IsNullOrWhiteSpace(policy.ControlType))
            {
                if (TryMapControlOverride(policy.ControlType!, out var overrideFieldType))
                {
                    return overrideFieldType;
                }

                diagnostics.Add(Diagnostic.Warning(
                    $"Unity uGUI control override '{policy.ControlType}' is not recognized; using default mapping.",
                    source.Id,
                    "BHUG1003"));
            }

            return source.Type switch
            {
                ComponentType.Label or ComponentType.Badge or ComponentType.Icon => "Text",
                ComponentType.Button or ComponentType.MenuItem => "Button",
                ComponentType.TextInput or ComponentType.TextArea => "InputField",
                ComponentType.Checkbox or ComponentType.RadioButton => "Toggle",
                ComponentType.ProgressBar or ComponentType.Slider => "Slider",
                ComponentType.Image => "Image",
                ComponentType.ScrollView or ComponentType.ListBox or ComponentType.ListView or ComponentType.TreeView or ComponentType.DataGrid or ComponentType.Timeline => "ScrollRect",
                _ => "RectTransform"
            };
        }

        private static bool TryMapControlOverride(string controlType, out string fieldType)
        {
            fieldType = controlType.Trim() switch
            {
                "Label" or "Text" => "Text",
                "Button" => "Button",
                "TextField" or "InputField" => "InputField",
                "Toggle" => "Toggle",
                "ProgressBar" or "Slider" => "Slider",
                "Image" => "Image",
                "ScrollView" or "ScrollRect" => "ScrollRect",
                "Container" or "RectTransform" => "RectTransform",
                _ => string.Empty
            };

            return fieldType.Length > 0;
        }

        private static string Unique(string baseName, HashSet<string> names)
        {
            var candidate = baseName;
            var suffix = 2;
            while (!names.Add(candidate))
            {
                candidate = baseName + suffix.ToString(CultureInfo.InvariantCulture);
                suffix++;
            }
            return candidate;
        }

        private static string Pascal(string value)
            => SanitizeIdentifier(Pascalize(value), "Node");

        private static IEnumerable<PlannedNode> Flatten(PlannedNode node)
        {
            yield return node;
            foreach (var child in node.Children)
            {
                foreach (var descendant in Flatten(child))
                {
                    yield return descendant;
                }
            }
        }
    }

    private sealed record PlanDocument
    {
        public required PlannedNode Root { get; init; }
        public required IReadOnlyList<PlannedNode> Nodes { get; init; }
        public required IReadOnlyList<ViewModelProperty> Properties { get; init; }
    }

    private sealed record PlannedNode
    {
        public required string Name { get; init; }
        public required string FieldName { get; init; }
        public required string FieldType { get; init; }
        public string? ComponentView { get; init; }
        public required ComponentNode Source { get; init; }
        public required ResolvedGeneratorPolicy Policy { get; init; }
        public required IReadOnlyList<PlannedNode> Children { get; init; }
    }

    private sealed record ViewModelProperty
    {
        public required string Path { get; init; }
        public required string Identifier { get; init; }
    }
}
