// <auto-generated>
// Generated by BoomHud.Gen.TerminalGui from DebugOverlay
// </auto-generated>

#nullable enable

namespace Generated;

/// <summary>
/// ViewModel interface for DebugOverlay.
/// </summary>
public interface IDebugOverlayViewModel
{
    object? CurrentChunk { get; }
    object? Fps { get; }
    object? MemoryUsage { get; }
    object? PlayerPosition { get; }
    object? Version { get; }
}
