// <auto-generated>
// Generated by BoomHud.Gen.Unity from motion document CharPortraitMotion
// </auto-generated>

#nullable enable

using System;
using UnityEngine;
using UnityEngine.UIElements;

namespace Generated.Hud
{
public static class CharPortraitMotion
{
    public const int FramesPerSecond = 30;
    public const string DefaultClipId = "portraitIntro";
    public static readonly string[] ClipIds =
    {
        "portraitIntro",
        "hpBarFill",
        "mpBarFill",
        "stat1Reveal",
        "stat2Reveal",
        "atkReveal",
        "magReveal",
        "defReveal",
        "itemReveal",
    };

    public const string DefaultSequenceId = "generatedMotionDemo";
    public static readonly string[] SequenceIds =
    {
        "generatedMotionDemo",
    };

    public enum TimelineSequenceFillMode
    {
        None,
        HoldStart,
        HoldEnd,
        HoldBoth
    }

    public sealed class TimelineSequenceClip
    {
        public string ClipId { get; set; } = string.Empty;
        public int StartFrame { get; set; }
        public int DurationFrames { get; set; }
        public TimelineSequenceFillMode FillMode { get; set; } = TimelineSequenceFillMode.None;
    }

    public static TimelineSequenceClip[] GetSequenceItems(string sequenceId)
    {
        return sequenceId switch
        {
            "generatedMotionDemo" => new[]
            {
                new TimelineSequenceClip
                {
                    ClipId = "portraitIntro",
                    StartFrame = 0,
                    DurationFrames = 0,
                    FillMode = TimelineSequenceFillMode.HoldEnd
                },
                new TimelineSequenceClip
                {
                    ClipId = "hpBarFill",
                    StartFrame = 14,
                    DurationFrames = 0,
                    FillMode = TimelineSequenceFillMode.HoldBoth
                },
                new TimelineSequenceClip
                {
                    ClipId = "mpBarFill",
                    StartFrame = 22,
                    DurationFrames = 0,
                    FillMode = TimelineSequenceFillMode.HoldBoth
                },
                new TimelineSequenceClip
                {
                    ClipId = "stat1Reveal",
                    StartFrame = 28,
                    DurationFrames = 0,
                    FillMode = TimelineSequenceFillMode.HoldBoth
                },
                new TimelineSequenceClip
                {
                    ClipId = "stat2Reveal",
                    StartFrame = 34,
                    DurationFrames = 0,
                    FillMode = TimelineSequenceFillMode.HoldBoth
                },
                new TimelineSequenceClip
                {
                    ClipId = "atkReveal",
                    StartFrame = 42,
                    DurationFrames = 0,
                    FillMode = TimelineSequenceFillMode.HoldBoth
                },
                new TimelineSequenceClip
                {
                    ClipId = "magReveal",
                    StartFrame = 48,
                    DurationFrames = 0,
                    FillMode = TimelineSequenceFillMode.HoldBoth
                },
                new TimelineSequenceClip
                {
                    ClipId = "defReveal",
                    StartFrame = 54,
                    DurationFrames = 0,
                    FillMode = TimelineSequenceFillMode.HoldBoth
                },
                new TimelineSequenceClip
                {
                    ClipId = "itemReveal",
                    StartFrame = 60,
                    DurationFrames = 0,
                    FillMode = TimelineSequenceFillMode.HoldBoth
                },
            },
            _ => Array.Empty<TimelineSequenceClip>()
        };
    }

    public static bool TryApplyAtFrame(CharPortraitView view, string clipId, int frame)
    {
        if (view == null)
        {
            throw new ArgumentNullException(nameof(view));
        }

        return clipId switch
        {
            "portraitIntro" => ApplyPortraitIntro(view, frame),
            "hpBarFill" => ApplyHpBarFill(view, frame),
            "mpBarFill" => ApplyMpBarFill(view, frame),
            "stat1Reveal" => ApplyStat1Reveal(view, frame),
            "stat2Reveal" => ApplyStat2Reveal(view, frame),
            "atkReveal" => ApplyAtkReveal(view, frame),
            "magReveal" => ApplyMagReveal(view, frame),
            "defReveal" => ApplyDefReveal(view, frame),
            "itemReveal" => ApplyItemReveal(view, frame),
            _ => false
        };
    }

    public static bool TryApplyAtTime(CharPortraitView view, string clipId, float timeSeconds)
    {
        return TryApplyAtFrame(view, clipId, Mathf.Max(0, Mathf.RoundToInt(timeSeconds * FramesPerSecond)));
    }

    public static int GetClipDurationFrames(string clipId)
    {
        return clipId switch
        {
            "portraitIntro" => 24,
            "hpBarFill" => 22,
            "mpBarFill" => 22,
            "stat1Reveal" => 16,
            "stat2Reveal" => 16,
            "atkReveal" => 12,
            "magReveal" => 12,
            "defReveal" => 12,
            "itemReveal" => 12,
            _ => 0
        };
    }

    public static float GetClipDurationSeconds(string clipId)
    {
        return GetClipDurationFrames(clipId) / (float)FramesPerSecond;
    }

    private static readonly NumberKeyframe[] s_PortraitIntroPortraitRootOpacity =
    {
        new NumberKeyframe(0, 0f, EaseMode.Linear),
        new NumberKeyframe(12, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_PortraitIntroPortraitRootPositionY =
    {
        new NumberKeyframe(0, 24f, EaseMode.Linear),
        new NumberKeyframe(18, 0f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_PortraitIntroFaceRevealOpacity =
    {
        new NumberKeyframe(0, 0f, EaseMode.Linear),
        new NumberKeyframe(12, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_PortraitIntroFaceRevealScaleX =
    {
        new NumberKeyframe(0, 0.78f, EaseMode.Linear),
        new NumberKeyframe(16, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_PortraitIntroFaceRevealScaleY =
    {
        new NumberKeyframe(0, 0.78f, EaseMode.Linear),
        new NumberKeyframe(16, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_PortraitIntroClassIconSettleOpacity =
    {
        new NumberKeyframe(0, 0f, EaseMode.Linear),
        new NumberKeyframe(12, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_PortraitIntroClassIconSettleRotation =
    {
        new NumberKeyframe(0, -14f, EaseMode.Linear),
        new NumberKeyframe(16, 0f, EaseMode.EaseInOut),
    };

    private static readonly StringKeyframe[] s_PortraitIntroNameBootText =
    {
        new StringKeyframe(0, "SCANNING"),
        new StringKeyframe(18, "AELRIC"),
    };

    private static readonly StringKeyframe[] s_PortraitIntroNameBootColor =
    {
        new StringKeyframe(0, "#d6c6a4"),
        new StringKeyframe(18, "#ffffff"),
    };

    private static readonly NumberKeyframe[] s_PortraitIntroNameBootPositionX =
    {
        new NumberKeyframe(0, -10f, EaseMode.Linear),
        new NumberKeyframe(16, 0f, EaseMode.EaseOut),
    };

    private static bool ApplyPortraitIntro(CharPortraitView view, int frame)
    {
        var localFrame = Mathf.Clamp(frame - 0, 0, 24);
        ApplyOpacity(view.Root, EvaluateNumber(localFrame, s_PortraitIntroPortraitRootOpacity, 1f));
        ApplyTranslate(view.Root, 0f, EvaluateNumber(localFrame, s_PortraitIntroPortraitRootPositionY, 0f));
        ApplyOpacity(view.Face, EvaluateNumber(localFrame, s_PortraitIntroFaceRevealOpacity, 1f));
        ApplyScale(view.Face, EvaluateNumber(localFrame, s_PortraitIntroFaceRevealScaleX, 1f), EvaluateNumber(localFrame, s_PortraitIntroFaceRevealScaleY, 1f));
        ApplyOpacity(view.ClassIcon, EvaluateNumber(localFrame, s_PortraitIntroClassIconSettleOpacity, 1f));
        ApplyRotation(view.ClassIcon, EvaluateNumber(localFrame, s_PortraitIntroClassIconSettleRotation, 0f));
        ApplyText(view.Name, EvaluateString(localFrame, s_PortraitIntroNameBootText, string.Empty));
        ApplyColor(view.Name, EvaluateString(localFrame, s_PortraitIntroNameBootColor, string.Empty));
        ApplyTranslate(view.Name, EvaluateNumber(localFrame, s_PortraitIntroNameBootPositionX, 0f), 0f);
        return true;
    }

    private static readonly NumberKeyframe[] s_HpBarFillHpFillIntroWidth =
    {
        new NumberKeyframe(0, 0f, EaseMode.Linear),
        new NumberKeyframe(22, 90f, EaseMode.EaseOut),
    };

    private static bool ApplyHpBarFill(CharPortraitView view, int frame)
    {
        var localFrame = Mathf.Clamp(frame - 0, 0, 22);
        ApplyWidth(view.HpFill, EvaluateNumber(localFrame, s_HpBarFillHpFillIntroWidth, 0f));
        return true;
    }

    private static readonly NumberKeyframe[] s_MpBarFillMpFillIntroWidth =
    {
        new NumberKeyframe(0, 0f, EaseMode.Linear),
        new NumberKeyframe(22, 60f, EaseMode.EaseOut),
    };

    private static bool ApplyMpBarFill(CharPortraitView view, int frame)
    {
        var localFrame = Mathf.Clamp(frame - 0, 0, 22);
        ApplyWidth(view.MpFill, EvaluateNumber(localFrame, s_MpBarFillMpFillIntroWidth, 0f));
        return true;
    }

    private static readonly NumberKeyframe[] s_Stat1RevealStatsRevealOpacity =
    {
        new NumberKeyframe(0, 0f, EaseMode.Linear),
        new NumberKeyframe(16, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_Stat1RevealStatsRevealPositionX =
    {
        new NumberKeyframe(0, -8f, EaseMode.Linear),
        new NumberKeyframe(16, 0f, EaseMode.EaseOut),
    };

    private static bool ApplyStat1Reveal(CharPortraitView view, int frame)
    {
        var localFrame = Mathf.Clamp(frame - 0, 0, 16);
        ApplyOpacity(view.Stat1, EvaluateNumber(localFrame, s_Stat1RevealStatsRevealOpacity, 1f));
        ApplyTranslate(view.Stat1, EvaluateNumber(localFrame, s_Stat1RevealStatsRevealPositionX, 0f), 0f);
        return true;
    }

    private static readonly NumberKeyframe[] s_Stat2RevealStatsRevealSecondaryOpacity =
    {
        new NumberKeyframe(0, 0f, EaseMode.Linear),
        new NumberKeyframe(16, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_Stat2RevealStatsRevealSecondaryPositionX =
    {
        new NumberKeyframe(0, 8f, EaseMode.Linear),
        new NumberKeyframe(16, 0f, EaseMode.EaseOut),
    };

    private static bool ApplyStat2Reveal(CharPortraitView view, int frame)
    {
        var localFrame = Mathf.Clamp(frame - 0, 0, 16);
        ApplyOpacity(view.Stat2, EvaluateNumber(localFrame, s_Stat2RevealStatsRevealSecondaryOpacity, 1f));
        ApplyTranslate(view.Stat2, EvaluateNumber(localFrame, s_Stat2RevealStatsRevealSecondaryPositionX, 0f), 0f);
        return true;
    }

    private static readonly NumberKeyframe[] s_AtkRevealAtkButtonOpacity =
    {
        new NumberKeyframe(0, 0f, EaseMode.Linear),
        new NumberKeyframe(12, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_AtkRevealAtkButtonPositionY =
    {
        new NumberKeyframe(0, 10f, EaseMode.Linear),
        new NumberKeyframe(12, 0f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_AtkRevealAtkIconRotation =
    {
        new NumberKeyframe(0, -18f, EaseMode.Linear),
        new NumberKeyframe(12, 0f, EaseMode.EaseOut),
    };

    private static bool ApplyAtkReveal(CharPortraitView view, int frame)
    {
        var localFrame = Mathf.Clamp(frame - 0, 0, 12);
        ApplyOpacity(view.Atk, EvaluateNumber(localFrame, s_AtkRevealAtkButtonOpacity, 1f));
        ApplyTranslate(view.Atk, 0f, EvaluateNumber(localFrame, s_AtkRevealAtkButtonPositionY, 0f));
        ApplyRotation(view.QEpO3, EvaluateNumber(localFrame, s_AtkRevealAtkIconRotation, 0f));
        return true;
    }

    private static readonly NumberKeyframe[] s_MagRevealMagButtonOpacity =
    {
        new NumberKeyframe(0, 0f, EaseMode.Linear),
        new NumberKeyframe(12, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_MagRevealMagButtonPositionY =
    {
        new NumberKeyframe(0, 10f, EaseMode.Linear),
        new NumberKeyframe(12, 0f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_MagRevealMagIconRotation =
    {
        new NumberKeyframe(0, -18f, EaseMode.Linear),
        new NumberKeyframe(12, 0f, EaseMode.EaseOut),
    };

    private static bool ApplyMagReveal(CharPortraitView view, int frame)
    {
        var localFrame = Mathf.Clamp(frame - 0, 0, 12);
        ApplyOpacity(view.Mag, EvaluateNumber(localFrame, s_MagRevealMagButtonOpacity, 1f));
        ApplyTranslate(view.Mag, 0f, EvaluateNumber(localFrame, s_MagRevealMagButtonPositionY, 0f));
        ApplyRotation(view.AIphN, EvaluateNumber(localFrame, s_MagRevealMagIconRotation, 0f));
        return true;
    }

    private static readonly NumberKeyframe[] s_DefRevealDefButtonOpacity =
    {
        new NumberKeyframe(0, 0f, EaseMode.Linear),
        new NumberKeyframe(12, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_DefRevealDefButtonPositionY =
    {
        new NumberKeyframe(0, 10f, EaseMode.Linear),
        new NumberKeyframe(12, 0f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_DefRevealDefIconRotation =
    {
        new NumberKeyframe(0, -18f, EaseMode.Linear),
        new NumberKeyframe(12, 0f, EaseMode.EaseOut),
    };

    private static bool ApplyDefReveal(CharPortraitView view, int frame)
    {
        var localFrame = Mathf.Clamp(frame - 0, 0, 12);
        ApplyOpacity(view.Def, EvaluateNumber(localFrame, s_DefRevealDefButtonOpacity, 1f));
        ApplyTranslate(view.Def, 0f, EvaluateNumber(localFrame, s_DefRevealDefButtonPositionY, 0f));
        ApplyRotation(view.E4QKZ, EvaluateNumber(localFrame, s_DefRevealDefIconRotation, 0f));
        return true;
    }

    private static readonly NumberKeyframe[] s_ItemRevealItemButtonOpacity =
    {
        new NumberKeyframe(0, 0f, EaseMode.Linear),
        new NumberKeyframe(12, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_ItemRevealItemButtonPositionY =
    {
        new NumberKeyframe(0, 10f, EaseMode.Linear),
        new NumberKeyframe(12, 0f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_ItemRevealItemIconRotation =
    {
        new NumberKeyframe(0, -18f, EaseMode.Linear),
        new NumberKeyframe(12, 0f, EaseMode.EaseOut),
    };

    private static bool ApplyItemReveal(CharPortraitView view, int frame)
    {
        var localFrame = Mathf.Clamp(frame - 0, 0, 12);
        ApplyOpacity(view.Item, EvaluateNumber(localFrame, s_ItemRevealItemButtonOpacity, 1f));
        ApplyTranslate(view.Item, 0f, EvaluateNumber(localFrame, s_ItemRevealItemButtonPositionY, 0f));
        ApplyRotation(view.DVzX7, EvaluateNumber(localFrame, s_ItemRevealItemIconRotation, 0f));
        return true;
    }

    private static float EvaluateNumber(int frame, NumberKeyframe[] keyframes, float defaultValue)
    {
        if (keyframes.Length == 0)
        {
            return defaultValue;
        }

        if (frame <= keyframes[0].Frame)
        {
            return keyframes[0].Value;
        }

        for (var index = 0; index < keyframes.Length - 1; index++)
        {
            var current = keyframes[index];
            var next = keyframes[index + 1];
            if (frame > next.Frame)
            {
                continue;
            }

            if (current.Easing == EaseMode.Step || Mathf.Approximately(current.Value, next.Value))
            {
                return current.Value;
            }

            var t = Mathf.InverseLerp(current.Frame, next.Frame, frame);
            return Mathf.LerpUnclamped(current.Value, next.Value, Ease(t, current.Easing));
        }

        return keyframes[keyframes.Length - 1].Value;
    }

    private static bool EvaluateBoolean(int frame, BooleanKeyframe[] keyframes, bool defaultValue)
    {
        if (keyframes.Length == 0)
        {
            return defaultValue;
        }

        var result = keyframes[0].Value;
        for (var index = 1; index < keyframes.Length; index++)
        {
            if (frame < keyframes[index].Frame)
            {
                break;
            }

            result = keyframes[index].Value;
        }

        return result;
    }

    private static string EvaluateString(int frame, StringKeyframe[] keyframes, string defaultValue)
    {
        if (keyframes.Length == 0)
        {
            return defaultValue;
        }

        var result = keyframes[0].Value;
        for (var index = 1; index < keyframes.Length; index++)
        {
            if (frame < keyframes[index].Frame)
            {
                break;
            }

            result = keyframes[index].Value;
        }

        return result;
    }

    private static float Ease(float t, EaseMode mode)
    {
        return mode switch
        {
            EaseMode.EaseIn => t * t * t,
            EaseMode.EaseOut => 1f - Mathf.Pow(1f - t, 3f),
            EaseMode.EaseInOut => t < 0.5f ? 4f * t * t * t : 1f - Mathf.Pow(-2f * t + 2f, 3f) / 2f,
            EaseMode.Step => 0f,
            _ => t
        };
    }

    private static void ApplyOpacity(VisualElement element, float value)
    {
        element.style.opacity = value;
    }

    private static void ApplyWidth(VisualElement element, float value)
    {
        element.style.width = value;
    }

    private static void ApplyHeight(VisualElement element, float value)
    {
        element.style.height = value;
    }

    private static void ApplyVisibility(VisualElement element, bool visible)
    {
        element.style.display = visible ? DisplayStyle.Flex : DisplayStyle.None;
    }

    private static void ApplyTranslate(VisualElement element, float x, float y)
    {
        element.style.translate = new StyleTranslate
        {
            value = new Translate
            {
                x = Length.Pixels(x),
                y = Length.Pixels(y),
                z = 0f
            }
        };
    }

    private static void ApplyScale(VisualElement element, float x, float y)
    {
        element.style.scale = new StyleScale
        {
            value = new Scale
            {
                value = new Vector3(x, y, 1f)
            }
        };
    }

    private static void ApplyRotation(VisualElement element, float degrees)
    {
        element.style.rotate = new StyleRotate
        {
            value = new Rotate
            {
                angle = Angle.Degrees(degrees)
            }
        };
    }

    private static void ApplyColor(VisualElement element, string value)
    {
        if (!ColorUtility.TryParseHtmlString(value, out var color))
        {
            return;
        }

        element.style.color = new StyleColor
        {
            value = color
        };
    }

    private static void ApplyText(VisualElement element, string value)
    {
        switch (element)
        {
            case Label label:
                label.text = value;
                break;
            case Button button:
                button.text = value;
                break;
            case TextField textField:
                textField.value = value;
                break;
            case ProgressBar progressBar:
                progressBar.title = value;
                break;
        }
    }

    private enum EaseMode
    {
        Linear,
        EaseIn,
        EaseOut,
        EaseInOut,
        Step
    }

    private readonly struct NumberKeyframe
    {
        public NumberKeyframe(int frame, float value, EaseMode easing)
        {
            Frame = frame;
            Value = value;
            Easing = easing;
        }

        public int Frame { get; }
        public float Value { get; }
        public EaseMode Easing { get; }
    }

    private readonly struct BooleanKeyframe
    {
        public BooleanKeyframe(int frame, bool value)
        {
            Frame = frame;
            Value = value;
        }

        public int Frame { get; }
        public bool Value { get; }
    }

    private readonly struct StringKeyframe
    {
        public StringKeyframe(int frame, string value)
        {
            Frame = frame;
            Value = value;
        }

        public int Frame { get; }
        public string Value { get; }
    }
}
}
