// <auto-generated>
// Generated by BoomHud.Gen.Unity from motion document CharPortraitMotion
// </auto-generated>

#nullable enable

using System;
using UnityEngine;
using UnityEngine.UIElements;

namespace Generated.Hud
{
public static class CharPortraitMotion
{
    public const int FramesPerSecond = 30;
    public const string DefaultClipId = "intro";
    public static readonly string[] ClipIds =
    {
        "intro",
    };

    public static bool TryApplyAtFrame(CharPortraitView view, string clipId, int frame)
    {
        if (view == null)
        {
            throw new ArgumentNullException(nameof(view));
        }

        return clipId switch
        {
            "intro" => ApplyIntro(view, frame),
            _ => false
        };
    }

    public static bool TryApplyAtTime(CharPortraitView view, string clipId, float timeSeconds)
    {
        return TryApplyAtFrame(view, clipId, Mathf.Max(0, Mathf.RoundToInt(timeSeconds * FramesPerSecond)));
    }

    public static int GetClipDurationFrames(string clipId)
    {
        return clipId switch
        {
            "intro" => 90,
            _ => 0
        };
    }

    public static float GetClipDurationSeconds(string clipId)
    {
        return GetClipDurationFrames(clipId) / (float)FramesPerSecond;
    }

    private static readonly NumberKeyframe[] s_IntroPortraitRootOpacity =
    {
        new NumberKeyframe(0, 0f, EaseMode.Linear),
        new NumberKeyframe(12, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroPortraitRootPositionY =
    {
        new NumberKeyframe(0, 24f, EaseMode.Linear),
        new NumberKeyframe(18, 0f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroFaceRevealOpacity =
    {
        new NumberKeyframe(0, 0f, EaseMode.Linear),
        new NumberKeyframe(12, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroFaceRevealScaleX =
    {
        new NumberKeyframe(0, 0.78f, EaseMode.Linear),
        new NumberKeyframe(16, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroFaceRevealScaleY =
    {
        new NumberKeyframe(0, 0.78f, EaseMode.Linear),
        new NumberKeyframe(16, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroClassIconSettleOpacity =
    {
        new NumberKeyframe(4, 0f, EaseMode.Linear),
        new NumberKeyframe(16, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroClassIconSettleRotation =
    {
        new NumberKeyframe(4, -14f, EaseMode.Linear),
        new NumberKeyframe(20, 0f, EaseMode.EaseInOut),
    };

    private static readonly StringKeyframe[] s_IntroNameBootText =
    {
        new StringKeyframe(0, "SCANNING"),
        new StringKeyframe(24, "AELRIC"),
    };

    private static readonly StringKeyframe[] s_IntroNameBootColor =
    {
        new StringKeyframe(0, "#d6c6a4"),
        new StringKeyframe(24, "#ffffff"),
    };

    private static readonly NumberKeyframe[] s_IntroNameBootPositionX =
    {
        new NumberKeyframe(0, -10f, EaseMode.Linear),
        new NumberKeyframe(20, 0f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroHpFillIntroWidth =
    {
        new NumberKeyframe(6, 0f, EaseMode.Linear),
        new NumberKeyframe(28, 90f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroMpFillIntroWidth =
    {
        new NumberKeyframe(12, 0f, EaseMode.Linear),
        new NumberKeyframe(34, 60f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroStatsRevealOpacity =
    {
        new NumberKeyframe(14, 0f, EaseMode.Linear),
        new NumberKeyframe(30, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroStatsRevealPositionX =
    {
        new NumberKeyframe(14, -8f, EaseMode.Linear),
        new NumberKeyframe(30, 0f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroStatsRevealSecondaryOpacity =
    {
        new NumberKeyframe(18, 0f, EaseMode.Linear),
        new NumberKeyframe(34, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroStatsRevealSecondaryPositionX =
    {
        new NumberKeyframe(18, 8f, EaseMode.Linear),
        new NumberKeyframe(34, 0f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroActionsRevealOpacity =
    {
        new NumberKeyframe(20, 0f, EaseMode.Linear),
        new NumberKeyframe(36, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroActionsRevealPositionY =
    {
        new NumberKeyframe(20, 10f, EaseMode.Linear),
        new NumberKeyframe(36, 0f, EaseMode.EaseOut),
    };

    private static bool ApplyIntro(CharPortraitView view, int frame)
    {
        var localFrame = Mathf.Clamp(frame - 0, 0, 90);
        ApplyOpacity(view.Root, EvaluateNumber(localFrame, s_IntroPortraitRootOpacity, 1f));
        ApplyTranslate(view.Root, 0f, EvaluateNumber(localFrame, s_IntroPortraitRootPositionY, 0f));
        ApplyOpacity(view.Face, EvaluateNumber(localFrame, s_IntroFaceRevealOpacity, 1f));
        ApplyScale(view.Face, EvaluateNumber(localFrame, s_IntroFaceRevealScaleX, 1f), EvaluateNumber(localFrame, s_IntroFaceRevealScaleY, 1f));
        ApplyOpacity(view.ClassIcon, EvaluateNumber(localFrame, s_IntroClassIconSettleOpacity, 1f));
        ApplyRotation(view.ClassIcon, EvaluateNumber(localFrame, s_IntroClassIconSettleRotation, 0f));
        ApplyText(view.Name, EvaluateString(localFrame, s_IntroNameBootText, string.Empty));
        ApplyColor(view.Name, EvaluateString(localFrame, s_IntroNameBootColor, string.Empty));
        ApplyTranslate(view.Name, EvaluateNumber(localFrame, s_IntroNameBootPositionX, 0f), 0f);
        ApplyWidth(view.HpFill, EvaluateNumber(localFrame, s_IntroHpFillIntroWidth, 0f));
        ApplyWidth(view.MpFill, EvaluateNumber(localFrame, s_IntroMpFillIntroWidth, 0f));
        ApplyOpacity(view.Stat1, EvaluateNumber(localFrame, s_IntroStatsRevealOpacity, 1f));
        ApplyTranslate(view.Stat1, EvaluateNumber(localFrame, s_IntroStatsRevealPositionX, 0f), 0f);
        ApplyOpacity(view.Stat2, EvaluateNumber(localFrame, s_IntroStatsRevealSecondaryOpacity, 1f));
        ApplyTranslate(view.Stat2, EvaluateNumber(localFrame, s_IntroStatsRevealSecondaryPositionX, 0f), 0f);
        ApplyOpacity(view.ActionGrid, EvaluateNumber(localFrame, s_IntroActionsRevealOpacity, 1f));
        ApplyTranslate(view.ActionGrid, 0f, EvaluateNumber(localFrame, s_IntroActionsRevealPositionY, 0f));
        return true;
    }

    private static float EvaluateNumber(int frame, NumberKeyframe[] keyframes, float defaultValue)
    {
        if (keyframes.Length == 0)
        {
            return defaultValue;
        }

        if (frame <= keyframes[0].Frame)
        {
            return keyframes[0].Value;
        }

        for (var index = 0; index < keyframes.Length - 1; index++)
        {
            var current = keyframes[index];
            var next = keyframes[index + 1];
            if (frame > next.Frame)
            {
                continue;
            }

            if (current.Easing == EaseMode.Step || Mathf.Approximately(current.Value, next.Value))
            {
                return current.Value;
            }

            var t = Mathf.InverseLerp(current.Frame, next.Frame, frame);
            return Mathf.LerpUnclamped(current.Value, next.Value, Ease(t, current.Easing));
        }

        return keyframes[keyframes.Length - 1].Value;
    }

    private static bool EvaluateBoolean(int frame, BooleanKeyframe[] keyframes, bool defaultValue)
    {
        if (keyframes.Length == 0)
        {
            return defaultValue;
        }

        var result = keyframes[0].Value;
        for (var index = 1; index < keyframes.Length; index++)
        {
            if (frame < keyframes[index].Frame)
            {
                break;
            }

            result = keyframes[index].Value;
        }

        return result;
    }

    private static string EvaluateString(int frame, StringKeyframe[] keyframes, string defaultValue)
    {
        if (keyframes.Length == 0)
        {
            return defaultValue;
        }

        var result = keyframes[0].Value;
        for (var index = 1; index < keyframes.Length; index++)
        {
            if (frame < keyframes[index].Frame)
            {
                break;
            }

            result = keyframes[index].Value;
        }

        return result;
    }

    private static float Ease(float t, EaseMode mode)
    {
        return mode switch
        {
            EaseMode.EaseIn => t * t * t,
            EaseMode.EaseOut => 1f - Mathf.Pow(1f - t, 3f),
            EaseMode.EaseInOut => t < 0.5f ? 4f * t * t * t : 1f - Mathf.Pow(-2f * t + 2f, 3f) / 2f,
            EaseMode.Step => 0f,
            _ => t
        };
    }

    private static void ApplyOpacity(VisualElement element, float value)
    {
        element.style.opacity = value;
    }

    private static void ApplyWidth(VisualElement element, float value)
    {
        element.style.width = value;
    }

    private static void ApplyHeight(VisualElement element, float value)
    {
        element.style.height = value;
    }

    private static void ApplyVisibility(VisualElement element, bool visible)
    {
        element.style.display = visible ? DisplayStyle.Flex : DisplayStyle.None;
    }

    private static void ApplyTranslate(VisualElement element, float x, float y)
    {
        element.style.translate = new StyleTranslate
        {
            value = new Translate
            {
                x = Length.Pixels(x),
                y = Length.Pixels(y),
                z = 0f
            }
        };
    }

    private static void ApplyScale(VisualElement element, float x, float y)
    {
        element.style.scale = new StyleScale
        {
            value = new Scale
            {
                value = new Vector3(x, y, 1f)
            }
        };
    }

    private static void ApplyRotation(VisualElement element, float degrees)
    {
        element.style.rotate = new StyleRotate
        {
            value = new Rotate
            {
                angle = Angle.Degrees(degrees)
            }
        };
    }

    private static void ApplyColor(VisualElement element, string value)
    {
        if (!ColorUtility.TryParseHtmlString(value, out var color))
        {
            return;
        }

        element.style.color = new StyleColor
        {
            value = color
        };
    }

    private static void ApplyText(VisualElement element, string value)
    {
        switch (element)
        {
            case Label label:
                label.text = value;
                break;
            case Button button:
                button.text = value;
                break;
            case TextField textField:
                textField.value = value;
                break;
            case ProgressBar progressBar:
                progressBar.title = value;
                break;
        }
    }

    private enum EaseMode
    {
        Linear,
        EaseIn,
        EaseOut,
        EaseInOut,
        Step
    }

    private readonly struct NumberKeyframe
    {
        public NumberKeyframe(int frame, float value, EaseMode easing)
        {
            Frame = frame;
            Value = value;
            Easing = easing;
        }

        public int Frame { get; }
        public float Value { get; }
        public EaseMode Easing { get; }
    }

    private readonly struct BooleanKeyframe
    {
        public BooleanKeyframe(int frame, bool value)
        {
            Frame = frame;
            Value = value;
        }

        public int Frame { get; }
        public bool Value { get; }
    }

    private readonly struct StringKeyframe
    {
        public StringKeyframe(int frame, string value)
        {
            Frame = frame;
            Value = value;
        }

        public int Frame { get; }
        public string Value { get; }
    }
}
}
