// <auto-generated>
// Generated by BoomHud.Gen.Unity from motion document DebugOverlayMotion
// </auto-generated>

#nullable enable

using System;
using UnityEngine;
using UnityEngine.UIElements;

namespace Generated.Hud
{
public static class DebugOverlayMotion
{
    public const int FramesPerSecond = 30;
    public const string DefaultClipId = "intro";
    public static readonly string[] ClipIds =
    {
        "intro",
    };

    public static bool TryApplyAtFrame(DebugOverlayView view, string clipId, int frame)
    {
        if (view == null)
        {
            throw new ArgumentNullException(nameof(view));
        }

        return clipId switch
        {
            "intro" => ApplyIntro(view, frame),
            _ => false
        };
    }

    public static bool TryApplyAtTime(DebugOverlayView view, string clipId, float timeSeconds)
    {
        return TryApplyAtFrame(view, clipId, Mathf.Max(0, Mathf.RoundToInt(timeSeconds * FramesPerSecond)));
    }

    public static int GetClipDurationFrames(string clipId)
    {
        return clipId switch
        {
            "intro" => 90,
            _ => 0
        };
    }

    public static float GetClipDurationSeconds(string clipId)
    {
        return GetClipDurationFrames(clipId) / (float)FramesPerSecond;
    }

    private static readonly NumberKeyframe[] s_IntroRootFadeOpacity =
    {
        new NumberKeyframe(0, 0f, EaseMode.Linear),
        new NumberKeyframe(12, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroRootFadePositionY =
    {
        new NumberKeyframe(0, 18f, EaseMode.Linear),
        new NumberKeyframe(16, 0f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroHeaderEntrancePositionX =
    {
        new NumberKeyframe(0, -24f, EaseMode.Linear),
        new NumberKeyframe(18, 0f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroHeaderEntranceOpacity =
    {
        new NumberKeyframe(0, 0.15f, EaseMode.Linear),
        new NumberKeyframe(18, 1f, EaseMode.EaseOut),
    };

    private static readonly StringKeyframe[] s_IntroVersionBootTextText =
    {
        new StringKeyframe(0, "BOOT"),
        new StringKeyframe(24, "READY"),
        new StringKeyframe(42, "v1.2.0"),
    };

    private static readonly StringKeyframe[] s_IntroVersionBootTextColor =
    {
        new StringKeyframe(0, "#7dd3fc"),
        new StringKeyframe(42, "#f8fafc"),
    };

    private static readonly NumberKeyframe[] s_IntroSeparatorGlowOpacity =
    {
        new NumberKeyframe(0, 0f, EaseMode.Linear),
        new NumberKeyframe(20, 0.3f, EaseMode.EaseOut),
        new NumberKeyframe(46, 0.6f, EaseMode.EaseInOut),
        new NumberKeyframe(72, 0.3f, EaseMode.EaseInOut),
    };

    private static readonly NumberKeyframe[] s_IntroFpsPulsePositionY =
    {
        new NumberKeyframe(8, -8f, EaseMode.Linear),
        new NumberKeyframe(24, 0f, EaseMode.EaseOut),
    };

    private static readonly StringKeyframe[] s_IntroFpsPulseColor =
    {
        new StringKeyframe(0, "#f8fafc"),
        new StringKeyframe(18, "#86efac"),
        new StringKeyframe(36, "#f8fafc"),
    };

    private static readonly NumberKeyframe[] s_IntroMemorySlidePositionX =
    {
        new NumberKeyframe(10, -18f, EaseMode.Linear),
        new NumberKeyframe(26, 0f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroMemorySlideOpacity =
    {
        new NumberKeyframe(10, 0f, EaseMode.Linear),
        new NumberKeyframe(26, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroPositionSlidePositionX =
    {
        new NumberKeyframe(16, -18f, EaseMode.Linear),
        new NumberKeyframe(32, 0f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroPositionSlideOpacity =
    {
        new NumberKeyframe(16, 0f, EaseMode.Linear),
        new NumberKeyframe(32, 1f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroChunkRevealPositionX =
    {
        new NumberKeyframe(22, -18f, EaseMode.Linear),
        new NumberKeyframe(40, 0f, EaseMode.EaseOut),
    };

    private static readonly NumberKeyframe[] s_IntroChunkRevealOpacity =
    {
        new NumberKeyframe(22, 0f, EaseMode.Linear),
        new NumberKeyframe(40, 1f, EaseMode.EaseOut),
    };

    private static readonly StringKeyframe[] s_IntroChunkTextText =
    {
        new StringKeyframe(0, "--"),
        new StringKeyframe(45, "14,08"),
        new StringKeyframe(72, "14,09"),
    };

    private static bool ApplyIntro(DebugOverlayView view, int frame)
    {
        var localFrame = Mathf.Clamp(frame - 0, 0, 90);
        ApplyOpacity(view.Root, EvaluateNumber(localFrame, s_IntroRootFadeOpacity, 1f));
        ApplyTranslate(view.Root, 0f, EvaluateNumber(localFrame, s_IntroRootFadePositionY, 0f));
        ApplyOpacity(view.Header, EvaluateNumber(localFrame, s_IntroHeaderEntranceOpacity, 1f));
        ApplyTranslate(view.Header, EvaluateNumber(localFrame, s_IntroHeaderEntrancePositionX, 0f), 0f);
        ApplyText(view.Version, EvaluateString(localFrame, s_IntroVersionBootTextText, string.Empty));
        ApplyColor(view.Version, EvaluateString(localFrame, s_IntroVersionBootTextColor, string.Empty));
        ApplyOpacity(view.Separator, EvaluateNumber(localFrame, s_IntroSeparatorGlowOpacity, 1f));
        ApplyColor(view.FpsValue, EvaluateString(localFrame, s_IntroFpsPulseColor, string.Empty));
        ApplyTranslate(view.FpsValue, 0f, EvaluateNumber(localFrame, s_IntroFpsPulsePositionY, 0f));
        ApplyOpacity(view.MemoryRow, EvaluateNumber(localFrame, s_IntroMemorySlideOpacity, 1f));
        ApplyTranslate(view.MemoryRow, EvaluateNumber(localFrame, s_IntroMemorySlidePositionX, 0f), 0f);
        ApplyOpacity(view.PositionRow, EvaluateNumber(localFrame, s_IntroPositionSlideOpacity, 1f));
        ApplyTranslate(view.PositionRow, EvaluateNumber(localFrame, s_IntroPositionSlidePositionX, 0f), 0f);
        ApplyOpacity(view.ChunkRow, EvaluateNumber(localFrame, s_IntroChunkRevealOpacity, 1f));
        ApplyTranslate(view.ChunkRow, EvaluateNumber(localFrame, s_IntroChunkRevealPositionX, 0f), 0f);
        ApplyText(view.ChunkValue, EvaluateString(localFrame, s_IntroChunkTextText, string.Empty));
        return true;
    }

    private static float EvaluateNumber(int frame, NumberKeyframe[] keyframes, float defaultValue)
    {
        if (keyframes.Length == 0)
        {
            return defaultValue;
        }

        if (frame <= keyframes[0].Frame)
        {
            return keyframes[0].Value;
        }

        for (var index = 0; index < keyframes.Length - 1; index++)
        {
            var current = keyframes[index];
            var next = keyframes[index + 1];
            if (frame > next.Frame)
            {
                continue;
            }

            if (current.Easing == EaseMode.Step || Mathf.Approximately(current.Value, next.Value))
            {
                return current.Value;
            }

            var t = Mathf.InverseLerp(current.Frame, next.Frame, frame);
            return Mathf.LerpUnclamped(current.Value, next.Value, Ease(t, current.Easing));
        }

        return keyframes[keyframes.Length - 1].Value;
    }

    private static bool EvaluateBoolean(int frame, BooleanKeyframe[] keyframes, bool defaultValue)
    {
        if (keyframes.Length == 0)
        {
            return defaultValue;
        }

        var result = keyframes[0].Value;
        for (var index = 1; index < keyframes.Length; index++)
        {
            if (frame < keyframes[index].Frame)
            {
                break;
            }

            result = keyframes[index].Value;
        }

        return result;
    }

    private static string EvaluateString(int frame, StringKeyframe[] keyframes, string defaultValue)
    {
        if (keyframes.Length == 0)
        {
            return defaultValue;
        }

        var result = keyframes[0].Value;
        for (var index = 1; index < keyframes.Length; index++)
        {
            if (frame < keyframes[index].Frame)
            {
                break;
            }

            result = keyframes[index].Value;
        }

        return result;
    }

    private static float Ease(float t, EaseMode mode)
    {
        return mode switch
        {
            EaseMode.EaseIn => t * t * t,
            EaseMode.EaseOut => 1f - Mathf.Pow(1f - t, 3f),
            EaseMode.EaseInOut => t < 0.5f ? 4f * t * t * t : 1f - Mathf.Pow(-2f * t + 2f, 3f) / 2f,
            EaseMode.Step => 0f,
            _ => t
        };
    }

    private static void ApplyOpacity(VisualElement element, float value)
    {
        element.style.opacity = value;
    }

    private static void ApplyWidth(VisualElement element, float value)
    {
        element.style.width = value;
    }

    private static void ApplyHeight(VisualElement element, float value)
    {
        element.style.height = value;
    }

    private static void ApplyVisibility(VisualElement element, bool visible)
    {
        element.style.display = visible ? DisplayStyle.Flex : DisplayStyle.None;
    }

    private static void ApplyTranslate(VisualElement element, float x, float y)
    {
        element.style.translate = new StyleTranslate
        {
            value = new Translate
            {
                x = Length.Pixels(x),
                y = Length.Pixels(y),
                z = 0f
            }
        };
    }

    private static void ApplyScale(VisualElement element, float x, float y)
    {
        element.style.scale = new StyleScale
        {
            value = new Scale
            {
                value = new Vector3(x, y, 1f)
            }
        };
    }

    private static void ApplyRotation(VisualElement element, float degrees)
    {
        element.style.rotate = new StyleRotate
        {
            value = new Rotate
            {
                angle = Angle.Degrees(degrees)
            }
        };
    }

    private static void ApplyColor(VisualElement element, string value)
    {
        if (!ColorUtility.TryParseHtmlString(value, out var color))
        {
            return;
        }

        element.style.color = new StyleColor
        {
            value = color
        };
    }

    private static void ApplyText(VisualElement element, string value)
    {
        switch (element)
        {
            case Label label:
                label.text = value;
                break;
            case Button button:
                button.text = value;
                break;
            case TextField textField:
                textField.value = value;
                break;
            case ProgressBar progressBar:
                progressBar.title = value;
                break;
        }
    }

    private enum EaseMode
    {
        Linear,
        EaseIn,
        EaseOut,
        EaseInOut,
        Step
    }

    private readonly struct NumberKeyframe
    {
        public NumberKeyframe(int frame, float value, EaseMode easing)
        {
            Frame = frame;
            Value = value;
            Easing = easing;
        }

        public int Frame { get; }
        public float Value { get; }
        public EaseMode Easing { get; }
    }

    private readonly struct BooleanKeyframe
    {
        public BooleanKeyframe(int frame, bool value)
        {
            Frame = frame;
            Value = value;
        }

        public int Frame { get; }
        public bool Value { get; }
    }

    private readonly struct StringKeyframe
    {
        public StringKeyframe(int frame, string value)
        {
            Frame = frame;
            Value = value;
        }

        public int Frame { get; }
        public string Value { get; }
    }
}
}
