// <auto-generated>
// Generated by BoomHud.Gen.Unity from CharPortrait
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud
{
public interface ICharPortraitViewModel : INotifyPropertyChanged
{
}
}
