// <auto-generated>
// Generated by BoomHud.Gen.Unity from DebugOverlay
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud
{
public interface IDebugOverlayViewModel : INotifyPropertyChanged
{
    object? CurrentChunk { get; }
    object? Fps { get; }
    object? MemoryUsage { get; }
    object? PlayerPosition { get; }
    object? Version { get; }
}
}
