// <auto-generated>
// Generated by BoomHud.Gen.Unity from Minimap
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud
{
public interface IMinimapViewModel : INotifyPropertyChanged
{
}
}
