// <auto-generated>
// Generated by BoomHud.Gen.Unity from RuinerSkillMenu
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud
{
public interface IRuinerSkillMenuViewModel : INotifyPropertyChanged
{
}
}
