// <auto-generated>
// Generated by BoomHud.Gen.Unity from StatBar
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud
{
public interface IStatBarViewModel : INotifyPropertyChanged
{
}
}
