// <auto-generated>
// Generated by BoomHud.Gen.Unity from SyntheticContainer25885ADD
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud
{
public interface ISyntheticContainer25885ADDViewModel : INotifyPropertyChanged
{
}
}
