// <auto-generated>
// Generated by BoomHud.Gen.Unity from SyntheticContainer62FD2935
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud
{
public interface ISyntheticContainer62FD2935ViewModel : INotifyPropertyChanged
{
}
}
