// <auto-generated>
// Generated by BoomHud.Gen.Unity from SyntheticContainerB978BB0B
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud
{
public interface ISyntheticContainerB978BB0BViewModel : INotifyPropertyChanged
{
}
}
