// <auto-generated>
// Generated by BoomHud.Gen.Unity from SyntheticContainerA04D0699
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud
{
public interface ISyntheticContainerA04D0699ViewModel : INotifyPropertyChanged
{
}
}
