// <auto-generated>
// Generated by BoomHud.Gen.Unity from SyntheticContainerF65D929F
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud
{
public interface ISyntheticContainerF65D929FViewModel : INotifyPropertyChanged
{
}
}
