// <auto-generated>
// Generated by BoomHud.Gen.Unity from SyntheticContainerC35E1B73
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud
{
public interface ISyntheticContainerC35E1B73ViewModel : INotifyPropertyChanged
{
}
}
