// <auto-generated>
// Generated by BoomHud.Gen.Unity from PartyStatusStrip
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Linq;
using UnityEngine;
using UnityEngine.TextCore.Text;
using UnityEngine.UIElements;

namespace Generated.Hud
{
public sealed class PartyStatusStripView
{
    private readonly IPartyStatusStripViewModel? _initialViewModel = null;
    private readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, object?>>? _componentOverrides;
    private IPartyStatusStripViewModel? _viewModel;

    public VisualElement Root { get; }
    public VisualElement Header { get; }
    public Label AreaName { get; }
    public Label EncounterState { get; }
    public VisualElement MemberRow { get; }
    public VisualElement MemberA { get; }
    public VisualElement HeroRow { get; }
    public VisualElement HpBar { get; }
    public VisualElement HpFill { get; }
    public Label HpText { get; }
    public VisualElement MpBar { get; }
    public VisualElement MpFill { get; }
    public Label MpText { get; }
    public VisualElement StatusRow { get; }
    public VisualElement StatusBuff1 { get; }
    public VisualElement StatusBuff2 { get; }
    public VisualElement StatusBuff3 { get; }
    public VisualElement StatusBuff4 { get; }
    public VisualElement MemberB { get; }
    public VisualElement HeroRow2 { get; }
    public VisualElement HpBar2 { get; }
    public VisualElement HpFill2 { get; }
    public Label HpText2 { get; }
    public VisualElement MpBar2 { get; }
    public VisualElement MpFill2 { get; }
    public Label MpText2 { get; }
    public VisualElement StatusRow2 { get; }
    public VisualElement StatusBuff12 { get; }
    public VisualElement StatusBuff22 { get; }
    public VisualElement StatusBuff32 { get; }
    public VisualElement StatusBuff42 { get; }
    public VisualElement MemberC { get; }
    public VisualElement HeroRow3 { get; }
    public VisualElement HpBar3 { get; }
    public VisualElement HpFill3 { get; }
    public Label HpText3 { get; }
    public VisualElement MpBar3 { get; }
    public VisualElement MpFill3 { get; }
    public Label MpText3 { get; }
    public VisualElement StatusRow3 { get; }
    public VisualElement StatusBuff13 { get; }
    public VisualElement StatusBuff23 { get; }
    public VisualElement StatusBuff33 { get; }
    public VisualElement StatusBuff43 { get; }
    private readonly SyntheticContainerAF9ECAF6View? _heroRowComponent;
    private readonly SyntheticContainerB978BB0BView? _statusBuff1Component;
    private readonly SyntheticContainerB978BB0BView? _statusBuff2Component;
    private readonly SyntheticContainerB978BB0BView? _statusBuff3Component;
    private readonly SyntheticContainerB978BB0BView? _statusBuff4Component;
    private readonly SyntheticContainerAF9ECAF6View? _heroRow2Component;
    private readonly SyntheticContainerB978BB0BView? _statusBuff12Component;
    private readonly SyntheticContainerB978BB0BView? _statusBuff22Component;
    private readonly SyntheticContainerB978BB0BView? _statusBuff32Component;
    private readonly SyntheticContainerB978BB0BView? _statusBuff42Component;
    private readonly SyntheticContainerAF9ECAF6View? _heroRow3Component;
    private readonly SyntheticContainerB978BB0BView? _statusBuff13Component;
    private readonly SyntheticContainerB978BB0BView? _statusBuff23Component;
    private readonly SyntheticContainerB978BB0BView? _statusBuff33Component;
    private readonly SyntheticContainerB978BB0BView? _statusBuff43Component;

    public IPartyStatusStripViewModel? ViewModel
    {
        get => _viewModel;
        set
        {
            if (_viewModel != null)
            {
                _viewModel.PropertyChanged -= OnViewModelPropertyChanged;
            }

            _viewModel = value;
            ApplyComponentViewModels();

            if (_viewModel != null)
            {
                _viewModel.PropertyChanged += OnViewModelPropertyChanged;
            }

            Refresh();
        }
    }

    public PartyStatusStripView(VisualElement root, IReadOnlyDictionary<string, IReadOnlyDictionary<string, object?>>? componentOverrides = null)
    {
        Root = root as VisualElement ?? throw new ArgumentException("Expected root element type VisualElement.", nameof(root));
        _componentOverrides = componentOverrides;
        Header = Root.Q<VisualElement>("Header") ?? throw new InvalidOperationException("Could not find generated element 'Header'.");
        AreaName = Root.Q<Label>("AreaName") ?? throw new InvalidOperationException("Could not find generated element 'AreaName'.");
        EncounterState = Root.Q<Label>("EncounterState") ?? throw new InvalidOperationException("Could not find generated element 'EncounterState'.");
        MemberRow = Root.Q<VisualElement>("MemberRow") ?? throw new InvalidOperationException("Could not find generated element 'MemberRow'.");
        MemberA = Root.Q<VisualElement>("MemberA") ?? throw new InvalidOperationException("Could not find generated element 'MemberA'.");
        var heroRowPlaceholder = Root.Q<VisualElement>("HeroRow") ?? throw new InvalidOperationException("Could not find generated component placeholder 'HeroRow'.");
        _heroRowComponent = SyntheticContainerAF9ECAF6View.Attach(heroRowPlaceholder, null);
        HeroRow = _heroRowComponent.Root;
        HpBar = Root.Q<VisualElement>("HpBar") ?? throw new InvalidOperationException("Could not find generated element 'HpBar'.");
        HpFill = Root.Q<VisualElement>("HpFill") ?? throw new InvalidOperationException("Could not find generated element 'HpFill'.");
        HpText = Root.Q<Label>("HpText") ?? throw new InvalidOperationException("Could not find generated element 'HpText'.");
        MpBar = Root.Q<VisualElement>("MpBar") ?? throw new InvalidOperationException("Could not find generated element 'MpBar'.");
        MpFill = Root.Q<VisualElement>("MpFill") ?? throw new InvalidOperationException("Could not find generated element 'MpFill'.");
        MpText = Root.Q<Label>("MpText") ?? throw new InvalidOperationException("Could not find generated element 'MpText'.");
        StatusRow = Root.Q<VisualElement>("StatusRow") ?? throw new InvalidOperationException("Could not find generated element 'StatusRow'.");
        var statusBuff1Placeholder = Root.Q<VisualElement>("StatusBuff1") ?? throw new InvalidOperationException("Could not find generated component placeholder 'StatusBuff1'.");
        _statusBuff1Component = SyntheticContainerB978BB0BView.Attach(statusBuff1Placeholder, null);
        StatusBuff1 = _statusBuff1Component.Root;
        var statusBuff2Placeholder = Root.Q<VisualElement>("StatusBuff2") ?? throw new InvalidOperationException("Could not find generated component placeholder 'StatusBuff2'.");
        _statusBuff2Component = SyntheticContainerB978BB0BView.Attach(statusBuff2Placeholder, new Dictionary<string, IReadOnlyDictionary<string, object?>>(StringComparer.Ordinal)
        {
            ["$/0"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "flame"
            }
        });
        StatusBuff2 = _statusBuff2Component.Root;
        var statusBuff3Placeholder = Root.Q<VisualElement>("StatusBuff3") ?? throw new InvalidOperationException("Could not find generated component placeholder 'StatusBuff3'.");
        _statusBuff3Component = SyntheticContainerB978BB0BView.Attach(statusBuff3Placeholder, new Dictionary<string, IReadOnlyDictionary<string, object?>>(StringComparer.Ordinal)
        {
            ["$/0"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "cross"
            }
        });
        StatusBuff3 = _statusBuff3Component.Root;
        var statusBuff4Placeholder = Root.Q<VisualElement>("StatusBuff4") ?? throw new InvalidOperationException("Could not find generated component placeholder 'StatusBuff4'.");
        _statusBuff4Component = SyntheticContainerB978BB0BView.Attach(statusBuff4Placeholder, new Dictionary<string, IReadOnlyDictionary<string, object?>>(StringComparer.Ordinal)
        {
            ["$/0"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "moon"
            }
        });
        StatusBuff4 = _statusBuff4Component.Root;
        MemberB = Root.Q<VisualElement>("MemberB") ?? throw new InvalidOperationException("Could not find generated element 'MemberB'.");
        var heroRow2Placeholder = Root.Q<VisualElement>("HeroRow2") ?? throw new InvalidOperationException("Could not find generated component placeholder 'HeroRow2'.");
        _heroRow2Component = SyntheticContainerAF9ECAF6View.Attach(heroRow2Placeholder, new Dictionary<string, IReadOnlyDictionary<string, object?>>(StringComparer.Ordinal)
        {
            ["$/0/0"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "sparkles"
            },
            ["$/1/0"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "Lyra"
            },
            ["$/1/1"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "Arcane Control"
            }
        });
        HeroRow2 = _heroRow2Component.Root;
        HpBar2 = Root.Q<VisualElement>("HpBar2") ?? throw new InvalidOperationException("Could not find generated element 'HpBar2'.");
        HpFill2 = Root.Q<VisualElement>("HpFill2") ?? throw new InvalidOperationException("Could not find generated element 'HpFill2'.");
        HpText2 = Root.Q<Label>("HpText2") ?? throw new InvalidOperationException("Could not find generated element 'HpText2'.");
        MpBar2 = Root.Q<VisualElement>("MpBar2") ?? throw new InvalidOperationException("Could not find generated element 'MpBar2'.");
        MpFill2 = Root.Q<VisualElement>("MpFill2") ?? throw new InvalidOperationException("Could not find generated element 'MpFill2'.");
        MpText2 = Root.Q<Label>("MpText2") ?? throw new InvalidOperationException("Could not find generated element 'MpText2'.");
        StatusRow2 = Root.Q<VisualElement>("StatusRow2") ?? throw new InvalidOperationException("Could not find generated element 'StatusRow2'.");
        var statusBuff12Placeholder = Root.Q<VisualElement>("StatusBuff12") ?? throw new InvalidOperationException("Could not find generated component placeholder 'StatusBuff12'.");
        _statusBuff12Component = SyntheticContainerB978BB0BView.Attach(statusBuff12Placeholder, new Dictionary<string, IReadOnlyDictionary<string, object?>>(StringComparer.Ordinal)
        {
            ["$/0"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "wand-sparkles"
            }
        });
        StatusBuff12 = _statusBuff12Component.Root;
        var statusBuff22Placeholder = Root.Q<VisualElement>("StatusBuff22") ?? throw new InvalidOperationException("Could not find generated component placeholder 'StatusBuff22'.");
        _statusBuff22Component = SyntheticContainerB978BB0BView.Attach(statusBuff22Placeholder, new Dictionary<string, IReadOnlyDictionary<string, object?>>(StringComparer.Ordinal)
        {
            ["$/0"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "flask-conical"
            }
        });
        StatusBuff22 = _statusBuff22Component.Root;
        var statusBuff32Placeholder = Root.Q<VisualElement>("StatusBuff32") ?? throw new InvalidOperationException("Could not find generated component placeholder 'StatusBuff32'.");
        _statusBuff32Component = SyntheticContainerB978BB0BView.Attach(statusBuff32Placeholder, new Dictionary<string, IReadOnlyDictionary<string, object?>>(StringComparer.Ordinal)
        {
            ["$/0"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "moon"
            }
        });
        StatusBuff32 = _statusBuff32Component.Root;
        var statusBuff42Placeholder = Root.Q<VisualElement>("StatusBuff42") ?? throw new InvalidOperationException("Could not find generated component placeholder 'StatusBuff42'.");
        _statusBuff42Component = SyntheticContainerB978BB0BView.Attach(statusBuff42Placeholder, null);
        StatusBuff42 = _statusBuff42Component.Root;
        MemberC = Root.Q<VisualElement>("MemberC") ?? throw new InvalidOperationException("Could not find generated element 'MemberC'.");
        var heroRow3Placeholder = Root.Q<VisualElement>("HeroRow3") ?? throw new InvalidOperationException("Could not find generated component placeholder 'HeroRow3'.");
        _heroRow3Component = SyntheticContainerAF9ECAF6View.Attach(heroRow3Placeholder, new Dictionary<string, IReadOnlyDictionary<string, object?>>(StringComparer.Ordinal)
        {
            ["$/0/0"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "shield"
            },
            ["$/1/0"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "Serin"
            },
            ["$/1/1"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "Guardian Support"
            }
        });
        HeroRow3 = _heroRow3Component.Root;
        HpBar3 = Root.Q<VisualElement>("HpBar3") ?? throw new InvalidOperationException("Could not find generated element 'HpBar3'.");
        HpFill3 = Root.Q<VisualElement>("HpFill3") ?? throw new InvalidOperationException("Could not find generated element 'HpFill3'.");
        HpText3 = Root.Q<Label>("HpText3") ?? throw new InvalidOperationException("Could not find generated element 'HpText3'.");
        MpBar3 = Root.Q<VisualElement>("MpBar3") ?? throw new InvalidOperationException("Could not find generated element 'MpBar3'.");
        MpFill3 = Root.Q<VisualElement>("MpFill3") ?? throw new InvalidOperationException("Could not find generated element 'MpFill3'.");
        MpText3 = Root.Q<Label>("MpText3") ?? throw new InvalidOperationException("Could not find generated element 'MpText3'.");
        StatusRow3 = Root.Q<VisualElement>("StatusRow3") ?? throw new InvalidOperationException("Could not find generated element 'StatusRow3'.");
        var statusBuff13Placeholder = Root.Q<VisualElement>("StatusBuff13") ?? throw new InvalidOperationException("Could not find generated component placeholder 'StatusBuff13'.");
        _statusBuff13Component = SyntheticContainerB978BB0BView.Attach(statusBuff13Placeholder, new Dictionary<string, IReadOnlyDictionary<string, object?>>(StringComparer.Ordinal)
        {
            ["$/0"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "cross"
            }
        });
        StatusBuff13 = _statusBuff13Component.Root;
        var statusBuff23Placeholder = Root.Q<VisualElement>("StatusBuff23") ?? throw new InvalidOperationException("Could not find generated component placeholder 'StatusBuff23'.");
        _statusBuff23Component = SyntheticContainerB978BB0BView.Attach(statusBuff23Placeholder, null);
        StatusBuff23 = _statusBuff23Component.Root;
        var statusBuff33Placeholder = Root.Q<VisualElement>("StatusBuff33") ?? throw new InvalidOperationException("Could not find generated component placeholder 'StatusBuff33'.");
        _statusBuff33Component = SyntheticContainerB978BB0BView.Attach(statusBuff33Placeholder, new Dictionary<string, IReadOnlyDictionary<string, object?>>(StringComparer.Ordinal)
        {
            ["$/0"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "moon"
            }
        });
        StatusBuff33 = _statusBuff33Component.Root;
        var statusBuff43Placeholder = Root.Q<VisualElement>("StatusBuff43") ?? throw new InvalidOperationException("Could not find generated component placeholder 'StatusBuff43'.");
        _statusBuff43Component = SyntheticContainerB978BB0BView.Attach(statusBuff43Placeholder, new Dictionary<string, IReadOnlyDictionary<string, object?>>(StringComparer.Ordinal)
        {
            ["$/0"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "flame"
            }
        });
        StatusBuff43 = _statusBuff43Component.Root;

        ApplyStaticValues();
        ApplyInstanceOverrides();
        ViewModel = _initialViewModel;
    }

    public void Refresh()
    {
        if (_viewModel == null)
        {
            return;
        }

    }

    private void ApplyInstanceOverrides()
    {
        if (_componentOverrides == null)
        {
            return;
        }

        if (TryGetComponentOverrideValue("$/0/0", "Text", out var componentOverrideValue0))
        {
            AreaName.text = AsString(componentOverrideValue0);
            ApplyTextLabelStyle(AreaName, false);
        }
        if (TryGetComponentOverrideValue("$/0/1", "Text", out var componentOverrideValue1))
        {
            EncounterState.text = AsString(componentOverrideValue1);
            ApplyTextLabelStyle(EncounterState, false);
        }
        if (TryGetComponentOverrideValue("$/1/0/1/1", "Text", out var componentOverrideValue2))
        {
            HpText.text = AsString(componentOverrideValue2);
            ApplyTextLabelStyle(HpText, false);
        }
        if (TryGetComponentOverrideValue("$/1/0/2/1", "Text", out var componentOverrideValue3))
        {
            MpText.text = AsString(componentOverrideValue3);
            ApplyTextLabelStyle(MpText, false);
        }
        if (TryGetComponentOverrideValue("$/1/1/1/1", "Text", out var componentOverrideValue4))
        {
            HpText2.text = AsString(componentOverrideValue4);
            ApplyTextLabelStyle(HpText2, false);
        }
        if (TryGetComponentOverrideValue("$/1/1/2/1", "Text", out var componentOverrideValue5))
        {
            MpText2.text = AsString(componentOverrideValue5);
            ApplyTextLabelStyle(MpText2, false);
        }
        if (TryGetComponentOverrideValue("$/1/2/1/1", "Text", out var componentOverrideValue6))
        {
            HpText3.text = AsString(componentOverrideValue6);
            ApplyTextLabelStyle(HpText3, false);
        }
        if (TryGetComponentOverrideValue("$/1/2/2/1", "Text", out var componentOverrideValue7))
        {
            MpText3.text = AsString(componentOverrideValue7);
            ApplyTextLabelStyle(MpText3, false);
        }
    }

    private void ApplyStaticValues()
    {
        Root.style.flexDirection = ParseFlexDirection("column");
        Root.style.width = ParseStyleLength("1280px");
        Root.style.height = ParseStyleLength("320px");
        Root.style.marginTop = ParseStyleFloat("0px");
        Root.style.marginRight = ParseStyleFloat("0px");
        Root.style.marginBottom = ParseStyleFloat("0px");
        Root.style.marginLeft = ParseStyleFloat("0px");
        Root.style.paddingTop = ParseStyleFloat("24px");
        Root.style.paddingRight = ParseStyleFloat("24px");
        Root.style.paddingBottom = ParseStyleFloat("24px");
        Root.style.paddingLeft = ParseStyleFloat("24px");
        Root.style.alignItems = ParseAlign("flex-start");
        Root.style.justifyContent = ParseJustify("flex-start");
        Root.style.display = DisplayStyle.Flex;
        Root.SetEnabled(true);
        Root.style.color = ParseStyleColor("#050505", null);
        Root.style.backgroundColor = ParseStyleColor("#050505", null);
        Header.style.flexDirection = ParseFlexDirection("row");
        Header.style.alignSelf = ParseAlign("stretch");
        Header.style.height = ParseStyleLength("40px");
        Header.style.marginTop = ParseStyleFloat("0px");
        Header.style.marginRight = ParseStyleFloat("0px");
        Header.style.marginBottom = ParseStyleFloat("0px");
        Header.style.marginLeft = ParseStyleFloat("0px");
        Header.style.paddingTop = ParseStyleFloat("0px");
        Header.style.paddingRight = ParseStyleFloat("0px");
        Header.style.paddingBottom = ParseStyleFloat("0px");
        Header.style.paddingLeft = ParseStyleFloat("0px");
        Header.style.alignItems = ParseAlign("flex-start");
        Header.style.justifyContent = ParseJustify("flex-start");
        Header.style.display = DisplayStyle.Flex;
        Header.SetEnabled(true);
        Header.style.color = ParseStyleColor("#050505", null);
        Header.style.backgroundColor = ParseStyleColor("#050505", null);
        AreaName.style.flexDirection = ParseFlexDirection("column");
        AreaName.style.marginTop = ParseStyleFloat("0px");
        AreaName.style.marginRight = ParseStyleFloat("0px");
        AreaName.style.marginBottom = ParseStyleFloat("0px");
        AreaName.style.marginLeft = ParseStyleFloat("0px");
        AreaName.style.paddingTop = ParseStyleFloat("0px");
        AreaName.style.paddingRight = ParseStyleFloat("0px");
        AreaName.style.paddingBottom = ParseStyleFloat("0px");
        AreaName.style.paddingLeft = ParseStyleFloat("0px");
        AreaName.style.alignItems = ParseAlign("flex-start");
        AreaName.style.justifyContent = ParseJustify("flex-start");
        AreaName.text = "PartyStatusStrip";
        ApplyTextLabelStyle(AreaName, false);
        AreaName.style.display = DisplayStyle.Flex;
        AreaName.SetEnabled(true);
        ApplyFontFamily(AreaName, "Press Start 2P", 18f);
        AreaName.style.color = ParseStyleColor("#FFFFFF", null);
        AreaName.style.fontSize = 18f;
        AreaName.style.unityFontStyleAndWeight = UnityEngine.FontStyle.Normal;
        EncounterState.style.flexDirection = ParseFlexDirection("column");
        EncounterState.style.marginTop = ParseStyleFloat("0px");
        EncounterState.style.marginRight = ParseStyleFloat("0px");
        EncounterState.style.marginBottom = ParseStyleFloat("0px");
        EncounterState.style.marginLeft = ParseStyleFloat("0px");
        EncounterState.style.paddingTop = ParseStyleFloat("0px");
        EncounterState.style.paddingRight = ParseStyleFloat("0px");
        EncounterState.style.paddingBottom = ParseStyleFloat("0px");
        EncounterState.style.paddingLeft = ParseStyleFloat("0px");
        EncounterState.style.alignItems = ParseAlign("flex-start");
        EncounterState.style.justifyContent = ParseJustify("flex-start");
        EncounterState.text = "ENCOUNTER READY";
        ApplyTextLabelStyle(EncounterState, false);
        EncounterState.style.display = DisplayStyle.Flex;
        EncounterState.SetEnabled(true);
        ApplyFontFamily(EncounterState, "Press Start 2P", 12f);
        EncounterState.style.color = ParseStyleColor("#AAAAAA", null);
        EncounterState.style.fontSize = 12f;
        EncounterState.style.unityFontStyleAndWeight = UnityEngine.FontStyle.Normal;
        MemberRow.style.flexDirection = ParseFlexDirection("row");
        MemberRow.style.alignSelf = ParseAlign("stretch");
        MemberRow.style.height = ParseStyleLength("216px");
        MemberRow.style.marginTop = ParseStyleFloat("16px");
        MemberRow.style.marginRight = ParseStyleFloat("0px");
        MemberRow.style.marginBottom = ParseStyleFloat("0px");
        MemberRow.style.marginLeft = ParseStyleFloat("0px");
        MemberRow.style.paddingTop = ParseStyleFloat("0px");
        MemberRow.style.paddingRight = ParseStyleFloat("0px");
        MemberRow.style.paddingBottom = ParseStyleFloat("0px");
        MemberRow.style.paddingLeft = ParseStyleFloat("0px");
        MemberRow.style.alignItems = ParseAlign("flex-start");
        MemberRow.style.justifyContent = ParseJustify("flex-start");
        MemberRow.style.display = DisplayStyle.Flex;
        MemberRow.SetEnabled(true);
        MemberRow.style.color = ParseStyleColor("#050505", null);
        MemberRow.style.backgroundColor = ParseStyleColor("#050505", null);
        MemberA.style.flexDirection = ParseFlexDirection("column");
        MemberA.style.width = ParseStyleLength("400px");
        MemberA.style.alignSelf = ParseAlign("stretch");
        MemberA.style.marginTop = ParseStyleFloat("0px");
        MemberA.style.marginRight = ParseStyleFloat("0px");
        MemberA.style.marginBottom = ParseStyleFloat("0px");
        MemberA.style.marginLeft = ParseStyleFloat("0px");
        MemberA.style.paddingTop = ParseStyleFloat("12px");
        MemberA.style.paddingRight = ParseStyleFloat("12px");
        MemberA.style.paddingBottom = ParseStyleFloat("12px");
        MemberA.style.paddingLeft = ParseStyleFloat("12px");
        MemberA.style.alignItems = ParseAlign("flex-start");
        MemberA.style.justifyContent = ParseJustify("flex-start");
        MemberA.style.display = DisplayStyle.Flex;
        MemberA.SetEnabled(true);
        MemberA.style.color = ParseStyleColor("#101010", null);
        MemberA.style.backgroundColor = ParseStyleColor("#101010", null);
        MemberA.style.borderLeftWidth = 6f;
        MemberA.style.borderRightWidth = 6f;
        MemberA.style.borderTopWidth = 6f;
        MemberA.style.borderBottomWidth = 6f;
        MemberA.style.borderLeftColor = ParseStyleColor("#7E7E7E", null);
        MemberA.style.borderRightColor = ParseStyleColor("#7E7E7E", null);
        MemberA.style.borderTopColor = ParseStyleColor("#7E7E7E", null);
        MemberA.style.borderBottomColor = ParseStyleColor("#7E7E7E", null);
        HeroRow.style.display = DisplayStyle.Flex;
        HeroRow.SetEnabled(true);
        HpBar.style.flexDirection = ParseFlexDirection("column");
        HpBar.style.alignSelf = ParseAlign("stretch");
        HpBar.style.height = ParseStyleLength("22px");
        HpBar.style.marginTop = ParseStyleFloat("12px");
        HpBar.style.marginRight = ParseStyleFloat("0px");
        HpBar.style.marginBottom = ParseStyleFloat("0px");
        HpBar.style.marginLeft = ParseStyleFloat("0px");
        HpBar.style.paddingTop = ParseStyleFloat("0px");
        HpBar.style.paddingRight = ParseStyleFloat("0px");
        HpBar.style.paddingBottom = ParseStyleFloat("0px");
        HpBar.style.paddingLeft = ParseStyleFloat("0px");
        HpBar.style.alignItems = ParseAlign("flex-start");
        HpBar.style.justifyContent = ParseJustify("flex-start");
        HpBar.style.display = DisplayStyle.Flex;
        HpBar.SetEnabled(true);
        HpBar.style.color = ParseStyleColor("#1E1E1E", null);
        HpBar.style.backgroundColor = ParseStyleColor("#1E1E1E", null);
        HpBar.style.borderLeftWidth = 2f;
        HpBar.style.borderRightWidth = 2f;
        HpBar.style.borderTopWidth = 2f;
        HpBar.style.borderBottomWidth = 2f;
        HpBar.style.borderLeftColor = ParseStyleColor("#8C8C8C", null);
        HpBar.style.borderRightColor = ParseStyleColor("#8C8C8C", null);
        HpBar.style.borderTopColor = ParseStyleColor("#8C8C8C", null);
        HpBar.style.borderBottomColor = ParseStyleColor("#8C8C8C", null);
        HpFill.style.position = ParsePosition("absolute");
        HpFill.style.flexDirection = ParseFlexDirection("column");
        HpFill.style.width = ParseStyleLength("282px");
        HpFill.style.height = ParseStyleLength("18px");
        HpFill.style.marginTop = ParseStyleFloat("0px");
        HpFill.style.marginRight = ParseStyleFloat("0px");
        HpFill.style.marginBottom = ParseStyleFloat("0px");
        HpFill.style.marginLeft = ParseStyleFloat("0px");
        HpFill.style.paddingTop = ParseStyleFloat("0px");
        HpFill.style.paddingRight = ParseStyleFloat("0px");
        HpFill.style.paddingBottom = ParseStyleFloat("0px");
        HpFill.style.paddingLeft = ParseStyleFloat("0px");
        HpFill.style.alignItems = ParseAlign("flex-start");
        HpFill.style.justifyContent = ParseJustify("flex-start");
        HpFill.style.display = DisplayStyle.Flex;
        HpFill.SetEnabled(true);
        HpFill.style.color = ParseStyleColor("#D44A4A", null);
        HpFill.style.backgroundColor = ParseStyleColor("#D44A4A", null);
        HpText.style.position = ParsePosition("absolute");
        HpText.style.left = ParseStyleLength("12px");
        HpText.style.top = ParseStyleLength("4px");
        HpText.style.flexDirection = ParseFlexDirection("column");
        HpText.style.marginTop = ParseStyleFloat("0px");
        HpText.style.marginRight = ParseStyleFloat("0px");
        HpText.style.marginBottom = ParseStyleFloat("0px");
        HpText.style.marginLeft = ParseStyleFloat("0px");
        HpText.style.paddingTop = ParseStyleFloat("0px");
        HpText.style.paddingRight = ParseStyleFloat("0px");
        HpText.style.paddingBottom = ParseStyleFloat("0px");
        HpText.style.paddingLeft = ParseStyleFloat("0px");
        HpText.style.alignItems = ParseAlign("flex-start");
        HpText.style.justifyContent = ParseJustify("flex-start");
        HpText.text = "HP 182 / 220";
        ApplyTextLabelStyle(HpText, false);
        HpText.style.display = DisplayStyle.Flex;
        HpText.SetEnabled(true);
        ApplyFontFamily(HpText, "Press Start 2P", 9f);
        HpText.style.color = ParseStyleColor("#FFFFFF", null);
        HpText.style.fontSize = 9f;
        HpText.style.unityFontStyleAndWeight = UnityEngine.FontStyle.Normal;
        MpBar.style.flexDirection = ParseFlexDirection("column");
        MpBar.style.alignSelf = ParseAlign("stretch");
        MpBar.style.height = ParseStyleLength("22px");
        MpBar.style.marginTop = ParseStyleFloat("12px");
        MpBar.style.marginRight = ParseStyleFloat("0px");
        MpBar.style.marginBottom = ParseStyleFloat("0px");
        MpBar.style.marginLeft = ParseStyleFloat("0px");
        MpBar.style.paddingTop = ParseStyleFloat("0px");
        MpBar.style.paddingRight = ParseStyleFloat("0px");
        MpBar.style.paddingBottom = ParseStyleFloat("0px");
        MpBar.style.paddingLeft = ParseStyleFloat("0px");
        MpBar.style.alignItems = ParseAlign("flex-start");
        MpBar.style.justifyContent = ParseJustify("flex-start");
        MpBar.style.display = DisplayStyle.Flex;
        MpBar.SetEnabled(true);
        MpBar.style.color = ParseStyleColor("#1E1E1E", null);
        MpBar.style.backgroundColor = ParseStyleColor("#1E1E1E", null);
        MpBar.style.borderLeftWidth = 2f;
        MpBar.style.borderRightWidth = 2f;
        MpBar.style.borderTopWidth = 2f;
        MpBar.style.borderBottomWidth = 2f;
        MpBar.style.borderLeftColor = ParseStyleColor("#8C8C8C", null);
        MpBar.style.borderRightColor = ParseStyleColor("#8C8C8C", null);
        MpBar.style.borderTopColor = ParseStyleColor("#8C8C8C", null);
        MpBar.style.borderBottomColor = ParseStyleColor("#8C8C8C", null);
        MpFill.style.position = ParsePosition("absolute");
        MpFill.style.flexDirection = ParseFlexDirection("column");
        MpFill.style.width = ParseStyleLength("198px");
        MpFill.style.height = ParseStyleLength("18px");
        MpFill.style.marginTop = ParseStyleFloat("0px");
        MpFill.style.marginRight = ParseStyleFloat("0px");
        MpFill.style.marginBottom = ParseStyleFloat("0px");
        MpFill.style.marginLeft = ParseStyleFloat("0px");
        MpFill.style.paddingTop = ParseStyleFloat("0px");
        MpFill.style.paddingRight = ParseStyleFloat("0px");
        MpFill.style.paddingBottom = ParseStyleFloat("0px");
        MpFill.style.paddingLeft = ParseStyleFloat("0px");
        MpFill.style.alignItems = ParseAlign("flex-start");
        MpFill.style.justifyContent = ParseJustify("flex-start");
        MpFill.style.display = DisplayStyle.Flex;
        MpFill.SetEnabled(true);
        MpFill.style.color = ParseStyleColor("#4A78D4", null);
        MpFill.style.backgroundColor = ParseStyleColor("#4A78D4", null);
        MpText.style.position = ParsePosition("absolute");
        MpText.style.left = ParseStyleLength("12px");
        MpText.style.top = ParseStyleLength("4px");
        MpText.style.flexDirection = ParseFlexDirection("column");
        MpText.style.marginTop = ParseStyleFloat("0px");
        MpText.style.marginRight = ParseStyleFloat("0px");
        MpText.style.marginBottom = ParseStyleFloat("0px");
        MpText.style.marginLeft = ParseStyleFloat("0px");
        MpText.style.paddingTop = ParseStyleFloat("0px");
        MpText.style.paddingRight = ParseStyleFloat("0px");
        MpText.style.paddingBottom = ParseStyleFloat("0px");
        MpText.style.paddingLeft = ParseStyleFloat("0px");
        MpText.style.alignItems = ParseAlign("flex-start");
        MpText.style.justifyContent = ParseJustify("flex-start");
        MpText.text = "MP 78 / 110";
        ApplyTextLabelStyle(MpText, false);
        MpText.style.display = DisplayStyle.Flex;
        MpText.SetEnabled(true);
        ApplyFontFamily(MpText, "Press Start 2P", 9f);
        MpText.style.color = ParseStyleColor("#FFFFFF", null);
        MpText.style.fontSize = 9f;
        MpText.style.unityFontStyleAndWeight = UnityEngine.FontStyle.Normal;
        StatusRow.style.flexDirection = ParseFlexDirection("row");
        StatusRow.style.alignSelf = ParseAlign("stretch");
        StatusRow.style.height = ParseStyleLength("56px");
        StatusRow.style.marginTop = ParseStyleFloat("12px");
        StatusRow.style.marginRight = ParseStyleFloat("0px");
        StatusRow.style.marginBottom = ParseStyleFloat("0px");
        StatusRow.style.marginLeft = ParseStyleFloat("0px");
        StatusRow.style.paddingTop = ParseStyleFloat("0px");
        StatusRow.style.paddingRight = ParseStyleFloat("0px");
        StatusRow.style.paddingBottom = ParseStyleFloat("0px");
        StatusRow.style.paddingLeft = ParseStyleFloat("0px");
        StatusRow.style.alignItems = ParseAlign("flex-start");
        StatusRow.style.justifyContent = ParseJustify("flex-start");
        StatusRow.style.display = DisplayStyle.Flex;
        StatusRow.SetEnabled(true);
        StatusRow.style.color = ParseStyleColor("#101010", null);
        StatusRow.style.backgroundColor = ParseStyleColor("#101010", null);
        StatusBuff1.style.display = DisplayStyle.Flex;
        StatusBuff1.SetEnabled(true);
        StatusBuff2.style.display = DisplayStyle.Flex;
        StatusBuff2.SetEnabled(true);
        StatusBuff3.style.display = DisplayStyle.Flex;
        StatusBuff3.SetEnabled(true);
        StatusBuff4.style.display = DisplayStyle.Flex;
        StatusBuff4.SetEnabled(true);
        MemberB.style.flexDirection = ParseFlexDirection("column");
        MemberB.style.width = ParseStyleLength("400px");
        MemberB.style.alignSelf = ParseAlign("stretch");
        MemberB.style.marginTop = ParseStyleFloat("0px");
        MemberB.style.marginRight = ParseStyleFloat("0px");
        MemberB.style.marginBottom = ParseStyleFloat("0px");
        MemberB.style.marginLeft = ParseStyleFloat("16px");
        MemberB.style.paddingTop = ParseStyleFloat("12px");
        MemberB.style.paddingRight = ParseStyleFloat("12px");
        MemberB.style.paddingBottom = ParseStyleFloat("12px");
        MemberB.style.paddingLeft = ParseStyleFloat("12px");
        MemberB.style.alignItems = ParseAlign("flex-start");
        MemberB.style.justifyContent = ParseJustify("flex-start");
        MemberB.style.display = DisplayStyle.Flex;
        MemberB.SetEnabled(true);
        MemberB.style.color = ParseStyleColor("#101010", null);
        MemberB.style.backgroundColor = ParseStyleColor("#101010", null);
        MemberB.style.borderLeftWidth = 6f;
        MemberB.style.borderRightWidth = 6f;
        MemberB.style.borderTopWidth = 6f;
        MemberB.style.borderBottomWidth = 6f;
        MemberB.style.borderLeftColor = ParseStyleColor("#7E7E7E", null);
        MemberB.style.borderRightColor = ParseStyleColor("#7E7E7E", null);
        MemberB.style.borderTopColor = ParseStyleColor("#7E7E7E", null);
        MemberB.style.borderBottomColor = ParseStyleColor("#7E7E7E", null);
        HeroRow2.style.display = DisplayStyle.Flex;
        HeroRow2.SetEnabled(true);
        HpBar2.style.flexDirection = ParseFlexDirection("column");
        HpBar2.style.alignSelf = ParseAlign("stretch");
        HpBar2.style.height = ParseStyleLength("22px");
        HpBar2.style.marginTop = ParseStyleFloat("12px");
        HpBar2.style.marginRight = ParseStyleFloat("0px");
        HpBar2.style.marginBottom = ParseStyleFloat("0px");
        HpBar2.style.marginLeft = ParseStyleFloat("0px");
        HpBar2.style.paddingTop = ParseStyleFloat("0px");
        HpBar2.style.paddingRight = ParseStyleFloat("0px");
        HpBar2.style.paddingBottom = ParseStyleFloat("0px");
        HpBar2.style.paddingLeft = ParseStyleFloat("0px");
        HpBar2.style.alignItems = ParseAlign("flex-start");
        HpBar2.style.justifyContent = ParseJustify("flex-start");
        HpBar2.style.display = DisplayStyle.Flex;
        HpBar2.SetEnabled(true);
        HpBar2.style.color = ParseStyleColor("#1E1E1E", null);
        HpBar2.style.backgroundColor = ParseStyleColor("#1E1E1E", null);
        HpBar2.style.borderLeftWidth = 2f;
        HpBar2.style.borderRightWidth = 2f;
        HpBar2.style.borderTopWidth = 2f;
        HpBar2.style.borderBottomWidth = 2f;
        HpBar2.style.borderLeftColor = ParseStyleColor("#8C8C8C", null);
        HpBar2.style.borderRightColor = ParseStyleColor("#8C8C8C", null);
        HpBar2.style.borderTopColor = ParseStyleColor("#8C8C8C", null);
        HpBar2.style.borderBottomColor = ParseStyleColor("#8C8C8C", null);
        HpFill2.style.position = ParsePosition("absolute");
        HpFill2.style.flexDirection = ParseFlexDirection("column");
        HpFill2.style.width = ParseStyleLength("234px");
        HpFill2.style.height = ParseStyleLength("18px");
        HpFill2.style.marginTop = ParseStyleFloat("0px");
        HpFill2.style.marginRight = ParseStyleFloat("0px");
        HpFill2.style.marginBottom = ParseStyleFloat("0px");
        HpFill2.style.marginLeft = ParseStyleFloat("0px");
        HpFill2.style.paddingTop = ParseStyleFloat("0px");
        HpFill2.style.paddingRight = ParseStyleFloat("0px");
        HpFill2.style.paddingBottom = ParseStyleFloat("0px");
        HpFill2.style.paddingLeft = ParseStyleFloat("0px");
        HpFill2.style.alignItems = ParseAlign("flex-start");
        HpFill2.style.justifyContent = ParseJustify("flex-start");
        HpFill2.style.display = DisplayStyle.Flex;
        HpFill2.SetEnabled(true);
        HpFill2.style.color = ParseStyleColor("#D44A4A", null);
        HpFill2.style.backgroundColor = ParseStyleColor("#D44A4A", null);
        HpText2.style.position = ParsePosition("absolute");
        HpText2.style.left = ParseStyleLength("12px");
        HpText2.style.top = ParseStyleLength("4px");
        HpText2.style.flexDirection = ParseFlexDirection("column");
        HpText2.style.marginTop = ParseStyleFloat("0px");
        HpText2.style.marginRight = ParseStyleFloat("0px");
        HpText2.style.marginBottom = ParseStyleFloat("0px");
        HpText2.style.marginLeft = ParseStyleFloat("0px");
        HpText2.style.paddingTop = ParseStyleFloat("0px");
        HpText2.style.paddingRight = ParseStyleFloat("0px");
        HpText2.style.paddingBottom = ParseStyleFloat("0px");
        HpText2.style.paddingLeft = ParseStyleFloat("0px");
        HpText2.style.alignItems = ParseAlign("flex-start");
        HpText2.style.justifyContent = ParseJustify("flex-start");
        HpText2.text = "HP 144 / 220";
        ApplyTextLabelStyle(HpText2, false);
        HpText2.style.display = DisplayStyle.Flex;
        HpText2.SetEnabled(true);
        ApplyFontFamily(HpText2, "Press Start 2P", 9f);
        HpText2.style.color = ParseStyleColor("#FFFFFF", null);
        HpText2.style.fontSize = 9f;
        HpText2.style.unityFontStyleAndWeight = UnityEngine.FontStyle.Normal;
        MpBar2.style.flexDirection = ParseFlexDirection("column");
        MpBar2.style.alignSelf = ParseAlign("stretch");
        MpBar2.style.height = ParseStyleLength("22px");
        MpBar2.style.marginTop = ParseStyleFloat("12px");
        MpBar2.style.marginRight = ParseStyleFloat("0px");
        MpBar2.style.marginBottom = ParseStyleFloat("0px");
        MpBar2.style.marginLeft = ParseStyleFloat("0px");
        MpBar2.style.paddingTop = ParseStyleFloat("0px");
        MpBar2.style.paddingRight = ParseStyleFloat("0px");
        MpBar2.style.paddingBottom = ParseStyleFloat("0px");
        MpBar2.style.paddingLeft = ParseStyleFloat("0px");
        MpBar2.style.alignItems = ParseAlign("flex-start");
        MpBar2.style.justifyContent = ParseJustify("flex-start");
        MpBar2.style.display = DisplayStyle.Flex;
        MpBar2.SetEnabled(true);
        MpBar2.style.color = ParseStyleColor("#1E1E1E", null);
        MpBar2.style.backgroundColor = ParseStyleColor("#1E1E1E", null);
        MpBar2.style.borderLeftWidth = 2f;
        MpBar2.style.borderRightWidth = 2f;
        MpBar2.style.borderTopWidth = 2f;
        MpBar2.style.borderBottomWidth = 2f;
        MpBar2.style.borderLeftColor = ParseStyleColor("#8C8C8C", null);
        MpBar2.style.borderRightColor = ParseStyleColor("#8C8C8C", null);
        MpBar2.style.borderTopColor = ParseStyleColor("#8C8C8C", null);
        MpBar2.style.borderBottomColor = ParseStyleColor("#8C8C8C", null);
        MpFill2.style.position = ParsePosition("absolute");
        MpFill2.style.flexDirection = ParseFlexDirection("column");
        MpFill2.style.width = ParseStyleLength("296px");
        MpFill2.style.height = ParseStyleLength("18px");
        MpFill2.style.marginTop = ParseStyleFloat("0px");
        MpFill2.style.marginRight = ParseStyleFloat("0px");
        MpFill2.style.marginBottom = ParseStyleFloat("0px");
        MpFill2.style.marginLeft = ParseStyleFloat("0px");
        MpFill2.style.paddingTop = ParseStyleFloat("0px");
        MpFill2.style.paddingRight = ParseStyleFloat("0px");
        MpFill2.style.paddingBottom = ParseStyleFloat("0px");
        MpFill2.style.paddingLeft = ParseStyleFloat("0px");
        MpFill2.style.alignItems = ParseAlign("flex-start");
        MpFill2.style.justifyContent = ParseJustify("flex-start");
        MpFill2.style.display = DisplayStyle.Flex;
        MpFill2.SetEnabled(true);
        MpFill2.style.color = ParseStyleColor("#4A78D4", null);
        MpFill2.style.backgroundColor = ParseStyleColor("#4A78D4", null);
        MpText2.style.position = ParsePosition("absolute");
        MpText2.style.left = ParseStyleLength("12px");
        MpText2.style.top = ParseStyleLength("4px");
        MpText2.style.flexDirection = ParseFlexDirection("column");
        MpText2.style.marginTop = ParseStyleFloat("0px");
        MpText2.style.marginRight = ParseStyleFloat("0px");
        MpText2.style.marginBottom = ParseStyleFloat("0px");
        MpText2.style.marginLeft = ParseStyleFloat("0px");
        MpText2.style.paddingTop = ParseStyleFloat("0px");
        MpText2.style.paddingRight = ParseStyleFloat("0px");
        MpText2.style.paddingBottom = ParseStyleFloat("0px");
        MpText2.style.paddingLeft = ParseStyleFloat("0px");
        MpText2.style.alignItems = ParseAlign("flex-start");
        MpText2.style.justifyContent = ParseJustify("flex-start");
        MpText2.text = "MP 124 / 138";
        ApplyTextLabelStyle(MpText2, false);
        MpText2.style.display = DisplayStyle.Flex;
        MpText2.SetEnabled(true);
        ApplyFontFamily(MpText2, "Press Start 2P", 9f);
        MpText2.style.color = ParseStyleColor("#FFFFFF", null);
        MpText2.style.fontSize = 9f;
        MpText2.style.unityFontStyleAndWeight = UnityEngine.FontStyle.Normal;
        StatusRow2.style.flexDirection = ParseFlexDirection("row");
        StatusRow2.style.alignSelf = ParseAlign("stretch");
        StatusRow2.style.height = ParseStyleLength("56px");
        StatusRow2.style.marginTop = ParseStyleFloat("12px");
        StatusRow2.style.marginRight = ParseStyleFloat("0px");
        StatusRow2.style.marginBottom = ParseStyleFloat("0px");
        StatusRow2.style.marginLeft = ParseStyleFloat("0px");
        StatusRow2.style.paddingTop = ParseStyleFloat("0px");
        StatusRow2.style.paddingRight = ParseStyleFloat("0px");
        StatusRow2.style.paddingBottom = ParseStyleFloat("0px");
        StatusRow2.style.paddingLeft = ParseStyleFloat("0px");
        StatusRow2.style.alignItems = ParseAlign("flex-start");
        StatusRow2.style.justifyContent = ParseJustify("flex-start");
        StatusRow2.style.display = DisplayStyle.Flex;
        StatusRow2.SetEnabled(true);
        StatusRow2.style.color = ParseStyleColor("#101010", null);
        StatusRow2.style.backgroundColor = ParseStyleColor("#101010", null);
        StatusBuff12.style.display = DisplayStyle.Flex;
        StatusBuff12.SetEnabled(true);
        StatusBuff22.style.display = DisplayStyle.Flex;
        StatusBuff22.SetEnabled(true);
        StatusBuff32.style.display = DisplayStyle.Flex;
        StatusBuff32.SetEnabled(true);
        StatusBuff42.style.display = DisplayStyle.Flex;
        StatusBuff42.SetEnabled(true);
        MemberC.style.flexDirection = ParseFlexDirection("column");
        MemberC.style.width = ParseStyleLength("400px");
        MemberC.style.alignSelf = ParseAlign("stretch");
        MemberC.style.marginTop = ParseStyleFloat("0px");
        MemberC.style.marginRight = ParseStyleFloat("0px");
        MemberC.style.marginBottom = ParseStyleFloat("0px");
        MemberC.style.marginLeft = ParseStyleFloat("16px");
        MemberC.style.paddingTop = ParseStyleFloat("12px");
        MemberC.style.paddingRight = ParseStyleFloat("12px");
        MemberC.style.paddingBottom = ParseStyleFloat("12px");
        MemberC.style.paddingLeft = ParseStyleFloat("12px");
        MemberC.style.alignItems = ParseAlign("flex-start");
        MemberC.style.justifyContent = ParseJustify("flex-start");
        MemberC.style.display = DisplayStyle.Flex;
        MemberC.SetEnabled(true);
        MemberC.style.color = ParseStyleColor("#101010", null);
        MemberC.style.backgroundColor = ParseStyleColor("#101010", null);
        MemberC.style.borderLeftWidth = 6f;
        MemberC.style.borderRightWidth = 6f;
        MemberC.style.borderTopWidth = 6f;
        MemberC.style.borderBottomWidth = 6f;
        MemberC.style.borderLeftColor = ParseStyleColor("#7E7E7E", null);
        MemberC.style.borderRightColor = ParseStyleColor("#7E7E7E", null);
        MemberC.style.borderTopColor = ParseStyleColor("#7E7E7E", null);
        MemberC.style.borderBottomColor = ParseStyleColor("#7E7E7E", null);
        HeroRow3.style.display = DisplayStyle.Flex;
        HeroRow3.SetEnabled(true);
        HpBar3.style.flexDirection = ParseFlexDirection("column");
        HpBar3.style.alignSelf = ParseAlign("stretch");
        HpBar3.style.height = ParseStyleLength("22px");
        HpBar3.style.marginTop = ParseStyleFloat("12px");
        HpBar3.style.marginRight = ParseStyleFloat("0px");
        HpBar3.style.marginBottom = ParseStyleFloat("0px");
        HpBar3.style.marginLeft = ParseStyleFloat("0px");
        HpBar3.style.paddingTop = ParseStyleFloat("0px");
        HpBar3.style.paddingRight = ParseStyleFloat("0px");
        HpBar3.style.paddingBottom = ParseStyleFloat("0px");
        HpBar3.style.paddingLeft = ParseStyleFloat("0px");
        HpBar3.style.alignItems = ParseAlign("flex-start");
        HpBar3.style.justifyContent = ParseJustify("flex-start");
        HpBar3.style.display = DisplayStyle.Flex;
        HpBar3.SetEnabled(true);
        HpBar3.style.color = ParseStyleColor("#1E1E1E", null);
        HpBar3.style.backgroundColor = ParseStyleColor("#1E1E1E", null);
        HpBar3.style.borderLeftWidth = 2f;
        HpBar3.style.borderRightWidth = 2f;
        HpBar3.style.borderTopWidth = 2f;
        HpBar3.style.borderBottomWidth = 2f;
        HpBar3.style.borderLeftColor = ParseStyleColor("#8C8C8C", null);
        HpBar3.style.borderRightColor = ParseStyleColor("#8C8C8C", null);
        HpBar3.style.borderTopColor = ParseStyleColor("#8C8C8C", null);
        HpBar3.style.borderBottomColor = ParseStyleColor("#8C8C8C", null);
        HpFill3.style.position = ParsePosition("absolute");
        HpFill3.style.flexDirection = ParseFlexDirection("column");
        HpFill3.style.width = ParseStyleLength("318px");
        HpFill3.style.height = ParseStyleLength("18px");
        HpFill3.style.marginTop = ParseStyleFloat("0px");
        HpFill3.style.marginRight = ParseStyleFloat("0px");
        HpFill3.style.marginBottom = ParseStyleFloat("0px");
        HpFill3.style.marginLeft = ParseStyleFloat("0px");
        HpFill3.style.paddingTop = ParseStyleFloat("0px");
        HpFill3.style.paddingRight = ParseStyleFloat("0px");
        HpFill3.style.paddingBottom = ParseStyleFloat("0px");
        HpFill3.style.paddingLeft = ParseStyleFloat("0px");
        HpFill3.style.alignItems = ParseAlign("flex-start");
        HpFill3.style.justifyContent = ParseJustify("flex-start");
        HpFill3.style.display = DisplayStyle.Flex;
        HpFill3.SetEnabled(true);
        HpFill3.style.color = ParseStyleColor("#D44A4A", null);
        HpFill3.style.backgroundColor = ParseStyleColor("#D44A4A", null);
        HpText3.style.position = ParsePosition("absolute");
        HpText3.style.left = ParseStyleLength("12px");
        HpText3.style.top = ParseStyleLength("4px");
        HpText3.style.flexDirection = ParseFlexDirection("column");
        HpText3.style.marginTop = ParseStyleFloat("0px");
        HpText3.style.marginRight = ParseStyleFloat("0px");
        HpText3.style.marginBottom = ParseStyleFloat("0px");
        HpText3.style.marginLeft = ParseStyleFloat("0px");
        HpText3.style.paddingTop = ParseStyleFloat("0px");
        HpText3.style.paddingRight = ParseStyleFloat("0px");
        HpText3.style.paddingBottom = ParseStyleFloat("0px");
        HpText3.style.paddingLeft = ParseStyleFloat("0px");
        HpText3.style.alignItems = ParseAlign("flex-start");
        HpText3.style.justifyContent = ParseJustify("flex-start");
        HpText3.text = "HP 210 / 220";
        ApplyTextLabelStyle(HpText3, false);
        HpText3.style.display = DisplayStyle.Flex;
        HpText3.SetEnabled(true);
        ApplyFontFamily(HpText3, "Press Start 2P", 9f);
        HpText3.style.color = ParseStyleColor("#FFFFFF", null);
        HpText3.style.fontSize = 9f;
        HpText3.style.unityFontStyleAndWeight = UnityEngine.FontStyle.Normal;
        MpBar3.style.flexDirection = ParseFlexDirection("column");
        MpBar3.style.alignSelf = ParseAlign("stretch");
        MpBar3.style.height = ParseStyleLength("22px");
        MpBar3.style.marginTop = ParseStyleFloat("12px");
        MpBar3.style.marginRight = ParseStyleFloat("0px");
        MpBar3.style.marginBottom = ParseStyleFloat("0px");
        MpBar3.style.marginLeft = ParseStyleFloat("0px");
        MpBar3.style.paddingTop = ParseStyleFloat("0px");
        MpBar3.style.paddingRight = ParseStyleFloat("0px");
        MpBar3.style.paddingBottom = ParseStyleFloat("0px");
        MpBar3.style.paddingLeft = ParseStyleFloat("0px");
        MpBar3.style.alignItems = ParseAlign("flex-start");
        MpBar3.style.justifyContent = ParseJustify("flex-start");
        MpBar3.style.display = DisplayStyle.Flex;
        MpBar3.SetEnabled(true);
        MpBar3.style.color = ParseStyleColor("#1E1E1E", null);
        MpBar3.style.backgroundColor = ParseStyleColor("#1E1E1E", null);
        MpBar3.style.borderLeftWidth = 2f;
        MpBar3.style.borderRightWidth = 2f;
        MpBar3.style.borderTopWidth = 2f;
        MpBar3.style.borderBottomWidth = 2f;
        MpBar3.style.borderLeftColor = ParseStyleColor("#8C8C8C", null);
        MpBar3.style.borderRightColor = ParseStyleColor("#8C8C8C", null);
        MpBar3.style.borderTopColor = ParseStyleColor("#8C8C8C", null);
        MpBar3.style.borderBottomColor = ParseStyleColor("#8C8C8C", null);
        MpFill3.style.position = ParsePosition("absolute");
        MpFill3.style.flexDirection = ParseFlexDirection("column");
        MpFill3.style.width = ParseStyleLength("154px");
        MpFill3.style.height = ParseStyleLength("18px");
        MpFill3.style.marginTop = ParseStyleFloat("0px");
        MpFill3.style.marginRight = ParseStyleFloat("0px");
        MpFill3.style.marginBottom = ParseStyleFloat("0px");
        MpFill3.style.marginLeft = ParseStyleFloat("0px");
        MpFill3.style.paddingTop = ParseStyleFloat("0px");
        MpFill3.style.paddingRight = ParseStyleFloat("0px");
        MpFill3.style.paddingBottom = ParseStyleFloat("0px");
        MpFill3.style.paddingLeft = ParseStyleFloat("0px");
        MpFill3.style.alignItems = ParseAlign("flex-start");
        MpFill3.style.justifyContent = ParseJustify("flex-start");
        MpFill3.style.display = DisplayStyle.Flex;
        MpFill3.SetEnabled(true);
        MpFill3.style.color = ParseStyleColor("#4A78D4", null);
        MpFill3.style.backgroundColor = ParseStyleColor("#4A78D4", null);
        MpText3.style.position = ParsePosition("absolute");
        MpText3.style.left = ParseStyleLength("12px");
        MpText3.style.top = ParseStyleLength("4px");
        MpText3.style.flexDirection = ParseFlexDirection("column");
        MpText3.style.marginTop = ParseStyleFloat("0px");
        MpText3.style.marginRight = ParseStyleFloat("0px");
        MpText3.style.marginBottom = ParseStyleFloat("0px");
        MpText3.style.marginLeft = ParseStyleFloat("0px");
        MpText3.style.paddingTop = ParseStyleFloat("0px");
        MpText3.style.paddingRight = ParseStyleFloat("0px");
        MpText3.style.paddingBottom = ParseStyleFloat("0px");
        MpText3.style.paddingLeft = ParseStyleFloat("0px");
        MpText3.style.alignItems = ParseAlign("flex-start");
        MpText3.style.justifyContent = ParseJustify("flex-start");
        MpText3.text = "MP 42 / 110";
        ApplyTextLabelStyle(MpText3, false);
        MpText3.style.display = DisplayStyle.Flex;
        MpText3.SetEnabled(true);
        ApplyFontFamily(MpText3, "Press Start 2P", 9f);
        MpText3.style.color = ParseStyleColor("#FFFFFF", null);
        MpText3.style.fontSize = 9f;
        MpText3.style.unityFontStyleAndWeight = UnityEngine.FontStyle.Normal;
        StatusRow3.style.flexDirection = ParseFlexDirection("row");
        StatusRow3.style.alignSelf = ParseAlign("stretch");
        StatusRow3.style.height = ParseStyleLength("56px");
        StatusRow3.style.marginTop = ParseStyleFloat("12px");
        StatusRow3.style.marginRight = ParseStyleFloat("0px");
        StatusRow3.style.marginBottom = ParseStyleFloat("0px");
        StatusRow3.style.marginLeft = ParseStyleFloat("0px");
        StatusRow3.style.paddingTop = ParseStyleFloat("0px");
        StatusRow3.style.paddingRight = ParseStyleFloat("0px");
        StatusRow3.style.paddingBottom = ParseStyleFloat("0px");
        StatusRow3.style.paddingLeft = ParseStyleFloat("0px");
        StatusRow3.style.alignItems = ParseAlign("flex-start");
        StatusRow3.style.justifyContent = ParseJustify("flex-start");
        StatusRow3.style.display = DisplayStyle.Flex;
        StatusRow3.SetEnabled(true);
        StatusRow3.style.color = ParseStyleColor("#101010", null);
        StatusRow3.style.backgroundColor = ParseStyleColor("#101010", null);
        StatusBuff13.style.display = DisplayStyle.Flex;
        StatusBuff13.SetEnabled(true);
        StatusBuff23.style.display = DisplayStyle.Flex;
        StatusBuff23.SetEnabled(true);
        StatusBuff33.style.display = DisplayStyle.Flex;
        StatusBuff33.SetEnabled(true);
        StatusBuff43.style.display = DisplayStyle.Flex;
        StatusBuff43.SetEnabled(true);
    }

    private void ApplyComponentViewModels()
    {
        if (_heroRowComponent != null)
        {
            _heroRowComponent.ViewModel = _viewModel is ISyntheticContainerAF9ECAF6ViewModel componentViewModel ? componentViewModel : null;
        }
        if (_statusBuff1Component != null)
        {
            _statusBuff1Component.ViewModel = _viewModel is ISyntheticContainerB978BB0BViewModel componentViewModel ? componentViewModel : null;
        }
        if (_statusBuff2Component != null)
        {
            _statusBuff2Component.ViewModel = _viewModel is ISyntheticContainerB978BB0BViewModel componentViewModel ? componentViewModel : null;
        }
        if (_statusBuff3Component != null)
        {
            _statusBuff3Component.ViewModel = _viewModel is ISyntheticContainerB978BB0BViewModel componentViewModel ? componentViewModel : null;
        }
        if (_statusBuff4Component != null)
        {
            _statusBuff4Component.ViewModel = _viewModel is ISyntheticContainerB978BB0BViewModel componentViewModel ? componentViewModel : null;
        }
        if (_heroRow2Component != null)
        {
            _heroRow2Component.ViewModel = _viewModel is ISyntheticContainerAF9ECAF6ViewModel componentViewModel ? componentViewModel : null;
        }
        if (_statusBuff12Component != null)
        {
            _statusBuff12Component.ViewModel = _viewModel is ISyntheticContainerB978BB0BViewModel componentViewModel ? componentViewModel : null;
        }
        if (_statusBuff22Component != null)
        {
            _statusBuff22Component.ViewModel = _viewModel is ISyntheticContainerB978BB0BViewModel componentViewModel ? componentViewModel : null;
        }
        if (_statusBuff32Component != null)
        {
            _statusBuff32Component.ViewModel = _viewModel is ISyntheticContainerB978BB0BViewModel componentViewModel ? componentViewModel : null;
        }
        if (_statusBuff42Component != null)
        {
            _statusBuff42Component.ViewModel = _viewModel is ISyntheticContainerB978BB0BViewModel componentViewModel ? componentViewModel : null;
        }
        if (_heroRow3Component != null)
        {
            _heroRow3Component.ViewModel = _viewModel is ISyntheticContainerAF9ECAF6ViewModel componentViewModel ? componentViewModel : null;
        }
        if (_statusBuff13Component != null)
        {
            _statusBuff13Component.ViewModel = _viewModel is ISyntheticContainerB978BB0BViewModel componentViewModel ? componentViewModel : null;
        }
        if (_statusBuff23Component != null)
        {
            _statusBuff23Component.ViewModel = _viewModel is ISyntheticContainerB978BB0BViewModel componentViewModel ? componentViewModel : null;
        }
        if (_statusBuff33Component != null)
        {
            _statusBuff33Component.ViewModel = _viewModel is ISyntheticContainerB978BB0BViewModel componentViewModel ? componentViewModel : null;
        }
        if (_statusBuff43Component != null)
        {
            _statusBuff43Component.ViewModel = _viewModel is ISyntheticContainerB978BB0BViewModel componentViewModel ? componentViewModel : null;
        }
    }

    private void OnViewModelPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        Refresh();
    }

    private const string VisualTreeResourcePath = "BoomHudGenerated/PartyStatusStripView";
    private const string StyleSheetResourcePath = "BoomHudGenerated/PartyStatusStripView";
    private const string GeneratedRootName = "PartyStatusStrip";
    private static VisualTreeAsset? s_visualTreeAsset;
    private static StyleSheet? s_generatedStyleSheet;

    public static PartyStatusStripView Create(VisualElement parent, string? instanceName = null, IReadOnlyDictionary<string, IReadOnlyDictionary<string, object?>>? componentOverrides = null)
    {
        if (parent == null)
        {
            throw new ArgumentNullException(nameof(parent));
        }

        var root = CreateGeneratedRoot(instanceName);
        parent.Add(root);
        return new PartyStatusStripView(root, componentOverrides);
    }

    public static PartyStatusStripView Attach(VisualElement placeholder, IReadOnlyDictionary<string, IReadOnlyDictionary<string, object?>>? componentOverrides = null)
    {
        if (placeholder == null)
        {
            throw new ArgumentNullException(nameof(placeholder));
        }

        var parent = placeholder.parent ?? throw new InvalidOperationException("Cannot attach a generated component without a parent element.");
        var placeholderIndex = parent.IndexOf(placeholder);
        var root = CreateGeneratedRoot(string.IsNullOrWhiteSpace(placeholder.name) ? null : placeholder.name);
        parent.Insert(placeholderIndex, root);
        placeholder.RemoveFromHierarchy();
        return new PartyStatusStripView(root, componentOverrides);
    }

    private static VisualElement CreateGeneratedRoot(string? instanceName)
    {
        s_visualTreeAsset ??= Resources.Load<VisualTreeAsset>(VisualTreeResourcePath)
            ?? throw new InvalidOperationException($"Could not load VisualTreeAsset from Resources/{VisualTreeResourcePath}.uxml");
        s_generatedStyleSheet ??= Resources.Load<StyleSheet>(StyleSheetResourcePath);

        var staging = new VisualElement();
        s_visualTreeAsset.CloneTree(staging);
        var root = staging.Q<VisualElement>(GeneratedRootName)
            ?? throw new InvalidOperationException($"Could not find generated root element '{GeneratedRootName}' after cloning the tree.");
        root.RemoveFromHierarchy();
        root.name = string.IsNullOrWhiteSpace(instanceName) ? GeneratedRootName : instanceName!;

        if (s_generatedStyleSheet != null && !root.styleSheets.Contains(s_generatedStyleSheet))
        {
            root.styleSheets.Add(s_generatedStyleSheet);
        }

        return root;
    }

    private static readonly Dictionary<string, FontDefinition> s_fontDefinitions = new(StringComparer.OrdinalIgnoreCase);
    private static readonly Dictionary<string, FontAsset> s_sdfFontAssets = new(StringComparer.OrdinalIgnoreCase);
    private static readonly Dictionary<string, string> s_fontResourcePaths = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Press Start 2P"] = "BoomHudFonts/PressStart2P-Regular",
        ["lucide"] = "BoomHudFonts/lucide"
    };
    private static readonly Dictionary<string, string> s_lucideGlyphs = new(StringComparer.OrdinalIgnoreCase)
    {
        ["cross"] = "\uE1E5",
        ["flame"] = "\uE0D2",
        ["flask-conical"] = "\uE0D5",
        ["moon"] = "\uE11E",
        ["shield"] = "\uE158",
        ["sparkles"] = "\uE412",
        ["sword"] = "\uE2B3",
        ["swords"] = "\uE2B4",
        ["wand"] = "\uE246",
        ["wand-2"] = "\uE357",
        ["wand-sparkles"] = "\uE357"
    };

    private static string AsString(object? value) => value?.ToString() ?? string.Empty;

    private static float AsFloat(object? value)
    {
        return value switch
        {
            null => 0f,
            float floatValue => floatValue,
            double doubleValue => (float)doubleValue,
            int intValue => intValue,
            long longValue => longValue,
            decimal decimalValue => (float)decimalValue,
            string stringValue when float.TryParse(stringValue, NumberStyles.Float, CultureInfo.InvariantCulture, out var parsed) => parsed,
            _ => 0f
        };
    }

    private static bool AsBool(object? value)
    {
        return value switch
        {
            bool boolValue => boolValue,
            string stringValue when bool.TryParse(stringValue, out var parsed) => parsed,
            int intValue => intValue != 0,
            long longValue => longValue != 0,
            _ => false
        };
    }

    private bool TryGetComponentOverrideValue(string nodePath, string propertyName, out object? value)
    {
        value = null;
        if (_componentOverrides == null || !_componentOverrides.TryGetValue(nodePath, out var propertyOverrides))
        {
            return false;
        }

        if (propertyOverrides.TryGetValue(propertyName, out value))
        {
            return true;
        }

        foreach (var candidate in propertyOverrides)
        {
            if (string.Equals(candidate.Key, propertyName, StringComparison.OrdinalIgnoreCase))
            {
                value = candidate.Value;
                return true;
            }
        }

        return false;
    }

    private static StyleLength ParseStyleLength(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return StyleKeyword.Null;
        }

        if (string.Equals(value, "auto", StringComparison.OrdinalIgnoreCase))
        {
            return StyleKeyword.Auto;
        }

        if (value.EndsWith("%", StringComparison.Ordinal))
        {
            var number = value[..^1];
            return float.TryParse(number, NumberStyles.Float, CultureInfo.InvariantCulture, out var percent)
                ? new StyleLength(new Length(percent, LengthUnit.Percent))
                : StyleKeyword.Null;
        }

        if (value.EndsWith("px", StringComparison.OrdinalIgnoreCase))
        {
            var number = value[..^2];
            return float.TryParse(number, NumberStyles.Float, CultureInfo.InvariantCulture, out var pixels)
                ? new StyleLength(pixels)
                : StyleKeyword.Null;
        }

        return float.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out var raw)
            ? new StyleLength(raw)
            : StyleKeyword.Null;
    }

    private static float ParseStyleFloat(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return 0f;
        }

        var normalized = value.EndsWith("px", StringComparison.OrdinalIgnoreCase)
            ? value[..^2]
            : value;

        return float.TryParse(normalized, NumberStyles.Float, CultureInfo.InvariantCulture, out var parsed)
            ? parsed
            : 0f;
    }

    private static Position ParsePosition(string value)
        => string.Equals(value, "absolute", StringComparison.OrdinalIgnoreCase)
            ? Position.Absolute
            : Position.Relative;

    private static FlexDirection ParseFlexDirection(string value)
        => string.Equals(value, "row", StringComparison.OrdinalIgnoreCase)
            ? FlexDirection.Row
            : FlexDirection.Column;

    private static Overflow ParseOverflow(string value)
        => string.Equals(value, "hidden", StringComparison.OrdinalIgnoreCase)
            ? Overflow.Hidden
            : Overflow.Visible;

    private static Align ParseAlign(string value)
        => value.ToLowerInvariant() switch
        {
            "flex-start" => Align.FlexStart,
            "center" => Align.Center,
            "flex-end" => Align.FlexEnd,
            "stretch" => Align.Stretch,
            "auto" => Align.Auto,
            _ => Align.Stretch
        };

    private static Justify ParseJustify(string value)
        => value.ToLowerInvariant() switch
        {
            "flex-start" => Justify.FlexStart,
            "center" => Justify.Center,
            "flex-end" => Justify.FlexEnd,
            "space-between" => Justify.SpaceBetween,
            "space-around" => Justify.SpaceAround,
            "space-evenly" => Justify.SpaceEvenly,
            _ => Justify.FlexStart
        };

    private static string? ResolveMappedStyleValue(object? value, string? fallbackValue, params string[] mappings)
    {
        var key = AsString(value);

        for (var index = 0; index + 1 < mappings.Length; index += 2)
        {
            if (string.Equals(mappings[index], key, StringComparison.OrdinalIgnoreCase))
            {
                return mappings[index + 1];
            }
        }

        return string.IsNullOrWhiteSpace(key) ? fallbackValue : key;
    }

    private static Color ParseStyleColor(string? value, string? fallbackValue)
    {
        if (!string.IsNullOrWhiteSpace(value) && ColorUtility.TryParseHtmlString(value, out var parsed))
        {
            return parsed;
        }

        if (!string.IsNullOrWhiteSpace(fallbackValue) && ColorUtility.TryParseHtmlString(fallbackValue, out var fallback))
        {
            return fallback;
        }

        return default;
    }

    private static void SetImageSource(Image image, string resourcePath)
    {
        if (string.IsNullOrWhiteSpace(resourcePath))
        {
            image.image = null;
            return;
        }

        var normalized = resourcePath.Replace("\\", "/", StringComparison.Ordinal).TrimStart('/');
        var extensionIndex = normalized.LastIndexOf('.');
        if (extensionIndex > 0)
        {
            normalized = normalized[..extensionIndex];
        }

        image.image = Resources.Load<Texture2D>(normalized);
    }

    private static void ApplyTextLabelStyle(Label label, bool wrapText)
    {
        label.style.whiteSpace = wrapText ? WhiteSpace.Normal : WhiteSpace.NoWrap;
        label.style.flexShrink = wrapText ? 1 : 0;
        label.style.overflow = wrapText ? Overflow.Hidden : Overflow.Visible;
    }

    private static bool ApplyFontFamily(VisualElement element, string? familyName, float pointSize)
    {
        if (element == null || string.IsNullOrWhiteSpace(familyName))
        {
            return false;
        }

        if (!TryResolveFontDefinition(familyName, pointSize, out var fontDefinition))
        {
            return false;
        }

        element.style.unityFontDefinition = fontDefinition;
        return true;
    }

    private static bool TryResolveFontDefinition(string? familyName, float pointSize, out FontDefinition fontDefinition)
    {
        fontDefinition = default;

        if (string.IsNullOrWhiteSpace(familyName))
        {
            return false;
        }

        var normalizedFamily = familyName.Trim();
        var normalizedSize = Mathf.Max(1, Mathf.RoundToInt(pointSize));
        var cacheKey = $"{normalizedFamily}|{normalizedSize}";

        if (s_fontDefinitions.TryGetValue(cacheKey, out fontDefinition))
        {
            return true;
        }

        if (TryLoadSdfFontAsset(normalizedFamily, out var fontAsset))
        {
            fontDefinition = FontDefinition.FromSDFFont(fontAsset);
            s_fontDefinitions[cacheKey] = fontDefinition;
            return true;
        }

        if (!TryLoadFont(normalizedFamily, normalizedSize, out var font))
        {
            return false;
        }

        fontDefinition = FontDefinition.FromFont(font);
        s_fontDefinitions[cacheKey] = fontDefinition;
        return true;
    }

    private static bool TryLoadSdfFontAsset(string familyName, out FontAsset fontAsset)
    {
        fontAsset = null!;

        var normalizedFamily = familyName.Trim();
        if (s_sdfFontAssets.TryGetValue(normalizedFamily, out fontAsset))
        {
            return fontAsset != null;
        }

        fontAsset = LoadBundledSdfFontAsset(normalizedFamily)!;
        if (fontAsset == null)
        {
            return false;
        }

        s_sdfFontAssets[normalizedFamily] = fontAsset;
        return true;
    }

    private static FontAsset? LoadBundledSdfFontAsset(string familyName)
    {
        var normalizedFamily = familyName.Trim();

        if (s_fontResourcePaths.TryGetValue(normalizedFamily, out var resourcePath))
        {
            return Resources.Load<FontAsset>(resourcePath);
        }

        var compactName = normalizedFamily.Replace(" ", string.Empty, StringComparison.Ordinal).Replace("-", string.Empty, StringComparison.Ordinal);
        return Resources.Load<FontAsset>($"BoomHudFonts/{compactName}") ?? Resources.Load<FontAsset>($"BoomHudFonts/{normalizedFamily}");
    }

    private static bool TryLoadFont(string familyName, int pointSize, out Font font)
    {
        font = null!;

        var resourceFont = LoadBundledFont(familyName);
        if (resourceFont != null)
        {
            font = resourceFont;
            return true;
        }

        var fontCandidates = ExpandFontFamilyCandidates(familyName);
        foreach (var candidate in fontCandidates)
        {
            resourceFont = LoadBundledFont(candidate);
            if (resourceFont != null)
            {
                font = resourceFont;
                return true;
            }
        }

        try
        {
            var osFont = Font.CreateDynamicFontFromOSFont(fontCandidates, pointSize);
            if (osFont == null)
            {
                return false;
            }

            font = osFont;
            return true;
        }
        catch
        {
            return false;
        }
    }

    private static Font? LoadBundledFont(string familyName)
    {
        var normalizedFamily = familyName.Trim();

        if (s_fontResourcePaths.TryGetValue(normalizedFamily, out var resourcePath))
        {
            return Resources.Load<Font>(resourcePath);
        }

        var compactName = normalizedFamily.Replace(" ", string.Empty, StringComparison.Ordinal).Replace("-", string.Empty, StringComparison.Ordinal);
        return Resources.Load<Font>($"BoomHudFonts/{compactName}") ?? Resources.Load<Font>($"BoomHudFonts/{normalizedFamily}");
    }

    private static string[] ExpandFontFamilyCandidates(string familyName)
    {
        var rawCandidates = familyName.Split(',');
        var expanded = new List<string>();

        foreach (var rawCandidate in rawCandidates)
        {
            var candidate = rawCandidate.Trim().Trim('\'', '"');
            if (string.IsNullOrWhiteSpace(candidate))
            {
                continue;
            }

            switch (candidate.ToLowerInvariant())
            {
                case "monospace":
                    expanded.Add("Consolas");
                    expanded.Add("Cascadia Mono");
                    expanded.Add("Courier New");
                    expanded.Add("Lucida Console");
                    break;
                case "sans-serif":
                case "sans serif":
                    expanded.Add("Segoe UI");
                    expanded.Add("Arial");
                    break;
                case "serif":
                    expanded.Add("Georgia");
                    expanded.Add("Times New Roman");
                    break;
                default:
                    expanded.Add(candidate);
                    break;
            }
        }

        if (expanded.Count == 0)
        {
            expanded.Add(familyName.Trim());
        }

        return expanded.Distinct(StringComparer.OrdinalIgnoreCase).ToArray();
    }

    private static string ResolveIconText(string value, string? familyName, float pointSize)
    {
        if (!TryResolveFontDefinition(familyName, pointSize, out _))
        {
            return NormalizeIconText(value);
        }

        if (TryResolveIconGlyphText(value, familyName, out var glyphText))
        {
            return glyphText;
        }

        return string.Equals(familyName?.Trim(), "lucide", StringComparison.OrdinalIgnoreCase) ? NormalizeIconText(value) : value;
    }

    private static bool TryResolveIconGlyphText(string value, string? familyName, out string glyphText)
    {
        glyphText = string.Empty;

        if (string.IsNullOrWhiteSpace(familyName))
        {
            return false;
        }

        var normalizedFamily = familyName.Trim();
        if (string.Equals(normalizedFamily, "lucide", StringComparison.OrdinalIgnoreCase) && s_lucideGlyphs.TryGetValue(value, out glyphText))
        {
            return true;
        }

        return false;
    }

    private static string NormalizeIconText(string value)
    {
        return value switch
        {
            "sword" => "†",
            "swords" => "⚔",
            "sparkles" => "✦",
            "wand-sparkles" => "✦",
            "shield" => "⛨",
            "flask-conical" => "⚗",
            "flame" => "✹",
            "moon" => "☾",
            "cross" => "✚",
            _ => value
        };
    }

    private static void ApplyIconLabelStyle(Label label, float boxWidth, float boxHeight, float baselineOffset, bool opticalCentering, string sizeMode, float explicitFontSize)
    {
        var iconSize = explicitFontSize > 0f ? explicitFontSize : string.Equals(sizeMode, "match-height", StringComparison.OrdinalIgnoreCase) ? Mathf.Max(1f, boxHeight) : Mathf.Max(1f, Mathf.Min(boxWidth, boxHeight));
        label.style.unityTextAlign = TextAnchor.MiddleCenter;
        label.style.unityFontStyleAndWeight = FontStyle.Normal;
        label.style.whiteSpace = WhiteSpace.NoWrap;
        label.style.flexShrink = 0;
        label.style.alignItems = opticalCentering ? Align.Center : Align.FlexStart;
        label.style.justifyContent = opticalCentering ? Justify.Center : Justify.FlexStart;
        label.style.overflow = Overflow.Visible;
        label.style.paddingLeft = 0f;
        label.style.paddingTop = 0f;
        label.style.paddingRight = 0f;
        label.style.paddingBottom = 0f;
        label.style.width = boxWidth;
        label.style.height = boxHeight;
        label.style.minWidth = boxWidth;
        label.style.minHeight = boxHeight;
        if (opticalCentering && boxWidth >= 32f && boxHeight >= 32f && Mathf.Approximately(baselineOffset, 0f))
        {
            label.style.marginTop = -1f;
        }
        else if (!Mathf.Approximately(baselineOffset, 0f))
        {
            label.style.marginTop = baselineOffset;
        }
        label.style.fontSize = iconSize;
    }
}
}
