// <auto-generated>
// Generated by BoomHud.Gen.Unity from StardewJournal
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Linq;
using UnityEngine;
using UnityEngine.TextCore.Text;
using UnityEngine.UIElements;

namespace Generated.Hud
{
public sealed class StardewJournalView
{
    private readonly IStardewJournalViewModel? _initialViewModel = null;
    private readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, object?>>? _componentOverrides;
    private IStardewJournalViewModel? _viewModel;

    public VisualElement Root { get; }
    public VisualElement BackdropShade { get; }
    public VisualElement JournalCard { get; }
    public VisualElement RowNewAdvancement { get; }
    public VisualElement RowNewAnimals { get; }
    public VisualElement RowGathering { get; }
    public VisualElement QuestCoin { get; }
    public Label QuestCoinText { get; }
    public Label RowGatheringText { get; }
    public VisualElement RowDoneStarter { get; }
    public VisualElement DoneBadge { get; }
    public Label DoneBadgeText { get; }
    public Label RowDoneStarterText { get; }
    public VisualElement RowIntroductions { get; }
    public VisualElement SimpleGlyph { get; }
    public Label SimpleGlyphText { get; }
    public Label RowIntroductionsText { get; }
    public VisualElement JournalTab { get; }
    public Label JournalTabText { get; }
    public VisualElement CloseButton { get; }
    public Label CloseButtonText { get; }
    public VisualElement SelectionPointer { get; }
    public Label SelectionPointerText { get; }
    private readonly SyntheticContainer8FADC52CView? _rowNewAdvancementComponent;
    private readonly SyntheticContainer8FADC52CView? _rowNewAnimalsComponent;

    public IStardewJournalViewModel? ViewModel
    {
        get => _viewModel;
        set
        {
            if (_viewModel != null)
            {
                _viewModel.PropertyChanged -= OnViewModelPropertyChanged;
            }

            _viewModel = value;
            ApplyComponentViewModels();

            if (_viewModel != null)
            {
                _viewModel.PropertyChanged += OnViewModelPropertyChanged;
            }

            Refresh();
        }
    }

    public StardewJournalView(VisualElement root, IReadOnlyDictionary<string, IReadOnlyDictionary<string, object?>>? componentOverrides = null)
    {
        Root = root as VisualElement ?? throw new ArgumentException("Expected root element type VisualElement.", nameof(root));
        _componentOverrides = componentOverrides;
        BackdropShade = Root.Q<VisualElement>("BackdropShade") ?? throw new InvalidOperationException("Could not find generated element 'BackdropShade'.");
        JournalCard = Root.Q<VisualElement>("JournalCard") ?? throw new InvalidOperationException("Could not find generated element 'JournalCard'.");
        var rowNewAdvancementPlaceholder = Root.Q<VisualElement>("RowNewAdvancement") ?? throw new InvalidOperationException("Could not find generated component placeholder 'RowNewAdvancement'.");
        _rowNewAdvancementComponent = SyntheticContainer8FADC52CView.Attach(rowNewAdvancementPlaceholder, null);
        RowNewAdvancement = _rowNewAdvancementComponent.Root;
        var rowNewAnimalsPlaceholder = Root.Q<VisualElement>("RowNewAnimals") ?? throw new InvalidOperationException("Could not find generated component placeholder 'RowNewAnimals'.");
        _rowNewAnimalsComponent = SyntheticContainer8FADC52CView.Attach(rowNewAnimalsPlaceholder, new Dictionary<string, IReadOnlyDictionary<string, object?>>(StringComparer.Ordinal)
        {
            ["$/1"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "RAISING ANIMALS"
            }
        });
        RowNewAnimals = _rowNewAnimalsComponent.Root;
        RowGathering = Root.Q<VisualElement>("RowGathering") ?? throw new InvalidOperationException("Could not find generated element 'RowGathering'.");
        QuestCoin = Root.Q<VisualElement>("QuestCoin") ?? throw new InvalidOperationException("Could not find generated element 'QuestCoin'.");
        QuestCoinText = Root.Q<Label>("QuestCoinText") ?? throw new InvalidOperationException("Could not find generated element 'QuestCoinText'.");
        RowGatheringText = Root.Q<Label>("RowGatheringText") ?? throw new InvalidOperationException("Could not find generated element 'RowGatheringText'.");
        RowDoneStarter = Root.Q<VisualElement>("RowDoneStarter") ?? throw new InvalidOperationException("Could not find generated element 'RowDoneStarter'.");
        DoneBadge = Root.Q<VisualElement>("DoneBadge") ?? throw new InvalidOperationException("Could not find generated element 'DoneBadge'.");
        DoneBadgeText = Root.Q<Label>("DoneBadgeText") ?? throw new InvalidOperationException("Could not find generated element 'DoneBadgeText'.");
        RowDoneStarterText = Root.Q<Label>("RowDoneStarterText") ?? throw new InvalidOperationException("Could not find generated element 'RowDoneStarterText'.");
        RowIntroductions = Root.Q<VisualElement>("RowIntroductions") ?? throw new InvalidOperationException("Could not find generated element 'RowIntroductions'.");
        SimpleGlyph = Root.Q<VisualElement>("SimpleGlyph") ?? throw new InvalidOperationException("Could not find generated element 'SimpleGlyph'.");
        SimpleGlyphText = Root.Q<Label>("SimpleGlyphText") ?? throw new InvalidOperationException("Could not find generated element 'SimpleGlyphText'.");
        RowIntroductionsText = Root.Q<Label>("RowIntroductionsText") ?? throw new InvalidOperationException("Could not find generated element 'RowIntroductionsText'.");
        JournalTab = Root.Q<VisualElement>("JournalTab") ?? throw new InvalidOperationException("Could not find generated element 'JournalTab'.");
        JournalTabText = Root.Q<Label>("JournalTabText") ?? throw new InvalidOperationException("Could not find generated element 'JournalTabText'.");
        CloseButton = Root.Q<VisualElement>("CloseButton") ?? throw new InvalidOperationException("Could not find generated element 'CloseButton'.");
        CloseButtonText = Root.Q<Label>("CloseButtonText") ?? throw new InvalidOperationException("Could not find generated element 'CloseButtonText'.");
        SelectionPointer = Root.Q<VisualElement>("SelectionPointer") ?? throw new InvalidOperationException("Could not find generated element 'SelectionPointer'.");
        SelectionPointerText = Root.Q<Label>("SelectionPointerText") ?? throw new InvalidOperationException("Could not find generated element 'SelectionPointerText'.");

        ApplyStaticValues();
        ApplyInstanceOverrides();
        ViewModel = _initialViewModel;
    }

    public void Refresh()
    {
        if (_viewModel == null)
        {
            return;
        }

    }

    private void ApplyInstanceOverrides()
    {
        if (_componentOverrides == null)
        {
            return;
        }

        if (TryGetComponentOverrideValue("$/1/2/0/0", "Text", out var componentOverrideValue0))
        {
            QuestCoinText.text = AsString(componentOverrideValue0);
            ApplyTextLabelStyle(QuestCoinText, false);
        }
        if (TryGetComponentOverrideValue("$/1/2/1", "Text", out var componentOverrideValue1))
        {
            RowGatheringText.text = AsString(componentOverrideValue1);
            ApplyTextLabelStyle(RowGatheringText, false);
        }
        if (TryGetComponentOverrideValue("$/1/3/0/0", "Text", out var componentOverrideValue2))
        {
            DoneBadgeText.text = AsString(componentOverrideValue2);
            ApplyTextLabelStyle(DoneBadgeText, false);
        }
        if (TryGetComponentOverrideValue("$/1/3/1", "Text", out var componentOverrideValue3))
        {
            RowDoneStarterText.text = AsString(componentOverrideValue3);
            ApplyTextLabelStyle(RowDoneStarterText, false);
        }
        if (TryGetComponentOverrideValue("$/1/4/0/0", "Text", out var componentOverrideValue4))
        {
            SimpleGlyphText.text = AsString(componentOverrideValue4);
            ApplyTextLabelStyle(SimpleGlyphText, false);
        }
        if (TryGetComponentOverrideValue("$/1/4/1", "Text", out var componentOverrideValue5))
        {
            RowIntroductionsText.text = AsString(componentOverrideValue5);
            ApplyTextLabelStyle(RowIntroductionsText, false);
        }
        if (TryGetComponentOverrideValue("$/2/0", "Text", out var componentOverrideValue6))
        {
            JournalTabText.text = AsString(componentOverrideValue6);
            ApplyTextLabelStyle(JournalTabText, false);
        }
        if (TryGetComponentOverrideValue("$/3/0", "Text", out var componentOverrideValue7))
        {
            CloseButtonText.text = AsString(componentOverrideValue7);
            ApplyTextLabelStyle(CloseButtonText, false);
        }
        if (TryGetComponentOverrideValue("$/4/0", "Text", out var componentOverrideValue8))
        {
            SelectionPointerText.text = AsString(componentOverrideValue8);
            ApplyTextLabelStyle(SelectionPointerText, false);
        }
    }

    private void ApplyStaticValues()
    {
        Root.style.marginTop = ParseStyleFloat("0px");
        Root.style.marginRight = ParseStyleFloat("0px");
        Root.style.marginBottom = ParseStyleFloat("0px");
        Root.style.marginLeft = ParseStyleFloat("0px");
        Root.style.flexDirection = ParseFlexDirection("column");
        Root.style.width = ParseStyleLength("1920px");
        Root.style.height = ParseStyleLength("1080px");
        Root.style.paddingTop = ParseStyleFloat("0px");
        Root.style.paddingRight = ParseStyleFloat("0px");
        Root.style.paddingBottom = ParseStyleFloat("0px");
        Root.style.paddingLeft = ParseStyleFloat("0px");
        Root.style.alignItems = ParseAlign("flex-start");
        Root.style.justifyContent = ParseJustify("flex-start");
        Root.style.display = DisplayStyle.Flex;
        Root.SetEnabled(true);
        Root.style.color = ParseStyleColor("#203624", null);
        Root.style.backgroundColor = ParseStyleColor("#203624", null);
        BackdropShade.style.position = ParsePosition("absolute");
        BackdropShade.style.left = ParseStyleLength("0px");
        BackdropShade.style.top = ParseStyleLength("0px");
        BackdropShade.style.marginTop = ParseStyleFloat("0px");
        BackdropShade.style.marginRight = ParseStyleFloat("0px");
        BackdropShade.style.marginBottom = ParseStyleFloat("0px");
        BackdropShade.style.marginLeft = ParseStyleFloat("0px");
        BackdropShade.style.flexDirection = ParseFlexDirection("column");
        BackdropShade.style.width = ParseStyleLength("1920px");
        BackdropShade.style.height = ParseStyleLength("1080px");
        BackdropShade.style.paddingTop = ParseStyleFloat("0px");
        BackdropShade.style.paddingRight = ParseStyleFloat("0px");
        BackdropShade.style.paddingBottom = ParseStyleFloat("0px");
        BackdropShade.style.paddingLeft = ParseStyleFloat("0px");
        BackdropShade.style.alignItems = ParseAlign("flex-start");
        BackdropShade.style.justifyContent = ParseJustify("flex-start");
        BackdropShade.style.display = DisplayStyle.Flex;
        BackdropShade.SetEnabled(true);
        BackdropShade.style.color = ParseStyleColor("#132116CC", null);
        BackdropShade.style.backgroundColor = ParseStyleColor("#132116CC", null);
        JournalCard.style.position = ParsePosition("absolute");
        JournalCard.style.left = ParseStyleLength("666px");
        JournalCard.style.top = ParseStyleLength("194px");
        JournalCard.style.marginTop = ParseStyleFloat("0px");
        JournalCard.style.marginRight = ParseStyleFloat("0px");
        JournalCard.style.marginBottom = ParseStyleFloat("0px");
        JournalCard.style.marginLeft = ParseStyleFloat("0px");
        JournalCard.style.flexDirection = ParseFlexDirection("column");
        JournalCard.style.width = ParseStyleLength("588px");
        JournalCard.style.height = ParseStyleLength("482px");
        JournalCard.style.paddingTop = ParseStyleFloat("6px");
        JournalCard.style.paddingRight = ParseStyleFloat("6px");
        JournalCard.style.paddingBottom = ParseStyleFloat("6px");
        JournalCard.style.paddingLeft = ParseStyleFloat("6px");
        JournalCard.style.alignItems = ParseAlign("flex-start");
        JournalCard.style.justifyContent = ParseJustify("flex-start");
        JournalCard.style.display = DisplayStyle.Flex;
        JournalCard.SetEnabled(true);
        JournalCard.style.color = ParseStyleColor("#F0BD6B", null);
        JournalCard.style.backgroundColor = ParseStyleColor("#F0BD6B", null);
        JournalCard.style.borderLeftWidth = 8f;
        JournalCard.style.borderRightWidth = 8f;
        JournalCard.style.borderTopWidth = 8f;
        JournalCard.style.borderBottomWidth = 8f;
        JournalCard.style.borderLeftColor = ParseStyleColor("#7D3E14", null);
        JournalCard.style.borderRightColor = ParseStyleColor("#7D3E14", null);
        JournalCard.style.borderTopColor = ParseStyleColor("#7D3E14", null);
        JournalCard.style.borderBottomColor = ParseStyleColor("#7D3E14", null);
        RowNewAdvancement.style.flexShrink = ParseStyleFloat("0");
        RowNewAdvancement.style.display = DisplayStyle.Flex;
        RowNewAdvancement.SetEnabled(true);
        RowNewAnimals.style.marginTop = ParseStyleFloat("8px");
        RowNewAnimals.style.marginRight = ParseStyleFloat("0px");
        RowNewAnimals.style.marginBottom = ParseStyleFloat("0px");
        RowNewAnimals.style.marginLeft = ParseStyleFloat("0px");
        RowNewAnimals.style.flexShrink = ParseStyleFloat("0");
        RowNewAnimals.style.display = DisplayStyle.Flex;
        RowNewAnimals.SetEnabled(true);
        RowGathering.style.marginTop = ParseStyleFloat("8px");
        RowGathering.style.marginRight = ParseStyleFloat("0px");
        RowGathering.style.marginBottom = ParseStyleFloat("0px");
        RowGathering.style.marginLeft = ParseStyleFloat("0px");
        RowGathering.style.flexShrink = ParseStyleFloat("0");
        RowGathering.style.flexDirection = ParseFlexDirection("row");
        RowGathering.style.alignSelf = ParseAlign("stretch");
        RowGathering.style.height = ParseStyleLength("66px");
        RowGathering.style.paddingTop = ParseStyleFloat("8px");
        RowGathering.style.paddingRight = ParseStyleFloat("8px");
        RowGathering.style.paddingBottom = ParseStyleFloat("8px");
        RowGathering.style.paddingLeft = ParseStyleFloat("8px");
        RowGathering.style.alignItems = ParseAlign("flex-start");
        RowGathering.style.justifyContent = ParseJustify("flex-start");
        RowGathering.style.display = DisplayStyle.Flex;
        RowGathering.SetEnabled(true);
        RowGathering.style.color = ParseStyleColor("#F8D89A", null);
        RowGathering.style.backgroundColor = ParseStyleColor("#F8D89A", null);
        RowGathering.style.borderLeftWidth = 4f;
        RowGathering.style.borderRightWidth = 4f;
        RowGathering.style.borderTopWidth = 4f;
        RowGathering.style.borderBottomWidth = 4f;
        RowGathering.style.borderLeftColor = ParseStyleColor("#7D3E14", null);
        RowGathering.style.borderRightColor = ParseStyleColor("#7D3E14", null);
        RowGathering.style.borderTopColor = ParseStyleColor("#7D3E14", null);
        RowGathering.style.borderBottomColor = ParseStyleColor("#7D3E14", null);
        QuestCoin.style.marginTop = ParseStyleFloat("0px");
        QuestCoin.style.marginRight = ParseStyleFloat("0px");
        QuestCoin.style.marginBottom = ParseStyleFloat("0px");
        QuestCoin.style.marginLeft = ParseStyleFloat("0px");
        QuestCoin.style.flexShrink = ParseStyleFloat("0");
        QuestCoin.style.flexDirection = ParseFlexDirection("column");
        QuestCoin.style.width = ParseStyleLength("40px");
        QuestCoin.style.height = ParseStyleLength("40px");
        QuestCoin.style.paddingTop = ParseStyleFloat("0px");
        QuestCoin.style.paddingRight = ParseStyleFloat("0px");
        QuestCoin.style.paddingBottom = ParseStyleFloat("0px");
        QuestCoin.style.paddingLeft = ParseStyleFloat("0px");
        QuestCoin.style.alignItems = ParseAlign("center");
        QuestCoin.style.justifyContent = ParseJustify("center");
        QuestCoin.style.display = DisplayStyle.Flex;
        QuestCoin.SetEnabled(true);
        QuestCoin.style.color = ParseStyleColor("#E0B041", null);
        QuestCoin.style.backgroundColor = ParseStyleColor("#E0B041", null);
        QuestCoinText.style.marginTop = ParseStyleFloat("0px");
        QuestCoinText.style.marginRight = ParseStyleFloat("0px");
        QuestCoinText.style.marginBottom = ParseStyleFloat("0px");
        QuestCoinText.style.marginLeft = ParseStyleFloat("0px");
        QuestCoinText.style.flexDirection = ParseFlexDirection("column");
        QuestCoinText.style.paddingTop = ParseStyleFloat("0px");
        QuestCoinText.style.paddingRight = ParseStyleFloat("0px");
        QuestCoinText.style.paddingBottom = ParseStyleFloat("0px");
        QuestCoinText.style.paddingLeft = ParseStyleFloat("0px");
        QuestCoinText.style.alignItems = ParseAlign("flex-start");
        QuestCoinText.style.justifyContent = ParseJustify("flex-start");
        QuestCoinText.text = "$";
        ApplyTextLabelStyle(QuestCoinText, false);
        QuestCoinText.style.display = DisplayStyle.Flex;
        QuestCoinText.SetEnabled(true);
        ApplyFontFamily(QuestCoinText, "Press Start 2P", 12f);
        QuestCoinText.style.color = ParseStyleColor("#7D3E14", null);
        QuestCoinText.style.fontSize = 12f;
        QuestCoinText.style.unityFontStyleAndWeight = UnityEngine.FontStyle.Normal;
        RowGatheringText.style.marginTop = ParseStyleFloat("0px");
        RowGatheringText.style.marginRight = ParseStyleFloat("0px");
        RowGatheringText.style.marginBottom = ParseStyleFloat("0px");
        RowGatheringText.style.marginLeft = ParseStyleFloat("14px");
        RowGatheringText.style.flexShrink = ParseStyleFloat("0");
        RowGatheringText.style.flexDirection = ParseFlexDirection("column");
        RowGatheringText.style.paddingTop = ParseStyleFloat("0px");
        RowGatheringText.style.paddingRight = ParseStyleFloat("0px");
        RowGatheringText.style.paddingBottom = ParseStyleFloat("0px");
        RowGatheringText.style.paddingLeft = ParseStyleFloat("0px");
        RowGatheringText.style.alignItems = ParseAlign("flex-start");
        RowGatheringText.style.justifyContent = ParseJustify("flex-start");
        RowGatheringText.text = "GATHERING";
        ApplyTextLabelStyle(RowGatheringText, false);
        RowGatheringText.style.display = DisplayStyle.Flex;
        RowGatheringText.SetEnabled(true);
        ApplyFontFamily(RowGatheringText, "Press Start 2P", 12f);
        RowGatheringText.style.color = ParseStyleColor("#5A2A10", null);
        RowGatheringText.style.fontSize = 12f;
        RowGatheringText.style.unityFontStyleAndWeight = UnityEngine.FontStyle.Normal;
        RowDoneStarter.style.marginTop = ParseStyleFloat("8px");
        RowDoneStarter.style.marginRight = ParseStyleFloat("0px");
        RowDoneStarter.style.marginBottom = ParseStyleFloat("0px");
        RowDoneStarter.style.marginLeft = ParseStyleFloat("0px");
        RowDoneStarter.style.flexShrink = ParseStyleFloat("0");
        RowDoneStarter.style.flexDirection = ParseFlexDirection("row");
        RowDoneStarter.style.alignSelf = ParseAlign("stretch");
        RowDoneStarter.style.height = ParseStyleLength("66px");
        RowDoneStarter.style.paddingTop = ParseStyleFloat("8px");
        RowDoneStarter.style.paddingRight = ParseStyleFloat("8px");
        RowDoneStarter.style.paddingBottom = ParseStyleFloat("8px");
        RowDoneStarter.style.paddingLeft = ParseStyleFloat("8px");
        RowDoneStarter.style.alignItems = ParseAlign("flex-start");
        RowDoneStarter.style.justifyContent = ParseJustify("flex-start");
        RowDoneStarter.style.display = DisplayStyle.Flex;
        RowDoneStarter.SetEnabled(true);
        RowDoneStarter.style.color = ParseStyleColor("#F8D89A", null);
        RowDoneStarter.style.backgroundColor = ParseStyleColor("#F8D89A", null);
        RowDoneStarter.style.borderLeftWidth = 4f;
        RowDoneStarter.style.borderRightWidth = 4f;
        RowDoneStarter.style.borderTopWidth = 4f;
        RowDoneStarter.style.borderBottomWidth = 4f;
        RowDoneStarter.style.borderLeftColor = ParseStyleColor("#7D3E14", null);
        RowDoneStarter.style.borderRightColor = ParseStyleColor("#7D3E14", null);
        RowDoneStarter.style.borderTopColor = ParseStyleColor("#7D3E14", null);
        RowDoneStarter.style.borderBottomColor = ParseStyleColor("#7D3E14", null);
        DoneBadge.style.marginTop = ParseStyleFloat("0px");
        DoneBadge.style.marginRight = ParseStyleFloat("0px");
        DoneBadge.style.marginBottom = ParseStyleFloat("0px");
        DoneBadge.style.marginLeft = ParseStyleFloat("0px");
        DoneBadge.style.flexShrink = ParseStyleFloat("0");
        DoneBadge.style.flexDirection = ParseFlexDirection("column");
        DoneBadge.style.width = ParseStyleLength("110px");
        DoneBadge.style.height = ParseStyleLength("40px");
        DoneBadge.style.paddingTop = ParseStyleFloat("0px");
        DoneBadge.style.paddingRight = ParseStyleFloat("0px");
        DoneBadge.style.paddingBottom = ParseStyleFloat("0px");
        DoneBadge.style.paddingLeft = ParseStyleFloat("0px");
        DoneBadge.style.alignItems = ParseAlign("center");
        DoneBadge.style.justifyContent = ParseJustify("center");
        DoneBadge.style.display = DisplayStyle.Flex;
        DoneBadge.SetEnabled(true);
        DoneBadge.style.color = ParseStyleColor("#1BB841", null);
        DoneBadge.style.backgroundColor = ParseStyleColor("#1BB841", null);
        DoneBadgeText.style.marginTop = ParseStyleFloat("0px");
        DoneBadgeText.style.marginRight = ParseStyleFloat("0px");
        DoneBadgeText.style.marginBottom = ParseStyleFloat("0px");
        DoneBadgeText.style.marginLeft = ParseStyleFloat("0px");
        DoneBadgeText.style.flexDirection = ParseFlexDirection("column");
        DoneBadgeText.style.paddingTop = ParseStyleFloat("0px");
        DoneBadgeText.style.paddingRight = ParseStyleFloat("0px");
        DoneBadgeText.style.paddingBottom = ParseStyleFloat("0px");
        DoneBadgeText.style.paddingLeft = ParseStyleFloat("0px");
        DoneBadgeText.style.alignItems = ParseAlign("flex-start");
        DoneBadgeText.style.justifyContent = ParseJustify("flex-start");
        DoneBadgeText.text = "DONE";
        ApplyTextLabelStyle(DoneBadgeText, false);
        DoneBadgeText.style.display = DisplayStyle.Flex;
        DoneBadgeText.SetEnabled(true);
        ApplyFontFamily(DoneBadgeText, "Press Start 2P", 9f);
        DoneBadgeText.style.color = ParseStyleColor("#FFFFFF", null);
        DoneBadgeText.style.fontSize = 9f;
        DoneBadgeText.style.unityFontStyleAndWeight = UnityEngine.FontStyle.Normal;
        RowDoneStarterText.style.marginTop = ParseStyleFloat("0px");
        RowDoneStarterText.style.marginRight = ParseStyleFloat("0px");
        RowDoneStarterText.style.marginBottom = ParseStyleFloat("0px");
        RowDoneStarterText.style.marginLeft = ParseStyleFloat("14px");
        RowDoneStarterText.style.flexShrink = ParseStyleFloat("0");
        RowDoneStarterText.style.flexDirection = ParseFlexDirection("column");
        RowDoneStarterText.style.paddingTop = ParseStyleFloat("0px");
        RowDoneStarterText.style.paddingRight = ParseStyleFloat("0px");
        RowDoneStarterText.style.paddingBottom = ParseStyleFloat("0px");
        RowDoneStarterText.style.paddingLeft = ParseStyleFloat("0px");
        RowDoneStarterText.style.alignItems = ParseAlign("flex-start");
        RowDoneStarterText.style.justifyContent = ParseJustify("flex-start");
        RowDoneStarterText.text = "GETTING STARTED";
        ApplyTextLabelStyle(RowDoneStarterText, false);
        RowDoneStarterText.style.display = DisplayStyle.Flex;
        RowDoneStarterText.SetEnabled(true);
        ApplyFontFamily(RowDoneStarterText, "Press Start 2P", 12f);
        RowDoneStarterText.style.color = ParseStyleColor("#5A2A10", null);
        RowDoneStarterText.style.fontSize = 12f;
        RowDoneStarterText.style.unityFontStyleAndWeight = UnityEngine.FontStyle.Normal;
        RowIntroductions.style.marginTop = ParseStyleFloat("8px");
        RowIntroductions.style.marginRight = ParseStyleFloat("0px");
        RowIntroductions.style.marginBottom = ParseStyleFloat("0px");
        RowIntroductions.style.marginLeft = ParseStyleFloat("0px");
        RowIntroductions.style.flexShrink = ParseStyleFloat("0");
        RowIntroductions.style.flexDirection = ParseFlexDirection("row");
        RowIntroductions.style.alignSelf = ParseAlign("stretch");
        RowIntroductions.style.height = ParseStyleLength("66px");
        RowIntroductions.style.paddingTop = ParseStyleFloat("8px");
        RowIntroductions.style.paddingRight = ParseStyleFloat("8px");
        RowIntroductions.style.paddingBottom = ParseStyleFloat("8px");
        RowIntroductions.style.paddingLeft = ParseStyleFloat("8px");
        RowIntroductions.style.alignItems = ParseAlign("flex-start");
        RowIntroductions.style.justifyContent = ParseJustify("flex-start");
        RowIntroductions.style.display = DisplayStyle.Flex;
        RowIntroductions.SetEnabled(true);
        RowIntroductions.style.color = ParseStyleColor("#F8D89A", null);
        RowIntroductions.style.backgroundColor = ParseStyleColor("#F8D89A", null);
        RowIntroductions.style.borderLeftWidth = 4f;
        RowIntroductions.style.borderRightWidth = 4f;
        RowIntroductions.style.borderTopWidth = 4f;
        RowIntroductions.style.borderBottomWidth = 4f;
        RowIntroductions.style.borderLeftColor = ParseStyleColor("#7D3E14", null);
        RowIntroductions.style.borderRightColor = ParseStyleColor("#7D3E14", null);
        RowIntroductions.style.borderTopColor = ParseStyleColor("#7D3E14", null);
        RowIntroductions.style.borderBottomColor = ParseStyleColor("#7D3E14", null);
        SimpleGlyph.style.marginTop = ParseStyleFloat("0px");
        SimpleGlyph.style.marginRight = ParseStyleFloat("0px");
        SimpleGlyph.style.marginBottom = ParseStyleFloat("0px");
        SimpleGlyph.style.marginLeft = ParseStyleFloat("0px");
        SimpleGlyph.style.flexShrink = ParseStyleFloat("0");
        SimpleGlyph.style.flexDirection = ParseFlexDirection("column");
        SimpleGlyph.style.width = ParseStyleLength("34px");
        SimpleGlyph.style.height = ParseStyleLength("40px");
        SimpleGlyph.style.paddingTop = ParseStyleFloat("0px");
        SimpleGlyph.style.paddingRight = ParseStyleFloat("0px");
        SimpleGlyph.style.paddingBottom = ParseStyleFloat("0px");
        SimpleGlyph.style.paddingLeft = ParseStyleFloat("0px");
        SimpleGlyph.style.alignItems = ParseAlign("center");
        SimpleGlyph.style.justifyContent = ParseJustify("center");
        SimpleGlyph.style.display = DisplayStyle.Flex;
        SimpleGlyph.SetEnabled(true);
        SimpleGlyph.style.color = ParseStyleColor("#F8D89A", null);
        SimpleGlyph.style.backgroundColor = ParseStyleColor("#F8D89A", null);
        SimpleGlyphText.style.marginTop = ParseStyleFloat("0px");
        SimpleGlyphText.style.marginRight = ParseStyleFloat("0px");
        SimpleGlyphText.style.marginBottom = ParseStyleFloat("0px");
        SimpleGlyphText.style.marginLeft = ParseStyleFloat("0px");
        SimpleGlyphText.style.flexDirection = ParseFlexDirection("column");
        SimpleGlyphText.style.paddingTop = ParseStyleFloat("0px");
        SimpleGlyphText.style.paddingRight = ParseStyleFloat("0px");
        SimpleGlyphText.style.paddingBottom = ParseStyleFloat("0px");
        SimpleGlyphText.style.paddingLeft = ParseStyleFloat("0px");
        SimpleGlyphText.style.alignItems = ParseAlign("flex-start");
        SimpleGlyphText.style.justifyContent = ParseJustify("flex-start");
        SimpleGlyphText.text = "!";
        ApplyTextLabelStyle(SimpleGlyphText, false);
        SimpleGlyphText.style.display = DisplayStyle.Flex;
        SimpleGlyphText.SetEnabled(true);
        ApplyFontFamily(SimpleGlyphText, "Press Start 2P", 12f);
        SimpleGlyphText.style.color = ParseStyleColor("#E9A426", null);
        SimpleGlyphText.style.fontSize = 12f;
        SimpleGlyphText.style.unityFontStyleAndWeight = UnityEngine.FontStyle.Normal;
        RowIntroductionsText.style.marginTop = ParseStyleFloat("0px");
        RowIntroductionsText.style.marginRight = ParseStyleFloat("0px");
        RowIntroductionsText.style.marginBottom = ParseStyleFloat("0px");
        RowIntroductionsText.style.marginLeft = ParseStyleFloat("14px");
        RowIntroductionsText.style.flexShrink = ParseStyleFloat("0");
        RowIntroductionsText.style.flexDirection = ParseFlexDirection("column");
        RowIntroductionsText.style.paddingTop = ParseStyleFloat("0px");
        RowIntroductionsText.style.paddingRight = ParseStyleFloat("0px");
        RowIntroductionsText.style.paddingBottom = ParseStyleFloat("0px");
        RowIntroductionsText.style.paddingLeft = ParseStyleFloat("0px");
        RowIntroductionsText.style.alignItems = ParseAlign("flex-start");
        RowIntroductionsText.style.justifyContent = ParseJustify("flex-start");
        RowIntroductionsText.text = "INTRODUCTIONS";
        ApplyTextLabelStyle(RowIntroductionsText, false);
        RowIntroductionsText.style.display = DisplayStyle.Flex;
        RowIntroductionsText.SetEnabled(true);
        ApplyFontFamily(RowIntroductionsText, "Press Start 2P", 12f);
        RowIntroductionsText.style.color = ParseStyleColor("#5A2A10", null);
        RowIntroductionsText.style.fontSize = 12f;
        RowIntroductionsText.style.unityFontStyleAndWeight = UnityEngine.FontStyle.Normal;
        JournalTab.style.position = ParsePosition("absolute");
        JournalTab.style.left = ParseStyleLength("816px");
        JournalTab.style.top = ParseStyleLength("154px");
        JournalTab.style.marginTop = ParseStyleFloat("0px");
        JournalTab.style.marginRight = ParseStyleFloat("0px");
        JournalTab.style.marginBottom = ParseStyleFloat("0px");
        JournalTab.style.marginLeft = ParseStyleFloat("0px");
        JournalTab.style.flexDirection = ParseFlexDirection("column");
        JournalTab.style.width = ParseStyleLength("290px");
        JournalTab.style.height = ParseStyleLength("54px");
        JournalTab.style.paddingTop = ParseStyleFloat("0px");
        JournalTab.style.paddingRight = ParseStyleFloat("0px");
        JournalTab.style.paddingBottom = ParseStyleFloat("0px");
        JournalTab.style.paddingLeft = ParseStyleFloat("0px");
        JournalTab.style.alignItems = ParseAlign("center");
        JournalTab.style.justifyContent = ParseJustify("center");
        JournalTab.style.display = DisplayStyle.Flex;
        JournalTab.SetEnabled(true);
        JournalTab.style.color = ParseStyleColor("#F8D89A", null);
        JournalTab.style.backgroundColor = ParseStyleColor("#F8D89A", null);
        JournalTab.style.borderLeftWidth = 4f;
        JournalTab.style.borderRightWidth = 4f;
        JournalTab.style.borderTopWidth = 4f;
        JournalTab.style.borderBottomWidth = 4f;
        JournalTab.style.borderLeftColor = ParseStyleColor("#7D3E14", null);
        JournalTab.style.borderRightColor = ParseStyleColor("#7D3E14", null);
        JournalTab.style.borderTopColor = ParseStyleColor("#7D3E14", null);
        JournalTab.style.borderBottomColor = ParseStyleColor("#7D3E14", null);
        JournalTabText.style.marginTop = ParseStyleFloat("0px");
        JournalTabText.style.marginRight = ParseStyleFloat("0px");
        JournalTabText.style.marginBottom = ParseStyleFloat("0px");
        JournalTabText.style.marginLeft = ParseStyleFloat("0px");
        JournalTabText.style.flexDirection = ParseFlexDirection("column");
        JournalTabText.style.paddingTop = ParseStyleFloat("0px");
        JournalTabText.style.paddingRight = ParseStyleFloat("0px");
        JournalTabText.style.paddingBottom = ParseStyleFloat("0px");
        JournalTabText.style.paddingLeft = ParseStyleFloat("0px");
        JournalTabText.style.alignItems = ParseAlign("flex-start");
        JournalTabText.style.justifyContent = ParseJustify("flex-start");
        JournalTabText.text = "JOURNAL";
        ApplyTextLabelStyle(JournalTabText, false);
        JournalTabText.style.display = DisplayStyle.Flex;
        JournalTabText.SetEnabled(true);
        ApplyFontFamily(JournalTabText, "Press Start 2P", 14f);
        JournalTabText.style.color = ParseStyleColor("#7D3E14", null);
        JournalTabText.style.fontSize = 14f;
        JournalTabText.style.unityFontStyleAndWeight = UnityEngine.FontStyle.Normal;
        CloseButton.style.position = ParsePosition("absolute");
        CloseButton.style.left = ParseStyleLength("1224px");
        CloseButton.style.top = ParseStyleLength("210px");
        CloseButton.style.marginTop = ParseStyleFloat("0px");
        CloseButton.style.marginRight = ParseStyleFloat("0px");
        CloseButton.style.marginBottom = ParseStyleFloat("0px");
        CloseButton.style.marginLeft = ParseStyleFloat("0px");
        CloseButton.style.flexDirection = ParseFlexDirection("column");
        CloseButton.style.width = ParseStyleLength("30px");
        CloseButton.style.height = ParseStyleLength("30px");
        CloseButton.style.paddingTop = ParseStyleFloat("0px");
        CloseButton.style.paddingRight = ParseStyleFloat("0px");
        CloseButton.style.paddingBottom = ParseStyleFloat("0px");
        CloseButton.style.paddingLeft = ParseStyleFloat("0px");
        CloseButton.style.alignItems = ParseAlign("center");
        CloseButton.style.justifyContent = ParseJustify("center");
        CloseButton.style.display = DisplayStyle.Flex;
        CloseButton.SetEnabled(true);
        CloseButton.style.color = ParseStyleColor("#D84A28", null);
        CloseButton.style.backgroundColor = ParseStyleColor("#D84A28", null);
        CloseButtonText.style.marginTop = ParseStyleFloat("0px");
        CloseButtonText.style.marginRight = ParseStyleFloat("0px");
        CloseButtonText.style.marginBottom = ParseStyleFloat("0px");
        CloseButtonText.style.marginLeft = ParseStyleFloat("0px");
        CloseButtonText.style.flexDirection = ParseFlexDirection("column");
        CloseButtonText.style.paddingTop = ParseStyleFloat("0px");
        CloseButtonText.style.paddingRight = ParseStyleFloat("0px");
        CloseButtonText.style.paddingBottom = ParseStyleFloat("0px");
        CloseButtonText.style.paddingLeft = ParseStyleFloat("0px");
        CloseButtonText.style.alignItems = ParseAlign("flex-start");
        CloseButtonText.style.justifyContent = ParseJustify("flex-start");
        CloseButtonText.text = "X";
        ApplyTextLabelStyle(CloseButtonText, false);
        CloseButtonText.style.display = DisplayStyle.Flex;
        CloseButtonText.SetEnabled(true);
        ApplyFontFamily(CloseButtonText, "Press Start 2P", 10f);
        CloseButtonText.style.color = ParseStyleColor("#FFFFFF", null);
        CloseButtonText.style.fontSize = 10f;
        CloseButtonText.style.unityFontStyleAndWeight = UnityEngine.FontStyle.Normal;
        SelectionPointer.style.position = ParsePosition("absolute");
        SelectionPointer.style.left = ParseStyleLength("612px");
        SelectionPointer.style.top = ParseStyleLength("336px");
        SelectionPointer.style.marginTop = ParseStyleFloat("0px");
        SelectionPointer.style.marginRight = ParseStyleFloat("0px");
        SelectionPointer.style.marginBottom = ParseStyleFloat("0px");
        SelectionPointer.style.marginLeft = ParseStyleFloat("0px");
        SelectionPointer.style.flexDirection = ParseFlexDirection("column");
        SelectionPointer.style.width = ParseStyleLength("34px");
        SelectionPointer.style.height = ParseStyleLength("52px");
        SelectionPointer.style.paddingTop = ParseStyleFloat("0px");
        SelectionPointer.style.paddingRight = ParseStyleFloat("0px");
        SelectionPointer.style.paddingBottom = ParseStyleFloat("0px");
        SelectionPointer.style.paddingLeft = ParseStyleFloat("0px");
        SelectionPointer.style.alignItems = ParseAlign("center");
        SelectionPointer.style.justifyContent = ParseJustify("center");
        SelectionPointer.style.display = DisplayStyle.Flex;
        SelectionPointer.SetEnabled(true);
        SelectionPointer.style.color = ParseStyleColor("#F4F1E6", null);
        SelectionPointer.style.backgroundColor = ParseStyleColor("#F4F1E6", null);
        SelectionPointerText.style.marginTop = ParseStyleFloat("0px");
        SelectionPointerText.style.marginRight = ParseStyleFloat("0px");
        SelectionPointerText.style.marginBottom = ParseStyleFloat("0px");
        SelectionPointerText.style.marginLeft = ParseStyleFloat("0px");
        SelectionPointerText.style.flexDirection = ParseFlexDirection("column");
        SelectionPointerText.style.paddingTop = ParseStyleFloat("0px");
        SelectionPointerText.style.paddingRight = ParseStyleFloat("0px");
        SelectionPointerText.style.paddingBottom = ParseStyleFloat("0px");
        SelectionPointerText.style.paddingLeft = ParseStyleFloat("0px");
        SelectionPointerText.style.alignItems = ParseAlign("flex-start");
        SelectionPointerText.style.justifyContent = ParseJustify("flex-start");
        SelectionPointerText.text = ">";
        ApplyTextLabelStyle(SelectionPointerText, false);
        SelectionPointerText.style.display = DisplayStyle.Flex;
        SelectionPointerText.SetEnabled(true);
        ApplyFontFamily(SelectionPointerText, "Press Start 2P", 18f);
        SelectionPointerText.style.color = ParseStyleColor("#D5C9B0", null);
        SelectionPointerText.style.fontSize = 18f;
        SelectionPointerText.style.unityFontStyleAndWeight = UnityEngine.FontStyle.Normal;
    }

    private void ApplyComponentViewModels()
    {
        if (_rowNewAdvancementComponent != null)
        {
            _rowNewAdvancementComponent.ViewModel = _viewModel is ISyntheticContainer8FADC52CViewModel componentViewModel ? componentViewModel : null;
        }
        if (_rowNewAnimalsComponent != null)
        {
            _rowNewAnimalsComponent.ViewModel = _viewModel is ISyntheticContainer8FADC52CViewModel componentViewModel ? componentViewModel : null;
        }
    }

    private void OnViewModelPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        Refresh();
    }

    private const string VisualTreeResourcePath = "BoomHudGenerated/StardewJournalView";
    private const string StyleSheetResourcePath = "BoomHudGenerated/StardewJournalView";
    private const string GeneratedRootName = "StardewJournal";
    private static VisualTreeAsset? s_visualTreeAsset;
    private static StyleSheet? s_generatedStyleSheet;

    public static StardewJournalView Create(VisualElement parent, string? instanceName = null, IReadOnlyDictionary<string, IReadOnlyDictionary<string, object?>>? componentOverrides = null)
    {
        if (parent == null)
        {
            throw new ArgumentNullException(nameof(parent));
        }

        var root = CreateGeneratedRoot(instanceName);
        parent.Add(root);
        return new StardewJournalView(root, componentOverrides);
    }

    public static StardewJournalView Attach(VisualElement placeholder, IReadOnlyDictionary<string, IReadOnlyDictionary<string, object?>>? componentOverrides = null)
    {
        if (placeholder == null)
        {
            throw new ArgumentNullException(nameof(placeholder));
        }

        var parent = placeholder.parent ?? throw new InvalidOperationException("Cannot attach a generated component without a parent element.");
        var placeholderIndex = parent.IndexOf(placeholder);
        var root = CreateGeneratedRoot(string.IsNullOrWhiteSpace(placeholder.name) ? null : placeholder.name);
        parent.Insert(placeholderIndex, root);
        placeholder.RemoveFromHierarchy();
        return new StardewJournalView(root, componentOverrides);
    }

    private static VisualElement CreateGeneratedRoot(string? instanceName)
    {
        s_visualTreeAsset ??= Resources.Load<VisualTreeAsset>(VisualTreeResourcePath)
            ?? throw new InvalidOperationException($"Could not load VisualTreeAsset from Resources/{VisualTreeResourcePath}.uxml");
        s_generatedStyleSheet ??= Resources.Load<StyleSheet>(StyleSheetResourcePath);

        var staging = new VisualElement();
        s_visualTreeAsset.CloneTree(staging);
        var root = staging.Q<VisualElement>(GeneratedRootName)
            ?? throw new InvalidOperationException($"Could not find generated root element '{GeneratedRootName}' after cloning the tree.");
        root.RemoveFromHierarchy();
        root.name = string.IsNullOrWhiteSpace(instanceName) ? GeneratedRootName : instanceName!;

        if (s_generatedStyleSheet != null && !root.styleSheets.Contains(s_generatedStyleSheet))
        {
            root.styleSheets.Add(s_generatedStyleSheet);
        }

        return root;
    }

    private static readonly Dictionary<string, FontDefinition> s_fontDefinitions = new(StringComparer.OrdinalIgnoreCase);
    private static readonly Dictionary<string, FontAsset> s_sdfFontAssets = new(StringComparer.OrdinalIgnoreCase);
    private static readonly Dictionary<string, string> s_fontResourcePaths = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Press Start 2P"] = "BoomHudFonts/PressStart2P-Regular",
        ["lucide"] = "BoomHudFonts/lucide"
    };
    private static readonly Dictionary<string, string> s_lucideGlyphs = new(StringComparer.OrdinalIgnoreCase)
    {
        ["cross"] = "\uE1E5",
        ["flame"] = "\uE0D2",
        ["flask-conical"] = "\uE0D5",
        ["moon"] = "\uE11E",
        ["shield"] = "\uE158",
        ["sparkles"] = "\uE412",
        ["sword"] = "\uE2B3",
        ["swords"] = "\uE2B4",
        ["wand"] = "\uE246",
        ["wand-2"] = "\uE357",
        ["wand-sparkles"] = "\uE357"
    };

    private static string AsString(object? value) => value?.ToString() ?? string.Empty;

    private static float AsFloat(object? value)
    {
        return value switch
        {
            null => 0f,
            float floatValue => floatValue,
            double doubleValue => (float)doubleValue,
            int intValue => intValue,
            long longValue => longValue,
            decimal decimalValue => (float)decimalValue,
            string stringValue when float.TryParse(stringValue, NumberStyles.Float, CultureInfo.InvariantCulture, out var parsed) => parsed,
            _ => 0f
        };
    }

    private static bool AsBool(object? value)
    {
        return value switch
        {
            bool boolValue => boolValue,
            string stringValue when bool.TryParse(stringValue, out var parsed) => parsed,
            int intValue => intValue != 0,
            long longValue => longValue != 0,
            _ => false
        };
    }

    private bool TryGetComponentOverrideValue(string nodePath, string propertyName, out object? value)
    {
        value = null;
        if (_componentOverrides == null || !_componentOverrides.TryGetValue(nodePath, out var propertyOverrides))
        {
            return false;
        }

        if (propertyOverrides.TryGetValue(propertyName, out value))
        {
            return true;
        }

        foreach (var candidate in propertyOverrides)
        {
            if (string.Equals(candidate.Key, propertyName, StringComparison.OrdinalIgnoreCase))
            {
                value = candidate.Value;
                return true;
            }
        }

        return false;
    }

    private static StyleLength ParseStyleLength(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return StyleKeyword.Null;
        }

        if (string.Equals(value, "auto", StringComparison.OrdinalIgnoreCase))
        {
            return StyleKeyword.Auto;
        }

        if (value.EndsWith("%", StringComparison.Ordinal))
        {
            var number = value[..^1];
            return float.TryParse(number, NumberStyles.Float, CultureInfo.InvariantCulture, out var percent)
                ? new StyleLength(new Length(percent, LengthUnit.Percent))
                : StyleKeyword.Null;
        }

        if (value.EndsWith("px", StringComparison.OrdinalIgnoreCase))
        {
            var number = value[..^2];
            return float.TryParse(number, NumberStyles.Float, CultureInfo.InvariantCulture, out var pixels)
                ? new StyleLength(pixels)
                : StyleKeyword.Null;
        }

        return float.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out var raw)
            ? new StyleLength(raw)
            : StyleKeyword.Null;
    }

    private static float ParseStyleFloat(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return 0f;
        }

        var normalized = value.EndsWith("px", StringComparison.OrdinalIgnoreCase)
            ? value[..^2]
            : value;

        return float.TryParse(normalized, NumberStyles.Float, CultureInfo.InvariantCulture, out var parsed)
            ? parsed
            : 0f;
    }

    private static Position ParsePosition(string value)
        => string.Equals(value, "absolute", StringComparison.OrdinalIgnoreCase)
            ? Position.Absolute
            : Position.Relative;

    private static FlexDirection ParseFlexDirection(string value)
        => string.Equals(value, "row", StringComparison.OrdinalIgnoreCase)
            ? FlexDirection.Row
            : FlexDirection.Column;

    private static Overflow ParseOverflow(string value)
        => string.Equals(value, "hidden", StringComparison.OrdinalIgnoreCase)
            ? Overflow.Hidden
            : Overflow.Visible;

    private static Align ParseAlign(string value)
        => value.ToLowerInvariant() switch
        {
            "flex-start" => Align.FlexStart,
            "center" => Align.Center,
            "flex-end" => Align.FlexEnd,
            "stretch" => Align.Stretch,
            "auto" => Align.Auto,
            _ => Align.Stretch
        };

    private static Justify ParseJustify(string value)
        => value.ToLowerInvariant() switch
        {
            "flex-start" => Justify.FlexStart,
            "center" => Justify.Center,
            "flex-end" => Justify.FlexEnd,
            "space-between" => Justify.SpaceBetween,
            "space-around" => Justify.SpaceAround,
            "space-evenly" => Justify.SpaceEvenly,
            _ => Justify.FlexStart
        };

    private static string? ResolveMappedStyleValue(object? value, string? fallbackValue, params string[] mappings)
    {
        var key = AsString(value);

        for (var index = 0; index + 1 < mappings.Length; index += 2)
        {
            if (string.Equals(mappings[index], key, StringComparison.OrdinalIgnoreCase))
            {
                return mappings[index + 1];
            }
        }

        return string.IsNullOrWhiteSpace(key) ? fallbackValue : key;
    }

    private static Color ParseStyleColor(string? value, string? fallbackValue)
    {
        if (!string.IsNullOrWhiteSpace(value) && ColorUtility.TryParseHtmlString(value, out var parsed))
        {
            return parsed;
        }

        if (!string.IsNullOrWhiteSpace(fallbackValue) && ColorUtility.TryParseHtmlString(fallbackValue, out var fallback))
        {
            return fallback;
        }

        return default;
    }

    private static void SetImageSource(Image image, string resourcePath)
    {
        if (string.IsNullOrWhiteSpace(resourcePath))
        {
            image.image = null;
            return;
        }

        var normalized = resourcePath.Replace("\\", "/", StringComparison.Ordinal).TrimStart('/');
        var extensionIndex = normalized.LastIndexOf('.');
        if (extensionIndex > 0)
        {
            normalized = normalized[..extensionIndex];
        }

        image.image = Resources.Load<Texture2D>(normalized);
    }

    private static void ApplyTextLabelStyle(Label label, bool wrapText)
    {
        label.style.whiteSpace = wrapText ? WhiteSpace.Normal : WhiteSpace.NoWrap;
        label.style.flexShrink = wrapText ? 1 : 0;
        label.style.overflow = wrapText ? Overflow.Hidden : Overflow.Visible;
    }

    private static bool ApplyFontFamily(VisualElement element, string? familyName, float pointSize)
    {
        if (element == null || string.IsNullOrWhiteSpace(familyName))
        {
            return false;
        }

        if (!TryResolveFontDefinition(familyName, pointSize, out var fontDefinition))
        {
            return false;
        }

        element.style.unityFontDefinition = fontDefinition;
        return true;
    }

    private static bool TryResolveFontDefinition(string? familyName, float pointSize, out FontDefinition fontDefinition)
    {
        fontDefinition = default;

        if (string.IsNullOrWhiteSpace(familyName))
        {
            return false;
        }

        var normalizedFamily = familyName.Trim();
        var normalizedSize = Mathf.Max(1, Mathf.RoundToInt(pointSize));
        var cacheKey = $"{normalizedFamily}|{normalizedSize}";

        if (s_fontDefinitions.TryGetValue(cacheKey, out fontDefinition))
        {
            return true;
        }

        if (TryLoadSdfFontAsset(normalizedFamily, out var fontAsset))
        {
            fontDefinition = FontDefinition.FromSDFFont(fontAsset);
            s_fontDefinitions[cacheKey] = fontDefinition;
            return true;
        }

        if (!TryLoadFont(normalizedFamily, normalizedSize, out var font))
        {
            return false;
        }

        fontDefinition = FontDefinition.FromFont(font);
        s_fontDefinitions[cacheKey] = fontDefinition;
        return true;
    }

    private static bool TryLoadSdfFontAsset(string familyName, out FontAsset fontAsset)
    {
        fontAsset = null!;

        var normalizedFamily = familyName.Trim();
        if (s_sdfFontAssets.TryGetValue(normalizedFamily, out fontAsset))
        {
            return fontAsset != null;
        }

        fontAsset = LoadBundledSdfFontAsset(normalizedFamily)!;
        if (fontAsset == null)
        {
            return false;
        }

        s_sdfFontAssets[normalizedFamily] = fontAsset;
        return true;
    }

    private static FontAsset? LoadBundledSdfFontAsset(string familyName)
    {
        var normalizedFamily = familyName.Trim();

        if (s_fontResourcePaths.TryGetValue(normalizedFamily, out var resourcePath))
        {
            return Resources.Load<FontAsset>(resourcePath);
        }

        var compactName = normalizedFamily.Replace(" ", string.Empty, StringComparison.Ordinal).Replace("-", string.Empty, StringComparison.Ordinal);
        return Resources.Load<FontAsset>($"BoomHudFonts/{compactName}") ?? Resources.Load<FontAsset>($"BoomHudFonts/{normalizedFamily}");
    }

    private static bool TryLoadFont(string familyName, int pointSize, out Font font)
    {
        font = null!;

        var resourceFont = LoadBundledFont(familyName);
        if (resourceFont != null)
        {
            font = resourceFont;
            return true;
        }

        var fontCandidates = ExpandFontFamilyCandidates(familyName);
        foreach (var candidate in fontCandidates)
        {
            resourceFont = LoadBundledFont(candidate);
            if (resourceFont != null)
            {
                font = resourceFont;
                return true;
            }
        }

        try
        {
            var osFont = Font.CreateDynamicFontFromOSFont(fontCandidates, pointSize);
            if (osFont == null)
            {
                return false;
            }

            font = osFont;
            return true;
        }
        catch
        {
            return false;
        }
    }

    private static Font? LoadBundledFont(string familyName)
    {
        var normalizedFamily = familyName.Trim();

        if (s_fontResourcePaths.TryGetValue(normalizedFamily, out var resourcePath))
        {
            return Resources.Load<Font>(resourcePath);
        }

        var compactName = normalizedFamily.Replace(" ", string.Empty, StringComparison.Ordinal).Replace("-", string.Empty, StringComparison.Ordinal);
        return Resources.Load<Font>($"BoomHudFonts/{compactName}") ?? Resources.Load<Font>($"BoomHudFonts/{normalizedFamily}");
    }

    private static string[] ExpandFontFamilyCandidates(string familyName)
    {
        var rawCandidates = familyName.Split(',');
        var expanded = new List<string>();

        foreach (var rawCandidate in rawCandidates)
        {
            var candidate = rawCandidate.Trim().Trim('\'', '"');
            if (string.IsNullOrWhiteSpace(candidate))
            {
                continue;
            }

            switch (candidate.ToLowerInvariant())
            {
                case "monospace":
                    expanded.Add("Consolas");
                    expanded.Add("Cascadia Mono");
                    expanded.Add("Courier New");
                    expanded.Add("Lucida Console");
                    break;
                case "sans-serif":
                case "sans serif":
                    expanded.Add("Segoe UI");
                    expanded.Add("Arial");
                    break;
                case "serif":
                    expanded.Add("Georgia");
                    expanded.Add("Times New Roman");
                    break;
                default:
                    expanded.Add(candidate);
                    break;
            }
        }

        if (expanded.Count == 0)
        {
            expanded.Add(familyName.Trim());
        }

        return expanded.Distinct(StringComparer.OrdinalIgnoreCase).ToArray();
    }

    private static string ResolveIconText(string value, string? familyName, float pointSize)
    {
        if (!TryResolveFontDefinition(familyName, pointSize, out _))
        {
            return NormalizeIconText(value);
        }

        if (TryResolveIconGlyphText(value, familyName, out var glyphText))
        {
            return glyphText;
        }

        return string.Equals(familyName?.Trim(), "lucide", StringComparison.OrdinalIgnoreCase) ? NormalizeIconText(value) : value;
    }

    private static bool TryResolveIconGlyphText(string value, string? familyName, out string glyphText)
    {
        glyphText = string.Empty;

        if (string.IsNullOrWhiteSpace(familyName))
        {
            return false;
        }

        var normalizedFamily = familyName.Trim();
        if (string.Equals(normalizedFamily, "lucide", StringComparison.OrdinalIgnoreCase) && s_lucideGlyphs.TryGetValue(value, out glyphText))
        {
            return true;
        }

        return false;
    }

    private static string NormalizeIconText(string value)
    {
        return value switch
        {
            "sword" => "†",
            "swords" => "⚔",
            "sparkles" => "✦",
            "wand-sparkles" => "✦",
            "shield" => "⛨",
            "flask-conical" => "⚗",
            "flame" => "✹",
            "moon" => "☾",
            "cross" => "✚",
            _ => value
        };
    }

    private static void ApplyIconLabelStyle(Label label, float boxWidth, float boxHeight, float baselineOffset, bool opticalCentering, string sizeMode, float explicitFontSize)
    {
        var iconSize = explicitFontSize > 0f ? explicitFontSize : string.Equals(sizeMode, "match-height", StringComparison.OrdinalIgnoreCase) ? Mathf.Max(1f, boxHeight) : Mathf.Max(1f, Mathf.Min(boxWidth, boxHeight));
        label.style.unityTextAlign = TextAnchor.MiddleCenter;
        label.style.unityFontStyleAndWeight = FontStyle.Normal;
        label.style.whiteSpace = WhiteSpace.NoWrap;
        label.style.flexShrink = 0;
        label.style.alignItems = opticalCentering ? Align.Center : Align.FlexStart;
        label.style.justifyContent = opticalCentering ? Justify.Center : Justify.FlexStart;
        label.style.overflow = Overflow.Visible;
        label.style.paddingLeft = 0f;
        label.style.paddingTop = 0f;
        label.style.paddingRight = 0f;
        label.style.paddingBottom = 0f;
        label.style.width = boxWidth;
        label.style.height = boxHeight;
        label.style.minWidth = boxWidth;
        label.style.minHeight = boxHeight;
        if (opticalCentering && boxWidth >= 32f && boxHeight >= 32f && Mathf.Approximately(baselineOffset, 0f))
        {
            label.style.marginTop = -1f;
        }
        else if (!Mathf.Approximately(baselineOffset, 0f))
        {
            label.style.marginTop = baselineOffset;
        }
        label.style.fontSize = iconSize;
    }
}
}
