// <auto-generated>
// Generated by BoomHud.Gen.Unity from StatBar
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Linq;
using UnityEngine;
using UnityEngine.TextCore.Text;
using UnityEngine.UIElements;

namespace Generated.Hud
{
public sealed class StatBarView
{
    private readonly IStatBarViewModel? _initialViewModel = null;
    private IStatBarViewModel? _viewModel;

    public VisualElement Root { get; }
    public VisualElement Fill { get; }

    public IStatBarViewModel? ViewModel
    {
        get => _viewModel;
        set
        {
            if (_viewModel != null)
            {
                _viewModel.PropertyChanged -= OnViewModelPropertyChanged;
            }

            _viewModel = value;

            if (_viewModel != null)
            {
                _viewModel.PropertyChanged += OnViewModelPropertyChanged;
            }

            Refresh();
        }
    }

    public StatBarView(VisualElement root)
    {
        Root = root as VisualElement ?? throw new ArgumentException("Expected root element type VisualElement.", nameof(root));
        Fill = Root.Q<VisualElement>("Fill") ?? throw new InvalidOperationException("Could not find generated element 'Fill'.");

        ApplyStaticValues();
        ViewModel = _initialViewModel;
    }

    public void Refresh()
    {
        if (_viewModel == null)
        {
            return;
        }

    }

    private void ApplyStaticValues()
    {
        Root.style.display = DisplayStyle.Flex;
        Root.SetEnabled(true);
        Fill.style.display = DisplayStyle.Flex;
        Fill.SetEnabled(true);
    }

    private void OnViewModelPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        Refresh();
    }

    private static readonly Dictionary<string, FontDefinition> s_fontDefinitions = new(StringComparer.OrdinalIgnoreCase);
    private static readonly Dictionary<string, FontAsset> s_sdfFontAssets = new(StringComparer.OrdinalIgnoreCase);
    private static readonly Dictionary<string, string> s_fontResourcePaths = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Press Start 2P"] = "BoomHudFonts/PressStart2P-Regular",
        ["lucide"] = "BoomHudFonts/lucide"
    };
    private static readonly Dictionary<string, string> s_lucideGlyphs = new(StringComparer.OrdinalIgnoreCase)
    {
        ["cross"] = "\uE1E5",
        ["flame"] = "\uE0D2",
        ["flask-conical"] = "\uE0D5",
        ["moon"] = "\uE11E",
        ["shield"] = "\uE158",
        ["sparkles"] = "\uE412",
        ["sword"] = "\uE2B3",
        ["swords"] = "\uE2B4",
        ["wand"] = "\uE246",
        ["wand-2"] = "\uE357",
        ["wand-sparkles"] = "\uE357"
    };

    private static string AsString(object? value) => value?.ToString() ?? string.Empty;

    private static float AsFloat(object? value)
    {
        return value switch
        {
            null => 0f,
            float floatValue => floatValue,
            double doubleValue => (float)doubleValue,
            int intValue => intValue,
            long longValue => longValue,
            decimal decimalValue => (float)decimalValue,
            string stringValue when float.TryParse(stringValue, NumberStyles.Float, CultureInfo.InvariantCulture, out var parsed) => parsed,
            _ => 0f
        };
    }

    private static bool AsBool(object? value)
    {
        return value switch
        {
            bool boolValue => boolValue,
            string stringValue when bool.TryParse(stringValue, out var parsed) => parsed,
            int intValue => intValue != 0,
            long longValue => longValue != 0,
            _ => false
        };
    }

    private static string? ResolveMappedStyleValue(object? value, string? fallbackValue, params string[] mappings)
    {
        var key = AsString(value);

        for (var index = 0; index + 1 < mappings.Length; index += 2)
        {
            if (string.Equals(mappings[index], key, StringComparison.OrdinalIgnoreCase))
            {
                return mappings[index + 1];
            }
        }

        return string.IsNullOrWhiteSpace(key) ? fallbackValue : key;
    }

    private static Color ParseStyleColor(string? value, string? fallbackValue)
    {
        if (!string.IsNullOrWhiteSpace(value) && ColorUtility.TryParseHtmlString(value, out var parsed))
        {
            return parsed;
        }

        if (!string.IsNullOrWhiteSpace(fallbackValue) && ColorUtility.TryParseHtmlString(fallbackValue, out var fallback))
        {
            return fallback;
        }

        return default;
    }

    private static void ApplyTextLabelStyle(Label label)
    {
        label.style.whiteSpace = WhiteSpace.NoWrap;
        label.style.flexShrink = 0;
        label.style.overflow = Overflow.Visible;
    }

    private static bool ApplyFontFamily(VisualElement element, string? familyName, float pointSize)
    {
        if (element == null || string.IsNullOrWhiteSpace(familyName))
        {
            return false;
        }

        if (!TryResolveFontDefinition(familyName, pointSize, out var fontDefinition))
        {
            return false;
        }

        element.style.unityFontDefinition = fontDefinition;
        return true;
    }

    private static bool TryResolveFontDefinition(string? familyName, float pointSize, out FontDefinition fontDefinition)
    {
        fontDefinition = default;

        if (string.IsNullOrWhiteSpace(familyName))
        {
            return false;
        }

        var normalizedFamily = familyName.Trim();
        var normalizedSize = Mathf.Max(1, Mathf.RoundToInt(pointSize));
        var cacheKey = $"{normalizedFamily}|{normalizedSize}";

        if (s_fontDefinitions.TryGetValue(cacheKey, out fontDefinition))
        {
            return true;
        }

        if (TryLoadSdfFontAsset(normalizedFamily, out var fontAsset))
        {
            fontDefinition = FontDefinition.FromSDFFont(fontAsset);
            s_fontDefinitions[cacheKey] = fontDefinition;
            return true;
        }

        if (!TryLoadFont(normalizedFamily, normalizedSize, out var font))
        {
            return false;
        }

        fontDefinition = FontDefinition.FromFont(font);
        s_fontDefinitions[cacheKey] = fontDefinition;
        return true;
    }

    private static bool TryLoadSdfFontAsset(string familyName, out FontAsset fontAsset)
    {
        fontAsset = null!;

        var normalizedFamily = familyName.Trim();
        if (s_sdfFontAssets.TryGetValue(normalizedFamily, out fontAsset))
        {
            return fontAsset != null;
        }

        fontAsset = LoadBundledSdfFontAsset(normalizedFamily)!;
        if (fontAsset == null)
        {
            return false;
        }

        s_sdfFontAssets[normalizedFamily] = fontAsset;
        return true;
    }

    private static FontAsset? LoadBundledSdfFontAsset(string familyName)
    {
        var normalizedFamily = familyName.Trim();

        if (s_fontResourcePaths.TryGetValue(normalizedFamily, out var resourcePath))
        {
            return Resources.Load<FontAsset>(resourcePath);
        }

        var compactName = normalizedFamily.Replace(" ", string.Empty, StringComparison.Ordinal).Replace("-", string.Empty, StringComparison.Ordinal);
        return Resources.Load<FontAsset>($"BoomHudFonts/{compactName}") ?? Resources.Load<FontAsset>($"BoomHudFonts/{normalizedFamily}");
    }

    private static bool TryLoadFont(string familyName, int pointSize, out Font font)
    {
        font = null!;

        var resourceFont = LoadBundledFont(familyName);
        if (resourceFont != null)
        {
            font = resourceFont;
            return true;
        }

        var fontCandidates = ExpandFontFamilyCandidates(familyName);
        foreach (var candidate in fontCandidates)
        {
            resourceFont = LoadBundledFont(candidate);
            if (resourceFont != null)
            {
                font = resourceFont;
                return true;
            }
        }

        try
        {
            var osFont = Font.CreateDynamicFontFromOSFont(fontCandidates, pointSize);
            if (osFont == null)
            {
                return false;
            }

            font = osFont;
            return true;
        }
        catch
        {
            return false;
        }
    }

    private static Font? LoadBundledFont(string familyName)
    {
        var normalizedFamily = familyName.Trim();

        if (s_fontResourcePaths.TryGetValue(normalizedFamily, out var resourcePath))
        {
            return Resources.Load<Font>(resourcePath);
        }

        var compactName = normalizedFamily.Replace(" ", string.Empty, StringComparison.Ordinal).Replace("-", string.Empty, StringComparison.Ordinal);
        return Resources.Load<Font>($"BoomHudFonts/{compactName}") ?? Resources.Load<Font>($"BoomHudFonts/{normalizedFamily}");
    }

    private static string[] ExpandFontFamilyCandidates(string familyName)
    {
        var rawCandidates = familyName.Split(',');
        var expanded = new List<string>();

        foreach (var rawCandidate in rawCandidates)
        {
            var candidate = rawCandidate.Trim().Trim('\'', '"');
            if (string.IsNullOrWhiteSpace(candidate))
            {
                continue;
            }

            switch (candidate.ToLowerInvariant())
            {
                case "monospace":
                    expanded.Add("Consolas");
                    expanded.Add("Cascadia Mono");
                    expanded.Add("Courier New");
                    expanded.Add("Lucida Console");
                    break;
                case "sans-serif":
                case "sans serif":
                    expanded.Add("Segoe UI");
                    expanded.Add("Arial");
                    break;
                case "serif":
                    expanded.Add("Georgia");
                    expanded.Add("Times New Roman");
                    break;
                default:
                    expanded.Add(candidate);
                    break;
            }
        }

        if (expanded.Count == 0)
        {
            expanded.Add(familyName.Trim());
        }

        return expanded.Distinct(StringComparer.OrdinalIgnoreCase).ToArray();
    }

    private static string ResolveIconText(string value, string? familyName, float pointSize)
    {
        if (!TryResolveFontDefinition(familyName, pointSize, out _))
        {
            return NormalizeIconText(value);
        }

        if (TryResolveIconGlyphText(value, familyName, out var glyphText))
        {
            return glyphText;
        }

        return string.Equals(familyName?.Trim(), "lucide", StringComparison.OrdinalIgnoreCase) ? NormalizeIconText(value) : value;
    }

    private static bool TryResolveIconGlyphText(string value, string? familyName, out string glyphText)
    {
        glyphText = string.Empty;

        if (string.IsNullOrWhiteSpace(familyName))
        {
            return false;
        }

        var normalizedFamily = familyName.Trim();
        if (string.Equals(normalizedFamily, "lucide", StringComparison.OrdinalIgnoreCase) && s_lucideGlyphs.TryGetValue(value, out glyphText))
        {
            return true;
        }

        return false;
    }

    private static string NormalizeIconText(string value)
    {
        return value switch
        {
            "sword" => "†",
            "swords" => "⚔",
            "sparkles" => "✦",
            "wand-sparkles" => "✦",
            "shield" => "⛨",
            "flask-conical" => "⚗",
            "flame" => "✹",
            "moon" => "☾",
            "cross" => "✚",
            _ => value
        };
    }

    private static void ApplyIconLabelStyle(Label label, float boxWidth, float boxHeight)
    {
        var iconSize = Mathf.Max(1f, Mathf.Min(boxWidth, boxHeight));
        label.style.unityTextAlign = TextAnchor.MiddleCenter;
        label.style.unityFontStyleAndWeight = FontStyle.Normal;
        label.style.whiteSpace = WhiteSpace.NoWrap;
        label.style.flexShrink = 0;
        label.style.alignItems = Align.Center;
        label.style.justifyContent = Justify.Center;
        label.style.overflow = Overflow.Visible;
        label.style.paddingLeft = 0f;
        label.style.paddingTop = 0f;
        label.style.paddingRight = 0f;
        label.style.paddingBottom = 0f;
        label.style.width = boxWidth;
        label.style.height = boxHeight;
        label.style.minWidth = boxWidth;
        label.style.minHeight = boxHeight;
        label.style.fontSize = iconSize;
    }
}
}
