// <auto-generated>
// Generated by BoomHud.Gen.UGui from CharPortrait motion host
// </auto-generated>

#nullable enable

using System;
using BoomHud.Unity.UGUI;
using UnityEngine;

namespace Generated.Hud.UGui
{
public class CharPortraitMotionHost : BoomHudUguiMotionHost
{
    private CharPortraitView? _view;

    public CharPortraitView View => _view ?? throw new InvalidOperationException("The generated view has not been bound yet.");

    protected override void BindMotionView(RectTransform root)
    {
        if (root == null)
        {
            throw new ArgumentNullException(nameof(root));
        }

        _view = BindExistingOrCreate(root);
    }

    protected override bool TryApplyMotionAtTime(string clipId, float timeSeconds)
    {
        return _view != null && CharPortraitMotion.TryApplyAtTime(_view, clipId, timeSeconds);
    }

    protected override float GetClipDurationSeconds(string clipId)
    {
        return CharPortraitMotion.GetClipDurationSeconds(clipId);
    }

    private static CharPortraitView BindExistingOrCreate(RectTransform root)
    {
        if (TryBindExisting(root, out var boundView))
        {
            return boundView;
        }

        if (root.childCount == 1 && root.GetChild(0) is RectTransform childRoot && TryBindExisting(childRoot, out boundView))
        {
            return boundView;
        }

        return new CharPortraitView(root);
    }

    private static bool TryBindExisting(RectTransform root, out CharPortraitView view)
    {
        try
        {
            view = CharPortraitView.Bind(root);
            return true;
        }
        catch (InvalidOperationException)
        {
            view = null!;
            return false;
        }
    }
}
}
