// <auto-generated>
// Generated by BoomHud.Gen.UGui from CombatToastStack
// </auto-generated>

#nullable enable

using System;
using PropertyChangedEventArgs = System.ComponentModel.PropertyChangedEventArgs;
using System.Globalization;
using UnityEngine;
using UnityEngine.UI;

namespace Generated.Hud.UGui
{
public sealed class CombatToastStackView
{
    private ICombatToastStackViewModel? _viewModel;
    public RectTransform Root { get; }
    public RectTransform ToastOne { get; }
    public RectTransform IconPanel { get; }
    public Text EventIcon { get; }
    public RectTransform Content { get; }
    public Text Title { get; }
    public Text Body { get; }
    public RectTransform Progress { get; }
    public RectTransform ProgressFill { get; }
    public Text ProgressText { get; }
    public RectTransform RewardColumn { get; }
    public Text Tag { get; }
    public Text Value { get; }
    public Text Time { get; }
    public RectTransform Badge { get; }
    public Text BadgeText { get; }
    public RectTransform ToastTwo { get; }
    public RectTransform IconPanel2 { get; }
    public Text EventIcon2 { get; }
    public RectTransform Content2 { get; }
    public Text Title2 { get; }
    public Text Body2 { get; }
    public RectTransform Progress2 { get; }
    public RectTransform ProgressFill2 { get; }
    public Text ProgressText2 { get; }
    public RectTransform RewardColumn2 { get; }
    public Text Tag2 { get; }
    public Text Value2 { get; }
    public Text Time2 { get; }
    public RectTransform Badge2 { get; }
    public Text BadgeText2 { get; }
    public RectTransform ToastThree { get; }
    public RectTransform IconPanel3 { get; }
    public Text EventIcon3 { get; }
    public RectTransform Content3 { get; }
    public Text Title3 { get; }
    public Text Body3 { get; }
    public RectTransform Progress3 { get; }
    public RectTransform ProgressFill3 { get; }
    public Text ProgressText3 { get; }
    public RectTransform RewardColumn3 { get; }
    public Text Tag3 { get; }
    public Text Value3 { get; }
    public Text Time3 { get; }
    public RectTransform Badge3 { get; }
    public Text BadgeText3 { get; }

    public ICombatToastStackViewModel? ViewModel
    {
        get => _viewModel;
        set
        {
            if (ReferenceEquals(_viewModel, value)) return;
            if (_viewModel != null) _viewModel.PropertyChanged -= OnChanged;
            _viewModel = value;
            if (_viewModel != null) _viewModel.PropertyChanged += OnChanged;
            Refresh();
        }
    }

    public CombatToastStackView(Transform? parent = null, ICombatToastStackViewModel? viewModel = null)
    {
        Root = CreateRect("CombatToastStackRoot", parent);
        ConfigureRect(Root, width: 960f, height: 720f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(Root, ignoreLayout: false, preferredWidth: 960f, preferredHeight: 720f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(Root, horizontal: false, vertical: false);
        ApplyVerticalLayout(Root, 18f, 24, 24, 24, 24);
        ApplyStyle(Root, fg: "#050505", bg: "#050505", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Root.gameObject.SetActive(true);
        ToastOne = CreateRect("ToastOne", Root);
        ConfigureRect(RectOf(ToastOne), width: null, height: 180f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(ToastOne), ignoreLayout: false, preferredWidth: null, preferredHeight: 180f, flexibleWidth: 1f, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(ToastOne), horizontal: false, vertical: false);
        ApplyStyle(ToastOne, fg: "#101010", bg: "#101010", fontFamily: null, fontSize: null, borderColor: "#7E7E7E", borderWidth: 6f, treatAsIcon: false);
        ToastOne.gameObject.SetActive(true);
        IconPanel = CreateRect("IconPanel", RectOf(ToastOne));
        ConfigureRect(RectOf(IconPanel), width: 132f, height: 132f, left: 16f, top: 16f, absolute: true);
        ApplyLayoutSizing(RectOf(IconPanel), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(IconPanel), horizontal: false, vertical: false);
        ApplyVerticalLayout(RectOf(IconPanel), 0f, 0, 0, 0, 0);
        ApplyStyle(IconPanel, fg: "#000000", bg: "#000000", fontFamily: null, fontSize: null, borderColor: "#EAEAEA", borderWidth: 4f, treatAsIcon: false);
        IconPanel.gameObject.SetActive(true);
        EventIcon = CreateText("EventIcon", RectOf(IconPanel));
        ConfigureRect(RectOf(EventIcon), width: 56f, height: 56f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(EventIcon), ignoreLayout: false, preferredWidth: 56f, preferredHeight: 56f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(EventIcon), horizontal: false, vertical: false);
        ApplyStyle(EventIcon, fg: "#FFFFFF", bg: null, fontFamily: "lucide", fontSize: 56, borderColor: null, borderWidth: null, treatAsIcon: true);
        ApplyIconMetrics(EventIcon, boxWidth: 56f, boxHeight: 56f, baselineOffset: 0f, opticalCentering: true, sizeMode: "fit-box", explicitFontSize: 0f);
        ApplyTextMetrics(EventIcon, lineSpacing: null, wrapText: false);
        EventIcon.text = ResolveIconText("flame");
        EventIcon.gameObject.SetActive(true);
        Content = CreateRect("Content", RectOf(ToastOne));
        ConfigureRect(RectOf(Content), width: 560f, height: 144f, left: 168f, top: 18f, absolute: true);
        ApplyLayoutSizing(RectOf(Content), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Content), horizontal: false, vertical: false);
        ApplyVerticalLayout(RectOf(Content), 10f, 0, 0, 0, 0);
        ApplyStyle(Content, fg: "#101010", bg: "#101010", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Content.gameObject.SetActive(true);
        Title = CreateText("Title", RectOf(Content));
        ConfigureRect(RectOf(Title), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Title), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Title), horizontal: false, vertical: false);
        ApplyStyle(Title, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 14, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(Title, lineSpacing: null, wrapText: false);
        Title.text = "CRITICAL BURN DETECTED";
        Title.gameObject.SetActive(true);
        Body = CreateText("Body", RectOf(Content));
        ConfigureRect(RectOf(Body), width: 540f, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Body), ignoreLayout: false, preferredWidth: 540f, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Body), horizontal: false, vertical: false);
        ApplyStyle(Body, fg: "#AAAAAA", bg: null, fontFamily: "Press Start 2P", fontSize: 9, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(Body, lineSpacing: null, wrapText: true);
        Body.text = "The ignition lattice is unstable. Redirect coolant flow before the chamber overloads.";
        Body.gameObject.SetActive(true);
        Progress = CreateRect("Progress", RectOf(Content));
        ConfigureRect(RectOf(Progress), width: 540f, height: 22f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Progress), ignoreLayout: false, preferredWidth: 540f, preferredHeight: 22f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Progress), horizontal: false, vertical: false);
        ApplyStyle(Progress, fg: "#1E1E1E", bg: "#1E1E1E", fontFamily: null, fontSize: null, borderColor: "#8C8C8C", borderWidth: 2f, treatAsIcon: false);
        Progress.gameObject.SetActive(true);
        ProgressFill = CreateRect("ProgressFill", RectOf(Progress));
        ConfigureRect(RectOf(ProgressFill), width: 312f, height: 18f, left: null, top: null, absolute: true);
        ApplyLayoutSizing(RectOf(ProgressFill), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(ProgressFill), horizontal: false, vertical: false);
        ApplyStyle(ProgressFill, fg: "#D44A4A", bg: "#D44A4A", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        ProgressFill.gameObject.SetActive(true);
        ProgressText = CreateText("ProgressText", RectOf(Progress));
        ConfigureRect(RectOf(ProgressText), width: null, height: null, left: 12f, top: 4f, absolute: true);
        ApplyLayoutSizing(RectOf(ProgressText), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(ProgressText), horizontal: false, vertical: false);
        ApplyStyle(ProgressText, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 9, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(ProgressText, lineSpacing: null, wrapText: false);
        ProgressText.text = "RESPONSE WINDOW 58%";
        ProgressText.gameObject.SetActive(true);
        RewardColumn = CreateRect("RewardColumn", RectOf(ToastOne));
        ConfigureRect(RectOf(RewardColumn), width: 164f, height: 132f, left: 764f, top: 16f, absolute: true);
        ApplyLayoutSizing(RectOf(RewardColumn), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(RewardColumn), horizontal: false, vertical: false);
        ApplyVerticalLayout(RectOf(RewardColumn), 10f, 12, 12, 12, 12);
        ApplyStyle(RewardColumn, fg: "#0C0C0C", bg: "#0C0C0C", fontFamily: null, fontSize: null, borderColor: "#7E7E7E", borderWidth: 4f, treatAsIcon: false);
        RewardColumn.gameObject.SetActive(true);
        Tag = CreateText("Tag", RectOf(RewardColumn));
        ConfigureRect(RectOf(Tag), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Tag), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Tag), horizontal: false, vertical: false);
        ApplyStyle(Tag, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 10, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(Tag, lineSpacing: null, wrapText: false);
        Tag.text = "ALERT";
        Tag.gameObject.SetActive(true);
        Value = CreateText("Value", RectOf(RewardColumn));
        ConfigureRect(RectOf(Value), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Value), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Value), horizontal: false, vertical: false);
        ApplyStyle(Value, fg: "#AAAAAA", bg: null, fontFamily: "Press Start 2P", fontSize: 9, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(Value, lineSpacing: null, wrapText: false);
        Value.text = "+120 XP";
        Value.gameObject.SetActive(true);
        Time = CreateText("Time", RectOf(RewardColumn));
        ConfigureRect(RectOf(Time), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Time), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Time), horizontal: false, vertical: false);
        ApplyStyle(Time, fg: "#AAAAAA", bg: null, fontFamily: "Press Start 2P", fontSize: 9, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(Time, lineSpacing: null, wrapText: false);
        Time.text = "00:14";
        Time.gameObject.SetActive(true);
        Badge = CreateRect("Badge", RectOf(ToastOne));
        ConfigureRect(RectOf(Badge), width: 120f, height: 28f, left: 784f, top: 0f, absolute: true);
        ApplyLayoutSizing(RectOf(Badge), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Badge), horizontal: false, vertical: false);
        ApplyVerticalLayout(RectOf(Badge), 0f, 0, 0, 0, 0);
        ApplyStyle(Badge, fg: "#D44A4A", bg: "#D44A4A", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Badge.gameObject.SetActive(true);
        BadgeText = CreateText("BadgeText", RectOf(Badge));
        ConfigureRect(RectOf(BadgeText), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(BadgeText), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(BadgeText), horizontal: false, vertical: false);
        ApplyStyle(BadgeText, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 8, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(BadgeText, lineSpacing: null, wrapText: false);
        BadgeText.text = "PRIORITY";
        BadgeText.gameObject.SetActive(true);
        ToastTwo = CreateRect("ToastTwo", Root);
        ConfigureRect(RectOf(ToastTwo), width: null, height: 180f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(ToastTwo), ignoreLayout: false, preferredWidth: null, preferredHeight: 180f, flexibleWidth: 1f, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(ToastTwo), horizontal: false, vertical: false);
        ApplyStyle(ToastTwo, fg: "#101010", bg: "#101010", fontFamily: null, fontSize: null, borderColor: "#7E7E7E", borderWidth: 6f, treatAsIcon: false);
        ToastTwo.gameObject.SetActive(true);
        IconPanel2 = CreateRect("IconPanel2", RectOf(ToastTwo));
        ConfigureRect(RectOf(IconPanel2), width: 132f, height: 132f, left: 16f, top: 16f, absolute: true);
        ApplyLayoutSizing(RectOf(IconPanel2), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(IconPanel2), horizontal: false, vertical: false);
        ApplyVerticalLayout(RectOf(IconPanel2), 0f, 0, 0, 0, 0);
        ApplyStyle(IconPanel2, fg: "#000000", bg: "#000000", fontFamily: null, fontSize: null, borderColor: "#EAEAEA", borderWidth: 4f, treatAsIcon: false);
        IconPanel2.gameObject.SetActive(true);
        EventIcon2 = CreateText("EventIcon2", RectOf(IconPanel2));
        ConfigureRect(RectOf(EventIcon2), width: 56f, height: 56f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(EventIcon2), ignoreLayout: false, preferredWidth: 56f, preferredHeight: 56f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(EventIcon2), horizontal: false, vertical: false);
        ApplyStyle(EventIcon2, fg: "#FFFFFF", bg: null, fontFamily: "lucide", fontSize: 56, borderColor: null, borderWidth: null, treatAsIcon: true);
        ApplyIconMetrics(EventIcon2, boxWidth: 56f, boxHeight: 56f, baselineOffset: 0f, opticalCentering: true, sizeMode: "fit-box", explicitFontSize: 0f);
        ApplyTextMetrics(EventIcon2, lineSpacing: null, wrapText: false);
        EventIcon2.text = ResolveIconText("shield");
        EventIcon2.gameObject.SetActive(true);
        Content2 = CreateRect("Content2", RectOf(ToastTwo));
        ConfigureRect(RectOf(Content2), width: 560f, height: 144f, left: 168f, top: 18f, absolute: true);
        ApplyLayoutSizing(RectOf(Content2), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Content2), horizontal: false, vertical: false);
        ApplyVerticalLayout(RectOf(Content2), 10f, 0, 0, 0, 0);
        ApplyStyle(Content2, fg: "#101010", bg: "#101010", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Content2.gameObject.SetActive(true);
        Title2 = CreateText("Title2", RectOf(Content2));
        ConfigureRect(RectOf(Title2), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Title2), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Title2), horizontal: false, vertical: false);
        ApplyStyle(Title2, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 14, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(Title2, lineSpacing: null, wrapText: false);
        Title2.text = "WARD MATRIX HOLDING";
        Title2.gameObject.SetActive(true);
        Body2 = CreateText("Body2", RectOf(Content2));
        ConfigureRect(RectOf(Body2), width: 540f, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Body2), ignoreLayout: false, preferredWidth: 540f, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Body2), horizontal: false, vertical: false);
        ApplyStyle(Body2, fg: "#AAAAAA", bg: null, fontFamily: "Press Start 2P", fontSize: 9, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(Body2, lineSpacing: null, wrapText: true);
        Body2.text = "Barrier anchors are synchronized. Redirect one guardian to the southern breach to prevent collapse.";
        Body2.gameObject.SetActive(true);
        Progress2 = CreateRect("Progress2", RectOf(Content2));
        ConfigureRect(RectOf(Progress2), width: 540f, height: 22f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Progress2), ignoreLayout: false, preferredWidth: 540f, preferredHeight: 22f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Progress2), horizontal: false, vertical: false);
        ApplyStyle(Progress2, fg: "#1E1E1E", bg: "#1E1E1E", fontFamily: null, fontSize: null, borderColor: "#8C8C8C", borderWidth: 2f, treatAsIcon: false);
        Progress2.gameObject.SetActive(true);
        ProgressFill2 = CreateRect("ProgressFill2", RectOf(Progress2));
        ConfigureRect(RectOf(ProgressFill2), width: 414f, height: 18f, left: null, top: null, absolute: true);
        ApplyLayoutSizing(RectOf(ProgressFill2), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(ProgressFill2), horizontal: false, vertical: false);
        ApplyStyle(ProgressFill2, fg: "#4A78D4", bg: "#4A78D4", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        ProgressFill2.gameObject.SetActive(true);
        ProgressText2 = CreateText("ProgressText2", RectOf(Progress2));
        ConfigureRect(RectOf(ProgressText2), width: null, height: null, left: 12f, top: 4f, absolute: true);
        ApplyLayoutSizing(RectOf(ProgressText2), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(ProgressText2), horizontal: false, vertical: false);
        ApplyStyle(ProgressText2, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 9, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(ProgressText2, lineSpacing: null, wrapText: false);
        ProgressText2.text = "WARD STABILITY 77%";
        ProgressText2.gameObject.SetActive(true);
        RewardColumn2 = CreateRect("RewardColumn2", RectOf(ToastTwo));
        ConfigureRect(RectOf(RewardColumn2), width: 164f, height: 132f, left: 764f, top: 16f, absolute: true);
        ApplyLayoutSizing(RectOf(RewardColumn2), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(RewardColumn2), horizontal: false, vertical: false);
        ApplyVerticalLayout(RectOf(RewardColumn2), 10f, 12, 12, 12, 12);
        ApplyStyle(RewardColumn2, fg: "#0C0C0C", bg: "#0C0C0C", fontFamily: null, fontSize: null, borderColor: "#7E7E7E", borderWidth: 4f, treatAsIcon: false);
        RewardColumn2.gameObject.SetActive(true);
        Tag2 = CreateText("Tag2", RectOf(RewardColumn2));
        ConfigureRect(RectOf(Tag2), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Tag2), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Tag2), horizontal: false, vertical: false);
        ApplyStyle(Tag2, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 10, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(Tag2, lineSpacing: null, wrapText: false);
        Tag2.text = "DEFENSE";
        Tag2.gameObject.SetActive(true);
        Value2 = CreateText("Value2", RectOf(RewardColumn2));
        ConfigureRect(RectOf(Value2), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Value2), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Value2), horizontal: false, vertical: false);
        ApplyStyle(Value2, fg: "#AAAAAA", bg: null, fontFamily: "Press Start 2P", fontSize: 9, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(Value2, lineSpacing: null, wrapText: false);
        Value2.text = "+1 barrier";
        Value2.gameObject.SetActive(true);
        Time2 = CreateText("Time2", RectOf(RewardColumn2));
        ConfigureRect(RectOf(Time2), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Time2), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Time2), horizontal: false, vertical: false);
        ApplyStyle(Time2, fg: "#AAAAAA", bg: null, fontFamily: "Press Start 2P", fontSize: 9, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(Time2, lineSpacing: null, wrapText: false);
        Time2.text = "00:21";
        Time2.gameObject.SetActive(true);
        Badge2 = CreateRect("Badge2", RectOf(ToastTwo));
        ConfigureRect(RectOf(Badge2), width: 104f, height: 28f, left: 792f, top: 0f, absolute: true);
        ApplyLayoutSizing(RectOf(Badge2), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Badge2), horizontal: false, vertical: false);
        ApplyVerticalLayout(RectOf(Badge2), 0f, 0, 0, 0, 0);
        ApplyStyle(Badge2, fg: "#4A78D4", bg: "#4A78D4", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Badge2.gameObject.SetActive(true);
        BadgeText2 = CreateText("BadgeText2", RectOf(Badge2));
        ConfigureRect(RectOf(BadgeText2), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(BadgeText2), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(BadgeText2), horizontal: false, vertical: false);
        ApplyStyle(BadgeText2, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 8, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(BadgeText2, lineSpacing: null, wrapText: false);
        BadgeText2.text = "STABLE";
        BadgeText2.gameObject.SetActive(true);
        ToastThree = CreateRect("ToastThree", Root);
        ConfigureRect(RectOf(ToastThree), width: null, height: 180f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(ToastThree), ignoreLayout: false, preferredWidth: null, preferredHeight: 180f, flexibleWidth: 1f, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(ToastThree), horizontal: false, vertical: false);
        ApplyStyle(ToastThree, fg: "#101010", bg: "#101010", fontFamily: null, fontSize: null, borderColor: "#7E7E7E", borderWidth: 6f, treatAsIcon: false);
        ToastThree.gameObject.SetActive(true);
        IconPanel3 = CreateRect("IconPanel3", RectOf(ToastThree));
        ConfigureRect(RectOf(IconPanel3), width: 132f, height: 132f, left: 16f, top: 16f, absolute: true);
        ApplyLayoutSizing(RectOf(IconPanel3), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(IconPanel3), horizontal: false, vertical: false);
        ApplyVerticalLayout(RectOf(IconPanel3), 0f, 0, 0, 0, 0);
        ApplyStyle(IconPanel3, fg: "#000000", bg: "#000000", fontFamily: null, fontSize: null, borderColor: "#EAEAEA", borderWidth: 4f, treatAsIcon: false);
        IconPanel3.gameObject.SetActive(true);
        EventIcon3 = CreateText("EventIcon3", RectOf(IconPanel3));
        ConfigureRect(RectOf(EventIcon3), width: 56f, height: 56f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(EventIcon3), ignoreLayout: false, preferredWidth: 56f, preferredHeight: 56f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(EventIcon3), horizontal: false, vertical: false);
        ApplyStyle(EventIcon3, fg: "#FFFFFF", bg: null, fontFamily: "lucide", fontSize: 56, borderColor: null, borderWidth: null, treatAsIcon: true);
        ApplyIconMetrics(EventIcon3, boxWidth: 56f, boxHeight: 56f, baselineOffset: 0f, opticalCentering: true, sizeMode: "fit-box", explicitFontSize: 0f);
        ApplyTextMetrics(EventIcon3, lineSpacing: null, wrapText: false);
        EventIcon3.text = ResolveIconText("moon");
        EventIcon3.gameObject.SetActive(true);
        Content3 = CreateRect("Content3", RectOf(ToastThree));
        ConfigureRect(RectOf(Content3), width: 560f, height: 144f, left: 168f, top: 18f, absolute: true);
        ApplyLayoutSizing(RectOf(Content3), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Content3), horizontal: false, vertical: false);
        ApplyVerticalLayout(RectOf(Content3), 10f, 0, 0, 0, 0);
        ApplyStyle(Content3, fg: "#101010", bg: "#101010", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Content3.gameObject.SetActive(true);
        Title3 = CreateText("Title3", RectOf(Content3));
        ConfigureRect(RectOf(Title3), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Title3), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Title3), horizontal: false, vertical: false);
        ApplyStyle(Title3, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 14, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(Title3, lineSpacing: null, wrapText: false);
        Title3.text = "SHADOW VEIL ACTIVE";
        Title3.gameObject.SetActive(true);
        Body3 = CreateText("Body3", RectOf(Content3));
        ConfigureRect(RectOf(Body3), width: 540f, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Body3), ignoreLayout: false, preferredWidth: 540f, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Body3), horizontal: false, vertical: false);
        ApplyStyle(Body3, fg: "#AAAAAA", bg: null, fontFamily: "Press Start 2P", fontSize: 9, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(Body3, lineSpacing: null, wrapText: true);
        Body3.text = "Enemy scouts have lost visual contact. Maintain silence and move the party through the lower atrium.";
        Body3.gameObject.SetActive(true);
        Progress3 = CreateRect("Progress3", RectOf(Content3));
        ConfigureRect(RectOf(Progress3), width: 540f, height: 22f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Progress3), ignoreLayout: false, preferredWidth: 540f, preferredHeight: 22f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Progress3), horizontal: false, vertical: false);
        ApplyStyle(Progress3, fg: "#1E1E1E", bg: "#1E1E1E", fontFamily: null, fontSize: null, borderColor: "#8C8C8C", borderWidth: 2f, treatAsIcon: false);
        Progress3.gameObject.SetActive(true);
        ProgressFill3 = CreateRect("ProgressFill3", RectOf(Progress3));
        ConfigureRect(RectOf(ProgressFill3), width: 236f, height: 18f, left: null, top: null, absolute: true);
        ApplyLayoutSizing(RectOf(ProgressFill3), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(ProgressFill3), horizontal: false, vertical: false);
        ApplyStyle(ProgressFill3, fg: "#7A5FD4", bg: "#7A5FD4", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        ProgressFill3.gameObject.SetActive(true);
        ProgressText3 = CreateText("ProgressText3", RectOf(Progress3));
        ConfigureRect(RectOf(ProgressText3), width: null, height: null, left: 12f, top: 4f, absolute: true);
        ApplyLayoutSizing(RectOf(ProgressText3), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(ProgressText3), horizontal: false, vertical: false);
        ApplyStyle(ProgressText3, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 9, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(ProgressText3, lineSpacing: null, wrapText: false);
        ProgressText3.text = "VEIL DURATION 43%";
        ProgressText3.gameObject.SetActive(true);
        RewardColumn3 = CreateRect("RewardColumn3", RectOf(ToastThree));
        ConfigureRect(RectOf(RewardColumn3), width: 164f, height: 132f, left: 764f, top: 16f, absolute: true);
        ApplyLayoutSizing(RectOf(RewardColumn3), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(RewardColumn3), horizontal: false, vertical: false);
        ApplyVerticalLayout(RectOf(RewardColumn3), 10f, 12, 12, 12, 12);
        ApplyStyle(RewardColumn3, fg: "#0C0C0C", bg: "#0C0C0C", fontFamily: null, fontSize: null, borderColor: "#7E7E7E", borderWidth: 4f, treatAsIcon: false);
        RewardColumn3.gameObject.SetActive(true);
        Tag3 = CreateText("Tag3", RectOf(RewardColumn3));
        ConfigureRect(RectOf(Tag3), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Tag3), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Tag3), horizontal: false, vertical: false);
        ApplyStyle(Tag3, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 10, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(Tag3, lineSpacing: null, wrapText: false);
        Tag3.text = "UTILITY";
        Tag3.gameObject.SetActive(true);
        Value3 = CreateText("Value3", RectOf(RewardColumn3));
        ConfigureRect(RectOf(Value3), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Value3), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Value3), horizontal: false, vertical: false);
        ApplyStyle(Value3, fg: "#AAAAAA", bg: null, fontFamily: "Press Start 2P", fontSize: 9, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(Value3, lineSpacing: null, wrapText: false);
        Value3.text = "+stealth";
        Value3.gameObject.SetActive(true);
        Time3 = CreateText("Time3", RectOf(RewardColumn3));
        ConfigureRect(RectOf(Time3), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Time3), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Time3), horizontal: false, vertical: false);
        ApplyStyle(Time3, fg: "#AAAAAA", bg: null, fontFamily: "Press Start 2P", fontSize: 9, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(Time3, lineSpacing: null, wrapText: false);
        Time3.text = "00:33";
        Time3.gameObject.SetActive(true);
        Badge3 = CreateRect("Badge3", RectOf(ToastThree));
        ConfigureRect(RectOf(Badge3), width: 128f, height: 28f, left: 780f, top: 0f, absolute: true);
        ApplyLayoutSizing(RectOf(Badge3), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Badge3), horizontal: false, vertical: false);
        ApplyVerticalLayout(RectOf(Badge3), 0f, 0, 0, 0, 0);
        ApplyStyle(Badge3, fg: "#7A5FD4", bg: "#7A5FD4", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Badge3.gameObject.SetActive(true);
        BadgeText3 = CreateText("BadgeText3", RectOf(Badge3));
        ConfigureRect(RectOf(BadgeText3), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(BadgeText3), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(BadgeText3), horizontal: false, vertical: false);
        ApplyStyle(BadgeText3, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 8, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(BadgeText3, lineSpacing: null, wrapText: false);
        BadgeText3.text = "CONCEALED";
        BadgeText3.gameObject.SetActive(true);
        ViewModel = viewModel;
    }

    private CombatToastStackView(RectTransform root, ICombatToastStackViewModel? viewModel)
    {
        Root = root;
        ToastOne = RequireRect(Root, "ToastOne");
        IconPanel = RequireRect(Root, "ToastOne/IconPanel");
        EventIcon = RequireComponent<Text>(Root, "ToastOne/IconPanel/EventIcon");
        Content = RequireRect(Root, "ToastOne/Content");
        Title = RequireComponent<Text>(Root, "ToastOne/Content/Title");
        Body = RequireComponent<Text>(Root, "ToastOne/Content/Body");
        Progress = RequireRect(Root, "ToastOne/Content/Progress");
        ProgressFill = RequireRect(Root, "ToastOne/Content/Progress/ProgressFill");
        ProgressText = RequireComponent<Text>(Root, "ToastOne/Content/Progress/ProgressText");
        RewardColumn = RequireRect(Root, "ToastOne/RewardColumn");
        Tag = RequireComponent<Text>(Root, "ToastOne/RewardColumn/Tag");
        Value = RequireComponent<Text>(Root, "ToastOne/RewardColumn/Value");
        Time = RequireComponent<Text>(Root, "ToastOne/RewardColumn/Time");
        Badge = RequireRect(Root, "ToastOne/Badge");
        BadgeText = RequireComponent<Text>(Root, "ToastOne/Badge/BadgeText");
        ToastTwo = RequireRect(Root, "ToastTwo");
        IconPanel2 = RequireRect(Root, "ToastTwo/IconPanel2");
        EventIcon2 = RequireComponent<Text>(Root, "ToastTwo/IconPanel2/EventIcon2");
        Content2 = RequireRect(Root, "ToastTwo/Content2");
        Title2 = RequireComponent<Text>(Root, "ToastTwo/Content2/Title2");
        Body2 = RequireComponent<Text>(Root, "ToastTwo/Content2/Body2");
        Progress2 = RequireRect(Root, "ToastTwo/Content2/Progress2");
        ProgressFill2 = RequireRect(Root, "ToastTwo/Content2/Progress2/ProgressFill2");
        ProgressText2 = RequireComponent<Text>(Root, "ToastTwo/Content2/Progress2/ProgressText2");
        RewardColumn2 = RequireRect(Root, "ToastTwo/RewardColumn2");
        Tag2 = RequireComponent<Text>(Root, "ToastTwo/RewardColumn2/Tag2");
        Value2 = RequireComponent<Text>(Root, "ToastTwo/RewardColumn2/Value2");
        Time2 = RequireComponent<Text>(Root, "ToastTwo/RewardColumn2/Time2");
        Badge2 = RequireRect(Root, "ToastTwo/Badge2");
        BadgeText2 = RequireComponent<Text>(Root, "ToastTwo/Badge2/BadgeText2");
        ToastThree = RequireRect(Root, "ToastThree");
        IconPanel3 = RequireRect(Root, "ToastThree/IconPanel3");
        EventIcon3 = RequireComponent<Text>(Root, "ToastThree/IconPanel3/EventIcon3");
        Content3 = RequireRect(Root, "ToastThree/Content3");
        Title3 = RequireComponent<Text>(Root, "ToastThree/Content3/Title3");
        Body3 = RequireComponent<Text>(Root, "ToastThree/Content3/Body3");
        Progress3 = RequireRect(Root, "ToastThree/Content3/Progress3");
        ProgressFill3 = RequireRect(Root, "ToastThree/Content3/Progress3/ProgressFill3");
        ProgressText3 = RequireComponent<Text>(Root, "ToastThree/Content3/Progress3/ProgressText3");
        RewardColumn3 = RequireRect(Root, "ToastThree/RewardColumn3");
        Tag3 = RequireComponent<Text>(Root, "ToastThree/RewardColumn3/Tag3");
        Value3 = RequireComponent<Text>(Root, "ToastThree/RewardColumn3/Value3");
        Time3 = RequireComponent<Text>(Root, "ToastThree/RewardColumn3/Time3");
        Badge3 = RequireRect(Root, "ToastThree/Badge3");
        BadgeText3 = RequireComponent<Text>(Root, "ToastThree/Badge3/BadgeText3");
        ViewModel = viewModel;
    }

    public static CombatToastStackView Bind(RectTransform root, ICombatToastStackViewModel? viewModel = null) => new(root, viewModel);

    public void Refresh()
    {
        if (_viewModel == null) return;
    }

    private void OnChanged(object? sender, PropertyChangedEventArgs e) => Refresh();

    private static RectTransform CreateRect(string name, Transform? parent){var go=new GameObject(name,typeof(RectTransform));var rect=go.GetComponent<RectTransform>();if(parent!=null)rect.SetParent(parent,false);rect.localScale=Vector3.one;rect.anchorMin=new Vector2(0f,1f);rect.anchorMax=new Vector2(0f,1f);rect.pivot=new Vector2(0f,1f);return rect;}
    private static RectTransform RequireRect(Transform root,string path){var target=root.Find(path);if(target==null||!target.TryGetComponent<RectTransform>(out var rect))throw new InvalidOperationException($"Required RectTransform '{path}' was not found beneath '{root.name}'.");return rect;}
    private static T RequireComponent<T>(Transform root,string path) where T : Component{var target=root.Find(path);if(target==null||!target.TryGetComponent<T>(out var component))throw new InvalidOperationException($"Required component '{typeof(T).Name}' at '{path}' was not found beneath '{root.name}'.");return component;}
    private static Text CreateText(string name, Transform? parent){var rect=CreateRect(name,parent);rect.gameObject.AddComponent<CanvasRenderer>();var text=rect.gameObject.AddComponent<Text>();text.font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");text.horizontalOverflow=HorizontalWrapMode.Overflow;text.verticalOverflow=VerticalWrapMode.Overflow;text.supportRichText=true;return text;}
    private static Image CreateImage(string name, Transform? parent){var rect=CreateRect(name,parent);rect.gameObject.AddComponent<CanvasRenderer>();return rect.gameObject.AddComponent<Image>();}
    private static Button CreateButton(string name, Transform? parent){var image=CreateImage(name,parent);var button=image.gameObject.AddComponent<Button>();button.targetGraphic=image;var label=CreateText("Label",image.transform);Stretch(RectOf(label));label.alignment=TextAnchor.MiddleCenter;return button;}
    private static Toggle CreateToggle(string name, Transform? parent){var root=CreateRect(name,parent);var toggle=root.gameObject.AddComponent<Toggle>();var bg=CreateImage("Background",root);ConfigureRect(RectOf(bg),18f,18f,0f,0f,true);var check=CreateImage("Checkmark",RectOf(bg));Stretch(RectOf(check));var label=CreateText("Label",root);ConfigureRect(RectOf(label),null,18f,24f,0f,true);toggle.targetGraphic=bg;toggle.graphic=check;return toggle;}
    private static Slider CreateSlider(string name, Transform? parent,bool interactable){var root=CreateRect(name,parent);var bg=CreateImage("Background",root);Stretch(RectOf(bg));var fillArea=CreateRect("Fill Area",root);Stretch(fillArea);var fill=CreateImage("Fill",fillArea);Stretch(RectOf(fill));var handleArea=CreateRect("Handle Slide Area",root);Stretch(handleArea);var handle=CreateImage("Handle",handleArea);ConfigureRect(RectOf(handle),12f,12f,0f,0f,true);var slider=root.gameObject.AddComponent<Slider>();slider.fillRect=RectOf(fill);slider.handleRect=RectOf(handle);slider.targetGraphic=handle;slider.interactable=interactable;return slider;}
    private static InputField CreateInput(string name, Transform? parent,bool multiline){var bg=CreateImage(name,parent);var text=CreateText("Text",bg.transform);Stretch(RectOf(text),6f,6f,6f,6f);text.alignment=multiline?TextAnchor.UpperLeft:TextAnchor.MiddleLeft;var input=bg.gameObject.AddComponent<InputField>();input.textComponent=text;input.lineType=multiline?InputField.LineType.MultiLineNewline:InputField.LineType.SingleLine;return input;}
    private static ScrollRect CreateScroll(string name, Transform? parent,out RectTransform content){var root=CreateImage(name,parent);var viewport=CreateImage("Viewport",root.transform);Stretch(RectOf(viewport));viewport.gameObject.AddComponent<Mask>().showMaskGraphic=false;content=CreateRect("Content",RectOf(viewport));Stretch(content);ApplyVerticalLayout(content,0f,0,0,0,0);var scroll=root.gameObject.AddComponent<ScrollRect>();scroll.viewport=RectOf(viewport);scroll.content=content;scroll.horizontal=false;scroll.vertical=true;return scroll;}
    private static void ApplyHorizontalLayout(RectTransform rect,float spacing,int paddingLeft,int paddingRight,int paddingTop,int paddingBottom){var group=rect.gameObject.GetComponent<HorizontalLayoutGroup>()??rect.gameObject.AddComponent<HorizontalLayoutGroup>();group.spacing=spacing;group.padding=new RectOffset(paddingLeft,paddingRight,paddingTop,paddingBottom);group.childControlWidth=true;group.childControlHeight=true;group.childForceExpandWidth=false;group.childForceExpandHeight=false;}
    private static void ApplyVerticalLayout(RectTransform rect,float spacing,int paddingLeft,int paddingRight,int paddingTop,int paddingBottom){var group=rect.gameObject.GetComponent<VerticalLayoutGroup>()??rect.gameObject.AddComponent<VerticalLayoutGroup>();group.spacing=spacing;group.padding=new RectOffset(paddingLeft,paddingRight,paddingTop,paddingBottom);group.childControlWidth=true;group.childControlHeight=true;group.childForceExpandWidth=false;group.childForceExpandHeight=false;}
    private static void ApplyLayoutSizing(RectTransform rect,bool ignoreLayout,float? preferredWidth,float? preferredHeight,float? flexibleWidth,float? flexibleHeight){var element=rect.gameObject.GetComponent<LayoutElement>()??rect.gameObject.AddComponent<LayoutElement>();element.ignoreLayout=ignoreLayout;element.preferredWidth=preferredWidth??-1f;element.preferredHeight=preferredHeight??-1f;element.flexibleWidth=flexibleWidth??-1f;element.flexibleHeight=flexibleHeight??-1f;}
    private static void ApplyContentSizeFit(RectTransform rect,bool horizontal,bool vertical){var fitter=rect.gameObject.GetComponent<ContentSizeFitter>()??rect.gameObject.AddComponent<ContentSizeFitter>();fitter.horizontalFit=horizontal?ContentSizeFitter.FitMode.PreferredSize:ContentSizeFitter.FitMode.Unconstrained;fitter.verticalFit=vertical?ContentSizeFitter.FitMode.PreferredSize:ContentSizeFitter.FitMode.Unconstrained;}
    private static void ConfigureRect(RectTransform rect,float? width,float? height,float? left,float? top,bool absolute){if(absolute){rect.anchorMin=new Vector2(0f,1f);rect.anchorMax=new Vector2(0f,1f);rect.pivot=new Vector2(0f,1f);rect.anchoredPosition=new Vector2(left??0f,-(top??0f));}if(width.HasValue)rect.SetSizeWithCurrentAnchors(RectTransform.Axis.Horizontal,width.Value);if(height.HasValue)rect.SetSizeWithCurrentAnchors(RectTransform.Axis.Vertical,height.Value);}
    private static void ApplyRectAnchorPreset(RectTransform rect,string preset){switch(NormalizeRectPreset(preset)){case "top-left":case "start":rect.anchorMin=new Vector2(0f,1f);rect.anchorMax=new Vector2(0f,1f);break;case "top-center":rect.anchorMin=new Vector2(0.5f,1f);rect.anchorMax=new Vector2(0.5f,1f);break;case "top-right":case "end":rect.anchorMin=new Vector2(1f,1f);rect.anchorMax=new Vector2(1f,1f);break;case "center":case "middle-center":rect.anchorMin=new Vector2(0.5f,0.5f);rect.anchorMax=new Vector2(0.5f,0.5f);break;case "stretch":rect.anchorMin=new Vector2(0f,0f);rect.anchorMax=new Vector2(1f,1f);break;case "stretch-horizontal":rect.anchorMin=new Vector2(0f,1f);rect.anchorMax=new Vector2(1f,1f);break;case "stretch-vertical":rect.anchorMin=new Vector2(0f,0f);rect.anchorMax=new Vector2(0f,1f);break;}}
    private static void ApplyRectPivotPreset(RectTransform rect,string preset){switch(NormalizeRectPreset(preset)){case "top-left":case "start":rect.pivot=new Vector2(0f,1f);break;case "top-center":rect.pivot=new Vector2(0.5f,1f);break;case "top-right":case "end":rect.pivot=new Vector2(1f,1f);break;case "center":case "middle-center":rect.pivot=new Vector2(0.5f,0.5f);break;case "bottom-left":rect.pivot=new Vector2(0f,0f);break;case "bottom-center":rect.pivot=new Vector2(0.5f,0f);break;case "bottom-right":rect.pivot=new Vector2(1f,0f);break;}}
    private static void ApplyRectTransformMode(RectTransform rect,string mode){switch(NormalizeRectPreset(mode)){case "stretch-parent":case "stretch":Stretch(rect);break;case "absolute-overlay":rect.anchorMin=new Vector2(0f,1f);rect.anchorMax=new Vector2(0f,1f);rect.pivot=new Vector2(0f,1f);break;case "top-left":ApplyRectAnchorPreset(rect,"top-left");ApplyRectPivotPreset(rect,"top-left");break;case "center":ApplyRectAnchorPreset(rect,"center");ApplyRectPivotPreset(rect,"center");break;}}
    private static void ApplyEdgeInsetPolicy(RectTransform rect,string policy){switch(NormalizeRectPreset(policy)){case "match-parent":Stretch(rect);break;case "zero-offsets":rect.offsetMin=Vector2.zero;rect.offsetMax=Vector2.zero;break;}}
    private static string NormalizeRectPreset(string? value)=>string.IsNullOrWhiteSpace(value)?string.Empty:value.Trim().ToLowerInvariant();
    private static void Stretch(RectTransform rect,float left=0f,float right=0f,float top=0f,float bottom=0f){rect.anchorMin=new Vector2(0f,0f);rect.anchorMax=new Vector2(1f,1f);rect.pivot=new Vector2(0.5f,0.5f);rect.offsetMin=new Vector2(left,bottom);rect.offsetMax=new Vector2(-right,-top);}
    private static void ApplyStyle(Component component,string? fg,string? bg,string? fontFamily,int? fontSize,string? borderColor,float? borderWidth,bool treatAsIcon){if(!string.IsNullOrWhiteSpace(bg))EnsureImage(component.gameObject).color=ParseColor(bg,Color.white);if(!string.IsNullOrWhiteSpace(borderColor)&&borderWidth.HasValue&&borderWidth.Value>0f)ApplyBorder(component.gameObject,ParseColor(borderColor,Color.white),borderWidth.Value);if(component is Text text){if(!string.IsNullOrWhiteSpace(fg))text.color=ParseColor(fg,text.color);if(!string.IsNullOrWhiteSpace(fontFamily)&&TryFont(fontFamily,out var font))text.font=font;if(fontSize.HasValue)text.fontSize=fontSize.Value;if(treatAsIcon){text.alignment=TextAnchor.MiddleCenter;text.horizontalOverflow=HorizontalWrapMode.Overflow;text.verticalOverflow=VerticalWrapMode.Overflow;}}else if(component is Button button&&TryLabel(button.gameObject,out var label)){if(!string.IsNullOrWhiteSpace(fg))label.color=ParseColor(fg,label.color);if(!string.IsNullOrWhiteSpace(fontFamily)&&TryFont(fontFamily,out var font))label.font=font;if(fontSize.HasValue)label.fontSize=fontSize.Value;}else if(component is Toggle toggle&&TryLabel(toggle.gameObject,out var toggleLabel)){if(!string.IsNullOrWhiteSpace(fg))toggleLabel.color=ParseColor(fg,toggleLabel.color);if(!string.IsNullOrWhiteSpace(fontFamily)&&TryFont(fontFamily,out var font))toggleLabel.font=font;if(fontSize.HasValue)toggleLabel.fontSize=fontSize.Value;}else if(component is InputField input&&input.textComponent!=null){if(!string.IsNullOrWhiteSpace(fg))input.textComponent.color=ParseColor(fg,input.textComponent.color);if(!string.IsNullOrWhiteSpace(fontFamily)&&TryFont(fontFamily,out var font))input.textComponent.font=font;if(fontSize.HasValue)input.textComponent.fontSize=fontSize.Value;}}
    private static void ApplyIconMetrics(Component component,float boxWidth,float boxHeight,float baselineOffset,bool opticalCentering,string sizeMode,float explicitFontSize){if(component is not Text text)return;var iconSize=explicitFontSize>0f?explicitFontSize:string.Equals(sizeMode,"match-height",StringComparison.OrdinalIgnoreCase)?Mathf.Max(1f,boxHeight):Mathf.Max(1f,Mathf.Min(boxWidth,boxHeight));text.fontSize=Mathf.RoundToInt(iconSize);text.alignment=opticalCentering?TextAnchor.MiddleCenter:TextAnchor.UpperCenter;text.horizontalOverflow=HorizontalWrapMode.Overflow;text.verticalOverflow=VerticalWrapMode.Overflow;var rect=RectOf(text);if(opticalCentering&&Mathf.Approximately(baselineOffset,0f)&&boxHeight>iconSize){baselineOffset=-1f;}rect.anchoredPosition=new Vector2(rect.anchoredPosition.x,baselineOffset);}
    private static void ApplyTextMetrics(Component component,float? lineSpacing,bool wrapText){if(component is Text text){if(lineSpacing.HasValue)text.lineSpacing=lineSpacing.Value;text.horizontalOverflow=wrapText?HorizontalWrapMode.Wrap:HorizontalWrapMode.Overflow;text.verticalOverflow=VerticalWrapMode.Overflow;return;}if(component is Button button&&TryLabel(button.gameObject,out var label)){if(lineSpacing.HasValue)label.lineSpacing=lineSpacing.Value;label.horizontalOverflow=wrapText?HorizontalWrapMode.Wrap:HorizontalWrapMode.Overflow;label.verticalOverflow=VerticalWrapMode.Overflow;return;}if(component is Toggle toggle&&TryLabel(toggle.gameObject,out var toggleLabel)){if(lineSpacing.HasValue)toggleLabel.lineSpacing=lineSpacing.Value;toggleLabel.horizontalOverflow=wrapText?HorizontalWrapMode.Wrap:HorizontalWrapMode.Overflow;toggleLabel.verticalOverflow=VerticalWrapMode.Overflow;return;}if(component is InputField input&&input.textComponent!=null){if(lineSpacing.HasValue)input.textComponent.lineSpacing=lineSpacing.Value;input.textComponent.horizontalOverflow=wrapText?HorizontalWrapMode.Wrap:HorizontalWrapMode.Overflow;input.textComponent.verticalOverflow=VerticalWrapMode.Overflow;}}
    private static void ApplyEnabled(Component component,bool enabled){if(component is Selectable selectable){selectable.interactable=enabled;return;}component.gameObject.SetActive(enabled);}
    private static void SetButtonText(Button button,string? value){if(TryLabel(button.gameObject,out var label))label.text=value??string.Empty;}
    private static void SetToggleText(Toggle toggle,string? value){if(TryLabel(toggle.gameObject,out var label))label.text=value??string.Empty;}
    private static void SetImage(Image image,string? path){image.sprite=string.IsNullOrWhiteSpace(path)?null:Resources.Load<Sprite>(path);}
    private static bool TryLabel(GameObject go,out Text label){label=go.GetComponentInChildren<Text>(true);return label!=null;}
    private static bool TryFont(string familyName,out Font font){var resourcePath=familyName switch{"Press Start 2P"=>"BoomHudFonts/PressStart2P-Regular","lucide"=>"BoomHudFonts/lucide",_=>familyName};font=Resources.Load<Font>(resourcePath)??Resources.Load<Font>(familyName);return font!=null;}
    private static void ApplyBorder(GameObject go,Color color,float width){var outline=go.GetComponent<Outline>()??go.AddComponent<Outline>();outline.effectColor=color;outline.effectDistance=new Vector2(width,-width);outline.useGraphicAlpha=false;}
    private static Image EnsureImage(GameObject go){var image=go.GetComponent<Image>();if(image==null){if(go.GetComponent<CanvasRenderer>()==null)go.AddComponent<CanvasRenderer>();image=go.AddComponent<Image>();}return image;}
    private static RectTransform RectOf(Component component)=>component.GetComponent<RectTransform>();
    private static RectTransform RectOf(RectTransform rect)=>rect;
    private static string ResolveIconText(string? value)=>value switch{"cross"=>"\uE1E5","flame"=>"\uE0D2","flask-conical"=>"\uE0D5","moon"=>"\uE11E","shield"=>"\uE158","sparkles"=>"\uE412","sword"=>"\uE2B3","swords"=>"\uE2B4","wand"=>"\uE246","wand-2"=>"\uE357","wand-sparkles"=>"\uE357",_=>value??string.Empty};
    private static bool AsBool(object? value,bool fallback)=>value is bool b?b:value is string s&&bool.TryParse(s,out var parsed)?parsed:fallback;
    private static float AsFloat(object? value)=>value switch{float f=>f,double d=>(float)d,int i=>i,long l=>l,decimal m=>(float)m,string s when float.TryParse(s,NumberStyles.Float,CultureInfo.InvariantCulture,out var parsed)=>parsed,_=>0f};
    private static string AsString(object? value)=>value?.ToString()??string.Empty;
    private static Color ParseColor(string? value,Color fallback)=>!string.IsNullOrWhiteSpace(value)&&ColorUtility.TryParseHtmlString(value,out var color)?color:fallback;}
}
