// <auto-generated>
// Generated by BoomHud.Gen.UGui from CombatToastStack
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud.UGui
{
public interface ICombatToastStackViewModel : INotifyPropertyChanged
{
}
}
