// <auto-generated>
// Generated by BoomHud.Gen.UGui from FortniteInventory
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud.UGui
{
public interface IFortniteInventoryViewModel : INotifyPropertyChanged
{
}
}
