// <auto-generated>
// Generated by BoomHud.Gen.UGui from SyntheticContainer6CA54749
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud.UGui
{
public interface ISyntheticContainer6CA54749ViewModel : INotifyPropertyChanged
{
}
}
