// <auto-generated>
// Generated by BoomHud.Gen.UGui from SyntheticContainer6397E5DC
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud.UGui
{
public interface ISyntheticContainer6397E5DCViewModel : INotifyPropertyChanged
{
}
}
