// <auto-generated>
// Generated by BoomHud.Gen.UGui from SyntheticContainerA9D40D97
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud.UGui
{
public interface ISyntheticContainerA9D40D97ViewModel : INotifyPropertyChanged
{
}
}
