// <auto-generated>
// Generated by BoomHud.Gen.UGui from SyntheticContainer33503E91
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud.UGui
{
public interface ISyntheticContainer33503E91ViewModel : INotifyPropertyChanged
{
}
}
