// <auto-generated>
// Generated by BoomHud.Gen.UGui from SyntheticContainerFA4632C6
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud.UGui
{
public interface ISyntheticContainerFA4632C6ViewModel : INotifyPropertyChanged
{
}
}
