// <auto-generated>
// Generated by BoomHud.Gen.UGui from SyntheticContainer100280A5
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud.UGui
{
public interface ISyntheticContainer100280A5ViewModel : INotifyPropertyChanged
{
}
}
