// <auto-generated>
// Generated by BoomHud.Gen.UGui from SyntheticContainer640002D6
// </auto-generated>

#nullable enable

using System.ComponentModel;

namespace Generated.Hud.UGui
{
public interface ISyntheticContainer640002D6ViewModel : INotifyPropertyChanged
{
}
}
