// <auto-generated>
// Generated by BoomHud.Gen.UGui from QuestSidebar
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using PropertyChangedEventArgs = System.ComponentModel.PropertyChangedEventArgs;
using System.Globalization;
using UnityEngine;
using UnityEngine.UI;

namespace Generated.Hud.UGui
{
public sealed class QuestSidebarView
{
    private readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, object?>>? _componentOverrides;
    private IQuestSidebarViewModel? _viewModel;
    public RectTransform Root { get; }
    public RectTransform Header { get; }
    public Text Title { get; }
    public Text Zone { get; }
    public RectTransform MinimapCard { get; }
    public Text MinimapLabel { get; }
    public RectTransform MapGrid { get; }
    public RectTransform Row0 { get; }
    public RectTransform Row1 { get; }
    public RectTransform Cell10 { get; }
    public RectTransform Cell11 { get; }
    public RectTransform Cell12 { get; }
    public RectTransform Cell13 { get; }
    public RectTransform Cell14 { get; }
    public RectTransform Cell15 { get; }
    public RectTransform Row2 { get; }
    public RectTransform Cell20 { get; }
    public RectTransform Cell21 { get; }
    public RectTransform Cell22 { get; }
    public RectTransform Cell23 { get; }
    public RectTransform Cell24 { get; }
    public RectTransform Cell25 { get; }
    public RectTransform Row3 { get; }
    public RectTransform Row4 { get; }
    public RectTransform Cell40 { get; }
    public RectTransform Cell41 { get; }
    public RectTransform Cell42 { get; }
    public RectTransform Cell43 { get; }
    public RectTransform Cell44 { get; }
    public RectTransform Cell45 { get; }
    public RectTransform ObjectiveCard { get; }
    public Text ObjectivesLabel { get; }
    public RectTransform Objective1 { get; }
    public RectTransform Objective2 { get; }
    public RectTransform Objective3 { get; }
    public RectTransform ResourceCard { get; }
    public Text ResourcesLabel { get; }
    public RectTransform HealthBar { get; }
    public RectTransform HealthFill { get; }
    public Text HealthText { get; }
    public RectTransform ManaBar { get; }
    public RectTransform ManaFill { get; }
    public Text ManaText { get; }
    public RectTransform SupplyBar { get; }
    public RectTransform SupplyFill { get; }
    public Text SupplyText { get; }

    public IQuestSidebarViewModel? ViewModel
    {
        get => _viewModel;
        set
        {
            if (ReferenceEquals(_viewModel, value)) return;
            if (_viewModel != null) _viewModel.PropertyChanged -= OnChanged;
            _viewModel = value;
            if (_viewModel != null) _viewModel.PropertyChanged += OnChanged;
            Refresh();
        }
    }

    public QuestSidebarView(Transform? parent = null, IQuestSidebarViewModel? viewModel = null, IReadOnlyDictionary<string, IReadOnlyDictionary<string, object?>>? componentOverrides = null)
    {
        _componentOverrides = componentOverrides;
        Root = CreateRect("QuestSidebarRoot", parent);
        ConfigureRect(Root, width: 420f, height: 960f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(Root, ignoreLayout: false, preferredWidth: 420f, preferredHeight: 960f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(Root, horizontal: false, vertical: false);
        ApplyVerticalLayout(Root, 16f, 16, 16, 16, 16);
        ApplyStyle(Root, fg: "#070707", bg: "#070707", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Root.gameObject.SetActive(true);
        Header = CreateRect("Header", Root);
        ConfigureRect(RectOf(Header), width: null, height: 64f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Header), ignoreLayout: false, preferredWidth: null, preferredHeight: 64f, flexibleWidth: 1f, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Header), horizontal: false, vertical: false);
        ApplyVerticalLayout(RectOf(Header), 6f, 12, 12, 12, 12);
        ApplyStyle(Header, fg: "#111111", bg: "#111111", fontFamily: null, fontSize: null, borderColor: "#7E7E7E", borderWidth: 4f, treatAsIcon: false);
        Header.gameObject.SetActive(true);
        Title = CreateText("Title", RectOf(Header));
        ConfigureRect(RectOf(Title), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Title), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Title), horizontal: false, vertical: false);
        ApplyStyle(Title, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 14, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(Title, lineSpacing: null, wrapText: false);
        Title.text = "QuestSidebar";
        Title.gameObject.SetActive(true);
        Zone = CreateText("Zone", RectOf(Header));
        ConfigureRect(RectOf(Zone), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Zone), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Zone), horizontal: false, vertical: false);
        ApplyStyle(Zone, fg: "#AAAAAA", bg: null, fontFamily: "Press Start 2P", fontSize: 9, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(Zone, lineSpacing: null, wrapText: false);
        Zone.text = "DARKSTONE DISTRICT";
        Zone.gameObject.SetActive(true);
        MinimapCard = CreateRect("MinimapCard", Root);
        ConfigureRect(RectOf(MinimapCard), width: null, height: 272f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(MinimapCard), ignoreLayout: false, preferredWidth: null, preferredHeight: 272f, flexibleWidth: 1f, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(MinimapCard), horizontal: false, vertical: false);
        ApplyVerticalLayout(RectOf(MinimapCard), 8f, 12, 12, 12, 12);
        ApplyStyle(MinimapCard, fg: "#111111", bg: "#111111", fontFamily: null, fontSize: null, borderColor: "#7E7E7E", borderWidth: 4f, treatAsIcon: false);
        MinimapCard.gameObject.SetActive(true);
        MinimapLabel = CreateText("MinimapLabel", RectOf(MinimapCard));
        ConfigureRect(RectOf(MinimapLabel), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(MinimapLabel), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(MinimapLabel), horizontal: false, vertical: false);
        ApplyStyle(MinimapLabel, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 10, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(MinimapLabel, lineSpacing: null, wrapText: false);
        MinimapLabel.text = "TACTICAL MAP";
        MinimapLabel.gameObject.SetActive(true);
        MapGrid = CreateRect("MapGrid", RectOf(MinimapCard));
        ConfigureRect(RectOf(MapGrid), width: null, height: 220f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(MapGrid), ignoreLayout: false, preferredWidth: null, preferredHeight: 220f, flexibleWidth: 1f, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(MapGrid), horizontal: false, vertical: false);
        ApplyVerticalLayout(RectOf(MapGrid), 4f, 8, 8, 8, 8);
        ApplyStyle(MapGrid, fg: "#000000", bg: "#000000", fontFamily: null, fontSize: null, borderColor: "#7E7E7E", borderWidth: 4f, treatAsIcon: false);
        MapGrid.gameObject.SetActive(true);
        var row0View = new SyntheticContainer9463CA59View(RectOf(MapGrid), null, null);
        Row0 = row0View.Root;
        Row0.name = "Row0";
        Row1 = CreateRect("Row1", RectOf(MapGrid));
        ConfigureRect(RectOf(Row1), width: null, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Row1), ignoreLayout: false, preferredWidth: null, preferredHeight: 32f, flexibleWidth: 1f, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Row1), horizontal: false, vertical: false);
        ApplyHorizontalLayout(RectOf(Row1), 4f, 0, 0, 0, 0);
        ApplyStyle(Row1, fg: "#000000", bg: "#000000", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Row1.gameObject.SetActive(true);
        Cell10 = CreateRect("Cell10", RectOf(Row1));
        ConfigureRect(RectOf(Cell10), width: 32f, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Cell10), ignoreLayout: false, preferredWidth: 32f, preferredHeight: 32f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Cell10), horizontal: false, vertical: false);
        ApplyStyle(Cell10, fg: "#232323", bg: "#232323", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Cell10.gameObject.SetActive(true);
        Cell11 = CreateRect("Cell11", RectOf(Row1));
        ConfigureRect(RectOf(Cell11), width: 32f, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Cell11), ignoreLayout: false, preferredWidth: 32f, preferredHeight: 32f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Cell11), horizontal: false, vertical: false);
        ApplyStyle(Cell11, fg: "#232323", bg: "#232323", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Cell11.gameObject.SetActive(true);
        Cell12 = CreateRect("Cell12", RectOf(Row1));
        ConfigureRect(RectOf(Cell12), width: 32f, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Cell12), ignoreLayout: false, preferredWidth: 32f, preferredHeight: 32f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Cell12), horizontal: false, vertical: false);
        ApplyStyle(Cell12, fg: "#3D6A3D", bg: "#3D6A3D", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Cell12.gameObject.SetActive(true);
        Cell13 = CreateRect("Cell13", RectOf(Row1));
        ConfigureRect(RectOf(Cell13), width: 32f, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Cell13), ignoreLayout: false, preferredWidth: 32f, preferredHeight: 32f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Cell13), horizontal: false, vertical: false);
        ApplyStyle(Cell13, fg: "#232323", bg: "#232323", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Cell13.gameObject.SetActive(true);
        Cell14 = CreateRect("Cell14", RectOf(Row1));
        ConfigureRect(RectOf(Cell14), width: 32f, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Cell14), ignoreLayout: false, preferredWidth: 32f, preferredHeight: 32f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Cell14), horizontal: false, vertical: false);
        ApplyStyle(Cell14, fg: "#6C4B1E", bg: "#6C4B1E", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Cell14.gameObject.SetActive(true);
        Cell15 = CreateRect("Cell15", RectOf(Row1));
        ConfigureRect(RectOf(Cell15), width: 32f, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Cell15), ignoreLayout: false, preferredWidth: 32f, preferredHeight: 32f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Cell15), horizontal: false, vertical: false);
        ApplyStyle(Cell15, fg: "#232323", bg: "#232323", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Cell15.gameObject.SetActive(true);
        Row2 = CreateRect("Row2", RectOf(MapGrid));
        ConfigureRect(RectOf(Row2), width: null, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Row2), ignoreLayout: false, preferredWidth: null, preferredHeight: 32f, flexibleWidth: 1f, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Row2), horizontal: false, vertical: false);
        ApplyHorizontalLayout(RectOf(Row2), 4f, 0, 0, 0, 0);
        ApplyStyle(Row2, fg: "#000000", bg: "#000000", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Row2.gameObject.SetActive(true);
        Cell20 = CreateRect("Cell20", RectOf(Row2));
        ConfigureRect(RectOf(Cell20), width: 32f, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Cell20), ignoreLayout: false, preferredWidth: 32f, preferredHeight: 32f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Cell20), horizontal: false, vertical: false);
        ApplyStyle(Cell20, fg: "#232323", bg: "#232323", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Cell20.gameObject.SetActive(true);
        Cell21 = CreateRect("Cell21", RectOf(Row2));
        ConfigureRect(RectOf(Cell21), width: 32f, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Cell21), ignoreLayout: false, preferredWidth: 32f, preferredHeight: 32f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Cell21), horizontal: false, vertical: false);
        ApplyStyle(Cell21, fg: "#232323", bg: "#232323", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Cell21.gameObject.SetActive(true);
        Cell22 = CreateRect("Cell22", RectOf(Row2));
        ConfigureRect(RectOf(Cell22), width: 32f, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Cell22), ignoreLayout: false, preferredWidth: 32f, preferredHeight: 32f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Cell22), horizontal: false, vertical: false);
        ApplyStyle(Cell22, fg: "#3D6A3D", bg: "#3D6A3D", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Cell22.gameObject.SetActive(true);
        Cell23 = CreateRect("Cell23", RectOf(Row2));
        ConfigureRect(RectOf(Cell23), width: 32f, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Cell23), ignoreLayout: false, preferredWidth: 32f, preferredHeight: 32f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Cell23), horizontal: false, vertical: false);
        ApplyStyle(Cell23, fg: "#4A78D4", bg: "#4A78D4", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Cell23.gameObject.SetActive(true);
        Cell24 = CreateRect("Cell24", RectOf(Row2));
        ConfigureRect(RectOf(Cell24), width: 32f, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Cell24), ignoreLayout: false, preferredWidth: 32f, preferredHeight: 32f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Cell24), horizontal: false, vertical: false);
        ApplyStyle(Cell24, fg: "#6C4B1E", bg: "#6C4B1E", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Cell24.gameObject.SetActive(true);
        Cell25 = CreateRect("Cell25", RectOf(Row2));
        ConfigureRect(RectOf(Cell25), width: 32f, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Cell25), ignoreLayout: false, preferredWidth: 32f, preferredHeight: 32f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Cell25), horizontal: false, vertical: false);
        ApplyStyle(Cell25, fg: "#232323", bg: "#232323", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Cell25.gameObject.SetActive(true);
        var row3View = new SyntheticContainer9463CA59View(RectOf(MapGrid), null, null);
        Row3 = row3View.Root;
        Row3.name = "Row3";
        Row4 = CreateRect("Row4", RectOf(MapGrid));
        ConfigureRect(RectOf(Row4), width: null, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Row4), ignoreLayout: false, preferredWidth: null, preferredHeight: 32f, flexibleWidth: 1f, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Row4), horizontal: false, vertical: false);
        ApplyHorizontalLayout(RectOf(Row4), 4f, 0, 0, 0, 0);
        ApplyStyle(Row4, fg: "#000000", bg: "#000000", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Row4.gameObject.SetActive(true);
        Cell40 = CreateRect("Cell40", RectOf(Row4));
        ConfigureRect(RectOf(Cell40), width: 32f, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Cell40), ignoreLayout: false, preferredWidth: 32f, preferredHeight: 32f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Cell40), horizontal: false, vertical: false);
        ApplyStyle(Cell40, fg: "#232323", bg: "#232323", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Cell40.gameObject.SetActive(true);
        Cell41 = CreateRect("Cell41", RectOf(Row4));
        ConfigureRect(RectOf(Cell41), width: 32f, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Cell41), ignoreLayout: false, preferredWidth: 32f, preferredHeight: 32f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Cell41), horizontal: false, vertical: false);
        ApplyStyle(Cell41, fg: "#232323", bg: "#232323", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Cell41.gameObject.SetActive(true);
        Cell42 = CreateRect("Cell42", RectOf(Row4));
        ConfigureRect(RectOf(Cell42), width: 32f, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Cell42), ignoreLayout: false, preferredWidth: 32f, preferredHeight: 32f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Cell42), horizontal: false, vertical: false);
        ApplyStyle(Cell42, fg: "#232323", bg: "#232323", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Cell42.gameObject.SetActive(true);
        Cell43 = CreateRect("Cell43", RectOf(Row4));
        ConfigureRect(RectOf(Cell43), width: 32f, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Cell43), ignoreLayout: false, preferredWidth: 32f, preferredHeight: 32f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Cell43), horizontal: false, vertical: false);
        ApplyStyle(Cell43, fg: "#232323", bg: "#232323", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Cell43.gameObject.SetActive(true);
        Cell44 = CreateRect("Cell44", RectOf(Row4));
        ConfigureRect(RectOf(Cell44), width: 32f, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Cell44), ignoreLayout: false, preferredWidth: 32f, preferredHeight: 32f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Cell44), horizontal: false, vertical: false);
        ApplyStyle(Cell44, fg: "#232323", bg: "#232323", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Cell44.gameObject.SetActive(true);
        Cell45 = CreateRect("Cell45", RectOf(Row4));
        ConfigureRect(RectOf(Cell45), width: 32f, height: 32f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(Cell45), ignoreLayout: false, preferredWidth: 32f, preferredHeight: 32f, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(Cell45), horizontal: false, vertical: false);
        ApplyStyle(Cell45, fg: "#232323", bg: "#232323", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        Cell45.gameObject.SetActive(true);
        ObjectiveCard = CreateRect("ObjectiveCard", Root);
        ConfigureRect(RectOf(ObjectiveCard), width: null, height: 268f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(ObjectiveCard), ignoreLayout: false, preferredWidth: null, preferredHeight: 268f, flexibleWidth: 1f, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(ObjectiveCard), horizontal: false, vertical: false);
        ApplyVerticalLayout(RectOf(ObjectiveCard), 10f, 12, 12, 12, 12);
        ApplyStyle(ObjectiveCard, fg: "#111111", bg: "#111111", fontFamily: null, fontSize: null, borderColor: "#7E7E7E", borderWidth: 4f, treatAsIcon: false);
        ObjectiveCard.gameObject.SetActive(true);
        ObjectivesLabel = CreateText("ObjectivesLabel", RectOf(ObjectiveCard));
        ConfigureRect(RectOf(ObjectivesLabel), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(ObjectivesLabel), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(ObjectivesLabel), horizontal: false, vertical: false);
        ApplyStyle(ObjectivesLabel, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 10, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(ObjectivesLabel, lineSpacing: null, wrapText: false);
        ObjectivesLabel.text = "ACTIVE OBJECTIVES";
        ObjectivesLabel.gameObject.SetActive(true);
        var objective1View = new SyntheticContainerC520AC99View(RectOf(ObjectiveCard), null, null);
        Objective1 = objective1View.Root;
        Objective1.name = "Objective1";
        var objective2View = new SyntheticContainerC520AC99View(RectOf(ObjectiveCard), null, new Dictionary<string, IReadOnlyDictionary<string, object?>>(StringComparer.Ordinal)
        {
            ["$/0/0"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "flame"
            },
            ["$/1/0"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "Stabilize the furnace"
            },
            ["$/1/1"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "Mana pressure is dropping."
            }
        });
        Objective2 = objective2View.Root;
        Objective2.name = "Objective2";
        var objective3View = new SyntheticContainerC520AC99View(RectOf(ObjectiveCard), null, new Dictionary<string, IReadOnlyDictionary<string, object?>>(StringComparer.Ordinal)
        {
            ["$/0/0"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "shield"
            },
            ["$/1/0"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "Hold the east passage"
            },
            ["$/1/1"] = new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["Text"] = "Reinforcements arrive in 02:10."
            }
        });
        Objective3 = objective3View.Root;
        Objective3.name = "Objective3";
        ResourceCard = CreateRect("ResourceCard", Root);
        ConfigureRect(RectOf(ResourceCard), width: null, height: 164f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(ResourceCard), ignoreLayout: false, preferredWidth: null, preferredHeight: 164f, flexibleWidth: 1f, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(ResourceCard), horizontal: false, vertical: false);
        ApplyVerticalLayout(RectOf(ResourceCard), 10f, 12, 12, 12, 12);
        ApplyStyle(ResourceCard, fg: "#111111", bg: "#111111", fontFamily: null, fontSize: null, borderColor: "#7E7E7E", borderWidth: 4f, treatAsIcon: false);
        ResourceCard.gameObject.SetActive(true);
        ResourcesLabel = CreateText("ResourcesLabel", RectOf(ResourceCard));
        ConfigureRect(RectOf(ResourcesLabel), width: null, height: null, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(ResourcesLabel), ignoreLayout: false, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(ResourcesLabel), horizontal: false, vertical: false);
        ApplyStyle(ResourcesLabel, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 10, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(ResourcesLabel, lineSpacing: null, wrapText: false);
        ResourcesLabel.text = "RESOURCES";
        ResourcesLabel.gameObject.SetActive(true);
        HealthBar = CreateRect("HealthBar", RectOf(ResourceCard));
        ConfigureRect(RectOf(HealthBar), width: null, height: 22f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(HealthBar), ignoreLayout: false, preferredWidth: null, preferredHeight: 22f, flexibleWidth: 1f, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(HealthBar), horizontal: false, vertical: false);
        ApplyStyle(HealthBar, fg: "#1E1E1E", bg: "#1E1E1E", fontFamily: null, fontSize: null, borderColor: "#8C8C8C", borderWidth: 2f, treatAsIcon: false);
        HealthBar.gameObject.SetActive(true);
        HealthFill = CreateRect("HealthFill", RectOf(HealthBar));
        ConfigureRect(RectOf(HealthFill), width: 280f, height: 18f, left: null, top: null, absolute: true);
        ApplyLayoutSizing(RectOf(HealthFill), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(HealthFill), horizontal: false, vertical: false);
        ApplyStyle(HealthFill, fg: "#D44A4A", bg: "#D44A4A", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        HealthFill.gameObject.SetActive(true);
        HealthText = CreateText("HealthText", RectOf(HealthBar));
        ConfigureRect(RectOf(HealthText), width: null, height: null, left: 12f, top: 4f, absolute: true);
        ApplyLayoutSizing(RectOf(HealthText), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(HealthText), horizontal: true, vertical: true);
        ApplyStyle(HealthText, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 9, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(HealthText, lineSpacing: null, wrapText: false);
        HealthText.text = "HEALTH 81%";
        HealthText.gameObject.SetActive(true);
        ManaBar = CreateRect("ManaBar", RectOf(ResourceCard));
        ConfigureRect(RectOf(ManaBar), width: null, height: 22f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(ManaBar), ignoreLayout: false, preferredWidth: null, preferredHeight: 22f, flexibleWidth: 1f, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(ManaBar), horizontal: false, vertical: false);
        ApplyStyle(ManaBar, fg: "#1E1E1E", bg: "#1E1E1E", fontFamily: null, fontSize: null, borderColor: "#8C8C8C", borderWidth: 2f, treatAsIcon: false);
        ManaBar.gameObject.SetActive(true);
        ManaFill = CreateRect("ManaFill", RectOf(ManaBar));
        ConfigureRect(RectOf(ManaFill), width: 214f, height: 18f, left: null, top: null, absolute: true);
        ApplyLayoutSizing(RectOf(ManaFill), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(ManaFill), horizontal: false, vertical: false);
        ApplyStyle(ManaFill, fg: "#4A78D4", bg: "#4A78D4", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        ManaFill.gameObject.SetActive(true);
        ManaText = CreateText("ManaText", RectOf(ManaBar));
        ConfigureRect(RectOf(ManaText), width: null, height: null, left: 12f, top: 4f, absolute: true);
        ApplyLayoutSizing(RectOf(ManaText), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(ManaText), horizontal: true, vertical: true);
        ApplyStyle(ManaText, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 9, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(ManaText, lineSpacing: null, wrapText: false);
        ManaText.text = "MANA 62%";
        ManaText.gameObject.SetActive(true);
        SupplyBar = CreateRect("SupplyBar", RectOf(ResourceCard));
        ConfigureRect(RectOf(SupplyBar), width: null, height: 22f, left: null, top: null, absolute: false);
        ApplyLayoutSizing(RectOf(SupplyBar), ignoreLayout: false, preferredWidth: null, preferredHeight: 22f, flexibleWidth: 1f, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(SupplyBar), horizontal: false, vertical: false);
        ApplyStyle(SupplyBar, fg: "#1E1E1E", bg: "#1E1E1E", fontFamily: null, fontSize: null, borderColor: "#8C8C8C", borderWidth: 2f, treatAsIcon: false);
        SupplyBar.gameObject.SetActive(true);
        SupplyFill = CreateRect("SupplyFill", RectOf(SupplyBar));
        ConfigureRect(RectOf(SupplyFill), width: 146f, height: 18f, left: null, top: null, absolute: true);
        ApplyLayoutSizing(RectOf(SupplyFill), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(SupplyFill), horizontal: false, vertical: false);
        ApplyStyle(SupplyFill, fg: "#D49C4A", bg: "#D49C4A", fontFamily: null, fontSize: null, borderColor: null, borderWidth: null, treatAsIcon: false);
        SupplyFill.gameObject.SetActive(true);
        SupplyText = CreateText("SupplyText", RectOf(SupplyBar));
        ConfigureRect(RectOf(SupplyText), width: null, height: null, left: 12f, top: 4f, absolute: true);
        ApplyLayoutSizing(RectOf(SupplyText), ignoreLayout: true, preferredWidth: null, preferredHeight: null, flexibleWidth: null, flexibleHeight: null);
        ApplyContentSizeFit(RectOf(SupplyText), horizontal: true, vertical: true);
        ApplyStyle(SupplyText, fg: "#FFFFFF", bg: null, fontFamily: "Press Start 2P", fontSize: 9, borderColor: null, borderWidth: null, treatAsIcon: false);
        ApplyTextMetrics(SupplyText, lineSpacing: null, wrapText: false);
        SupplyText.text = "SUPPLY 38%";
        SupplyText.gameObject.SetActive(true);
        ApplyInstanceOverrides();
        ViewModel = viewModel;
    }

    private QuestSidebarView(RectTransform root, IQuestSidebarViewModel? viewModel, IReadOnlyDictionary<string, IReadOnlyDictionary<string, object?>>? componentOverrides)
    {
        _componentOverrides = componentOverrides;
        Root = root;
        Header = RequireRect(Root, "Header");
        Title = RequireComponent<Text>(Root, "Header/Title");
        Zone = RequireComponent<Text>(Root, "Header/Zone");
        MinimapCard = RequireRect(Root, "MinimapCard");
        MinimapLabel = RequireComponent<Text>(Root, "MinimapCard/MinimapLabel");
        MapGrid = RequireRect(Root, "MinimapCard/MapGrid");
        Row0 = RequireRect(Root, "MinimapCard/MapGrid/Row0");
        Row1 = RequireRect(Root, "MinimapCard/MapGrid/Row1");
        Cell10 = RequireRect(Root, "MinimapCard/MapGrid/Row1/Cell10");
        Cell11 = RequireRect(Root, "MinimapCard/MapGrid/Row1/Cell11");
        Cell12 = RequireRect(Root, "MinimapCard/MapGrid/Row1/Cell12");
        Cell13 = RequireRect(Root, "MinimapCard/MapGrid/Row1/Cell13");
        Cell14 = RequireRect(Root, "MinimapCard/MapGrid/Row1/Cell14");
        Cell15 = RequireRect(Root, "MinimapCard/MapGrid/Row1/Cell15");
        Row2 = RequireRect(Root, "MinimapCard/MapGrid/Row2");
        Cell20 = RequireRect(Root, "MinimapCard/MapGrid/Row2/Cell20");
        Cell21 = RequireRect(Root, "MinimapCard/MapGrid/Row2/Cell21");
        Cell22 = RequireRect(Root, "MinimapCard/MapGrid/Row2/Cell22");
        Cell23 = RequireRect(Root, "MinimapCard/MapGrid/Row2/Cell23");
        Cell24 = RequireRect(Root, "MinimapCard/MapGrid/Row2/Cell24");
        Cell25 = RequireRect(Root, "MinimapCard/MapGrid/Row2/Cell25");
        Row3 = RequireRect(Root, "MinimapCard/MapGrid/Row3");
        Row4 = RequireRect(Root, "MinimapCard/MapGrid/Row4");
        Cell40 = RequireRect(Root, "MinimapCard/MapGrid/Row4/Cell40");
        Cell41 = RequireRect(Root, "MinimapCard/MapGrid/Row4/Cell41");
        Cell42 = RequireRect(Root, "MinimapCard/MapGrid/Row4/Cell42");
        Cell43 = RequireRect(Root, "MinimapCard/MapGrid/Row4/Cell43");
        Cell44 = RequireRect(Root, "MinimapCard/MapGrid/Row4/Cell44");
        Cell45 = RequireRect(Root, "MinimapCard/MapGrid/Row4/Cell45");
        ObjectiveCard = RequireRect(Root, "ObjectiveCard");
        ObjectivesLabel = RequireComponent<Text>(Root, "ObjectiveCard/ObjectivesLabel");
        Objective1 = RequireRect(Root, "ObjectiveCard/Objective1");
        Objective2 = RequireRect(Root, "ObjectiveCard/Objective2");
        Objective3 = RequireRect(Root, "ObjectiveCard/Objective3");
        ResourceCard = RequireRect(Root, "ResourceCard");
        ResourcesLabel = RequireComponent<Text>(Root, "ResourceCard/ResourcesLabel");
        HealthBar = RequireRect(Root, "ResourceCard/HealthBar");
        HealthFill = RequireRect(Root, "ResourceCard/HealthBar/HealthFill");
        HealthText = RequireComponent<Text>(Root, "ResourceCard/HealthBar/HealthText");
        ManaBar = RequireRect(Root, "ResourceCard/ManaBar");
        ManaFill = RequireRect(Root, "ResourceCard/ManaBar/ManaFill");
        ManaText = RequireComponent<Text>(Root, "ResourceCard/ManaBar/ManaText");
        SupplyBar = RequireRect(Root, "ResourceCard/SupplyBar");
        SupplyFill = RequireRect(Root, "ResourceCard/SupplyBar/SupplyFill");
        SupplyText = RequireComponent<Text>(Root, "ResourceCard/SupplyBar/SupplyText");
        ApplyInstanceOverrides();
        ViewModel = viewModel;
    }

    public static QuestSidebarView Bind(RectTransform root, IQuestSidebarViewModel? viewModel = null, IReadOnlyDictionary<string, IReadOnlyDictionary<string, object?>>? componentOverrides = null) => new(root, viewModel, componentOverrides);

    private void ApplyInstanceOverrides()
    {
        if (_componentOverrides == null) return;
        if (TryGetComponentOverrideValue("$/0/0", "Text", out var componentOverrideValue0))
        {
            Title.text = AsString(componentOverrideValue0);
        }
        if (TryGetComponentOverrideValue("$/0/1", "Text", out var componentOverrideValue1))
        {
            Zone.text = AsString(componentOverrideValue1);
        }
        if (TryGetComponentOverrideValue("$/1/0", "Text", out var componentOverrideValue2))
        {
            MinimapLabel.text = AsString(componentOverrideValue2);
        }
        if (TryGetComponentOverrideValue("$/2/0", "Text", out var componentOverrideValue3))
        {
            ObjectivesLabel.text = AsString(componentOverrideValue3);
        }
        if (TryGetComponentOverrideValue("$/3/0", "Text", out var componentOverrideValue4))
        {
            ResourcesLabel.text = AsString(componentOverrideValue4);
        }
        if (TryGetComponentOverrideValue("$/3/1/1", "Text", out var componentOverrideValue5))
        {
            HealthText.text = AsString(componentOverrideValue5);
        }
        if (TryGetComponentOverrideValue("$/3/2/1", "Text", out var componentOverrideValue6))
        {
            ManaText.text = AsString(componentOverrideValue6);
        }
        if (TryGetComponentOverrideValue("$/3/3/1", "Text", out var componentOverrideValue7))
        {
            SupplyText.text = AsString(componentOverrideValue7);
        }
    }

    public void Refresh()
    {
        if (_viewModel == null) return;
    }

    private void OnChanged(object? sender, PropertyChangedEventArgs e) => Refresh();

    private bool TryGetComponentOverrideValue(string nodePath, string propertyName, out object? value)
    {
        value = null;
        if (_componentOverrides == null || !_componentOverrides.TryGetValue(nodePath, out var propertyOverrides)) return false;
        if (propertyOverrides.TryGetValue(propertyName, out value)) return true;
        foreach (var candidate in propertyOverrides)
        {
            if (string.Equals(candidate.Key, propertyName, StringComparison.OrdinalIgnoreCase))
            {
                value = candidate.Value;
                return true;
            }
        }
        return false;
    }

    private static RectTransform CreateRect(string name, Transform? parent){var go=new GameObject(name,typeof(RectTransform));var rect=go.GetComponent<RectTransform>();if(parent!=null)rect.SetParent(parent,false);rect.localScale=Vector3.one;rect.anchorMin=new Vector2(0f,1f);rect.anchorMax=new Vector2(0f,1f);rect.pivot=new Vector2(0f,1f);return rect;}
    private static RectTransform RequireRect(Transform root,string path){var target=root.Find(path);if(target==null||!target.TryGetComponent<RectTransform>(out var rect))throw new InvalidOperationException($"Required RectTransform '{path}' was not found beneath '{root.name}'.");return rect;}
    private static T RequireComponent<T>(Transform root,string path) where T : Component{var target=root.Find(path);if(target==null||!target.TryGetComponent<T>(out var component))throw new InvalidOperationException($"Required component '{typeof(T).Name}' at '{path}' was not found beneath '{root.name}'.");return component;}
    private static Text CreateText(string name, Transform? parent){var rect=CreateRect(name,parent);rect.gameObject.AddComponent<CanvasRenderer>();var text=rect.gameObject.AddComponent<Text>();text.font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");text.horizontalOverflow=HorizontalWrapMode.Overflow;text.verticalOverflow=VerticalWrapMode.Overflow;text.supportRichText=true;return text;}
    private static Image CreateImage(string name, Transform? parent){var rect=CreateRect(name,parent);rect.gameObject.AddComponent<CanvasRenderer>();return rect.gameObject.AddComponent<Image>();}
    private static Button CreateButton(string name, Transform? parent){var image=CreateImage(name,parent);var button=image.gameObject.AddComponent<Button>();button.targetGraphic=image;var label=CreateText("Label",image.transform);Stretch(RectOf(label));label.alignment=TextAnchor.MiddleCenter;return button;}
    private static Toggle CreateToggle(string name, Transform? parent){var root=CreateRect(name,parent);var toggle=root.gameObject.AddComponent<Toggle>();var bg=CreateImage("Background",root);ConfigureRect(RectOf(bg),18f,18f,0f,0f,true);var check=CreateImage("Checkmark",RectOf(bg));Stretch(RectOf(check));var label=CreateText("Label",root);ConfigureRect(RectOf(label),null,18f,24f,0f,true);toggle.targetGraphic=bg;toggle.graphic=check;return toggle;}
    private static Slider CreateSlider(string name, Transform? parent,bool interactable){var root=CreateRect(name,parent);var bg=CreateImage("Background",root);Stretch(RectOf(bg));var fillArea=CreateRect("Fill Area",root);Stretch(fillArea);var fill=CreateImage("Fill",fillArea);Stretch(RectOf(fill));var handleArea=CreateRect("Handle Slide Area",root);Stretch(handleArea);var handle=CreateImage("Handle",handleArea);ConfigureRect(RectOf(handle),12f,12f,0f,0f,true);var slider=root.gameObject.AddComponent<Slider>();slider.fillRect=RectOf(fill);slider.handleRect=RectOf(handle);slider.targetGraphic=handle;slider.interactable=interactable;return slider;}
    private static InputField CreateInput(string name, Transform? parent,bool multiline){var bg=CreateImage(name,parent);var text=CreateText("Text",bg.transform);Stretch(RectOf(text),6f,6f,6f,6f);text.alignment=multiline?TextAnchor.UpperLeft:TextAnchor.MiddleLeft;var input=bg.gameObject.AddComponent<InputField>();input.textComponent=text;input.lineType=multiline?InputField.LineType.MultiLineNewline:InputField.LineType.SingleLine;return input;}
    private static ScrollRect CreateScroll(string name, Transform? parent,out RectTransform content){var root=CreateImage(name,parent);var viewport=CreateImage("Viewport",root.transform);Stretch(RectOf(viewport));viewport.gameObject.AddComponent<Mask>().showMaskGraphic=false;content=CreateRect("Content",RectOf(viewport));Stretch(content);ApplyVerticalLayout(content,0f,0,0,0,0);var scroll=root.gameObject.AddComponent<ScrollRect>();scroll.viewport=RectOf(viewport);scroll.content=content;scroll.horizontal=false;scroll.vertical=true;return scroll;}
    private static void ApplyHorizontalLayout(RectTransform rect,float spacing,int paddingLeft,int paddingRight,int paddingTop,int paddingBottom,string? alignmentPreset=null){var group=rect.gameObject.GetComponent<HorizontalLayoutGroup>()??rect.gameObject.AddComponent<HorizontalLayoutGroup>();group.spacing=spacing;group.padding=new RectOffset(paddingLeft,paddingRight,paddingTop,paddingBottom);group.childControlWidth=true;group.childControlHeight=true;group.childForceExpandWidth=false;group.childForceExpandHeight=false;ApplyLayoutAlignment(group,alignmentPreset);}
    private static void ApplyVerticalLayout(RectTransform rect,float spacing,int paddingLeft,int paddingRight,int paddingTop,int paddingBottom,string? alignmentPreset=null){var group=rect.gameObject.GetComponent<VerticalLayoutGroup>()??rect.gameObject.AddComponent<VerticalLayoutGroup>();group.spacing=spacing;group.padding=new RectOffset(paddingLeft,paddingRight,paddingTop,paddingBottom);group.childControlWidth=true;group.childControlHeight=true;group.childForceExpandWidth=false;group.childForceExpandHeight=false;ApplyLayoutAlignment(group,alignmentPreset);}
    private static void ApplyLayoutSizing(RectTransform rect,bool ignoreLayout,float? preferredWidth,float? preferredHeight,float? flexibleWidth,float? flexibleHeight){var element=rect.gameObject.GetComponent<LayoutElement>()??rect.gameObject.AddComponent<LayoutElement>();element.ignoreLayout=ignoreLayout;element.preferredWidth=preferredWidth??-1f;element.preferredHeight=preferredHeight??-1f;element.flexibleWidth=flexibleWidth??-1f;element.flexibleHeight=flexibleHeight??-1f;}
    private static void ApplyContentSizeFit(RectTransform rect,bool horizontal,bool vertical){var fitter=rect.gameObject.GetComponent<ContentSizeFitter>()??rect.gameObject.AddComponent<ContentSizeFitter>();fitter.horizontalFit=horizontal?ContentSizeFitter.FitMode.PreferredSize:ContentSizeFitter.FitMode.Unconstrained;fitter.verticalFit=vertical?ContentSizeFitter.FitMode.PreferredSize:ContentSizeFitter.FitMode.Unconstrained;}
    private static void ConfigureRect(RectTransform rect,float? width,float? height,float? left,float? top,bool absolute){if(absolute){rect.anchorMin=new Vector2(0f,1f);rect.anchorMax=new Vector2(0f,1f);rect.pivot=new Vector2(0f,1f);rect.anchoredPosition=new Vector2(left??0f,-(top??0f));}if(width.HasValue)rect.SetSizeWithCurrentAnchors(RectTransform.Axis.Horizontal,width.Value);if(height.HasValue)rect.SetSizeWithCurrentAnchors(RectTransform.Axis.Vertical,height.Value);}
    private static void ApplyRectAnchorPreset(RectTransform rect,string preset){switch(NormalizeRectPreset(preset)){case "top-left":case "start":rect.anchorMin=new Vector2(0f,1f);rect.anchorMax=new Vector2(0f,1f);break;case "top-center":rect.anchorMin=new Vector2(0.5f,1f);rect.anchorMax=new Vector2(0.5f,1f);break;case "top-right":case "end":rect.anchorMin=new Vector2(1f,1f);rect.anchorMax=new Vector2(1f,1f);break;case "center":case "middle-center":rect.anchorMin=new Vector2(0.5f,0.5f);rect.anchorMax=new Vector2(0.5f,0.5f);break;case "stretch":rect.anchorMin=new Vector2(0f,0f);rect.anchorMax=new Vector2(1f,1f);break;case "stretch-horizontal":rect.anchorMin=new Vector2(0f,1f);rect.anchorMax=new Vector2(1f,1f);break;case "stretch-vertical":rect.anchorMin=new Vector2(0f,0f);rect.anchorMax=new Vector2(0f,1f);break;}}
    private static void ApplyRectPivotPreset(RectTransform rect,string preset){switch(NormalizeRectPreset(preset)){case "top-left":case "start":rect.pivot=new Vector2(0f,1f);break;case "top-center":rect.pivot=new Vector2(0.5f,1f);break;case "top-right":case "end":rect.pivot=new Vector2(1f,1f);break;case "center":case "middle-center":rect.pivot=new Vector2(0.5f,0.5f);break;case "bottom-left":rect.pivot=new Vector2(0f,0f);break;case "bottom-center":rect.pivot=new Vector2(0.5f,0f);break;case "bottom-right":rect.pivot=new Vector2(1f,0f);break;}}
    private static void ApplyRectTransformMode(RectTransform rect,string mode){switch(NormalizeRectPreset(mode)){case "stretch-parent":case "stretch":Stretch(rect);break;case "absolute-overlay":rect.anchorMin=new Vector2(0f,1f);rect.anchorMax=new Vector2(0f,1f);rect.pivot=new Vector2(0f,1f);break;case "top-left":ApplyRectAnchorPreset(rect,"top-left");ApplyRectPivotPreset(rect,"top-left");break;case "center":ApplyRectAnchorPreset(rect,"center");ApplyRectPivotPreset(rect,"center");break;}}
    private static void ApplyEdgeInsetPolicy(RectTransform rect,string policy){switch(NormalizeRectPreset(policy)){case "match-parent":Stretch(rect);break;case "zero-offsets":rect.offsetMin=Vector2.zero;rect.offsetMax=Vector2.zero;break;}}
    private static void ApplyLayoutAlignment(HorizontalOrVerticalLayoutGroup group,string? alignmentPreset){switch(NormalizeRectPreset(alignmentPreset)){case "top-left":case "start":group.childAlignment=TextAnchor.UpperLeft;break;case "top-center":group.childAlignment=TextAnchor.UpperCenter;break;case "top-right":group.childAlignment=TextAnchor.UpperRight;break;case "middle-left":group.childAlignment=TextAnchor.MiddleLeft;break;case "center":case "middle-center":group.childAlignment=TextAnchor.MiddleCenter;break;case "middle-right":group.childAlignment=TextAnchor.MiddleRight;break;case "bottom-left":group.childAlignment=TextAnchor.LowerLeft;break;case "bottom-center":group.childAlignment=TextAnchor.LowerCenter;break;case "bottom-right":case "end":group.childAlignment=TextAnchor.LowerRight;break;}}
    private static string NormalizeRectPreset(string? value)=>string.IsNullOrWhiteSpace(value)?string.Empty:value.Trim().ToLowerInvariant();
    private static void Stretch(RectTransform rect,float left=0f,float right=0f,float top=0f,float bottom=0f){rect.anchorMin=new Vector2(0f,0f);rect.anchorMax=new Vector2(1f,1f);rect.pivot=new Vector2(0.5f,0.5f);rect.offsetMin=new Vector2(left,bottom);rect.offsetMax=new Vector2(-right,-top);}
    private static void ApplyStyle(Component component,string? fg,string? bg,string? fontFamily,int? fontSize,string? borderColor,float? borderWidth,bool treatAsIcon){if(!string.IsNullOrWhiteSpace(bg))EnsureImage(component.gameObject).color=ParseColor(bg,Color.white);if(!string.IsNullOrWhiteSpace(borderColor)&&borderWidth.HasValue&&borderWidth.Value>0f)ApplyBorder(component.gameObject,ParseColor(borderColor,Color.white),borderWidth.Value);if(component is Text text){if(!string.IsNullOrWhiteSpace(fg))text.color=ParseColor(fg,text.color);if(!string.IsNullOrWhiteSpace(fontFamily)&&TryFont(fontFamily,out var font))text.font=font;if(fontSize.HasValue)text.fontSize=fontSize.Value;if(treatAsIcon){text.alignment=TextAnchor.MiddleCenter;text.horizontalOverflow=HorizontalWrapMode.Overflow;text.verticalOverflow=VerticalWrapMode.Overflow;}}else if(component is Button button&&TryLabel(button.gameObject,out var label)){if(!string.IsNullOrWhiteSpace(fg))label.color=ParseColor(fg,label.color);if(!string.IsNullOrWhiteSpace(fontFamily)&&TryFont(fontFamily,out var font))label.font=font;if(fontSize.HasValue)label.fontSize=fontSize.Value;}else if(component is Toggle toggle&&TryLabel(toggle.gameObject,out var toggleLabel)){if(!string.IsNullOrWhiteSpace(fg))toggleLabel.color=ParseColor(fg,toggleLabel.color);if(!string.IsNullOrWhiteSpace(fontFamily)&&TryFont(fontFamily,out var font))toggleLabel.font=font;if(fontSize.HasValue)toggleLabel.fontSize=fontSize.Value;}else if(component is InputField input&&input.textComponent!=null){if(!string.IsNullOrWhiteSpace(fg))input.textComponent.color=ParseColor(fg,input.textComponent.color);if(!string.IsNullOrWhiteSpace(fontFamily)&&TryFont(fontFamily,out var font))input.textComponent.font=font;if(fontSize.HasValue)input.textComponent.fontSize=fontSize.Value;}}
    private static void ApplyIconMetrics(Component component,float boxWidth,float boxHeight,float baselineOffset,bool opticalCentering,string sizeMode,float explicitFontSize){if(component is not Text text)return;var iconSize=explicitFontSize>0f?explicitFontSize:string.Equals(sizeMode,"match-height",StringComparison.OrdinalIgnoreCase)?Mathf.Max(1f,boxHeight):Mathf.Max(1f,Mathf.Min(boxWidth,boxHeight));text.fontSize=Mathf.RoundToInt(iconSize);text.alignment=opticalCentering?TextAnchor.MiddleCenter:TextAnchor.UpperCenter;text.horizontalOverflow=HorizontalWrapMode.Overflow;text.verticalOverflow=VerticalWrapMode.Overflow;var rect=RectOf(text);if(opticalCentering&&Mathf.Approximately(baselineOffset,0f)&&boxHeight>iconSize){baselineOffset=-1f;}rect.anchoredPosition=new Vector2(rect.anchoredPosition.x,baselineOffset);}
    private static void ApplyTextMetrics(Component component,float? lineSpacing,bool wrapText){if(component is Text text){if(lineSpacing.HasValue)text.lineSpacing=lineSpacing.Value;text.horizontalOverflow=wrapText?HorizontalWrapMode.Wrap:HorizontalWrapMode.Overflow;text.verticalOverflow=VerticalWrapMode.Overflow;return;}if(component is Button button&&TryLabel(button.gameObject,out var label)){if(lineSpacing.HasValue)label.lineSpacing=lineSpacing.Value;label.horizontalOverflow=wrapText?HorizontalWrapMode.Wrap:HorizontalWrapMode.Overflow;label.verticalOverflow=VerticalWrapMode.Overflow;return;}if(component is Toggle toggle&&TryLabel(toggle.gameObject,out var toggleLabel)){if(lineSpacing.HasValue)toggleLabel.lineSpacing=lineSpacing.Value;toggleLabel.horizontalOverflow=wrapText?HorizontalWrapMode.Wrap:HorizontalWrapMode.Overflow;toggleLabel.verticalOverflow=VerticalWrapMode.Overflow;return;}if(component is InputField input&&input.textComponent!=null){if(lineSpacing.HasValue)input.textComponent.lineSpacing=lineSpacing.Value;input.textComponent.horizontalOverflow=wrapText?HorizontalWrapMode.Wrap:HorizontalWrapMode.Overflow;input.textComponent.verticalOverflow=VerticalWrapMode.Overflow;}}
    private static void ApplyEnabled(Component component,bool enabled){if(component is Selectable selectable){selectable.interactable=enabled;return;}component.gameObject.SetActive(enabled);}
    private static void SetButtonText(Button button,string? value){if(TryLabel(button.gameObject,out var label))label.text=value??string.Empty;}
    private static void SetToggleText(Toggle toggle,string? value){if(TryLabel(toggle.gameObject,out var label))label.text=value??string.Empty;}
    private static void SetImage(Image image,string? path){image.sprite=string.IsNullOrWhiteSpace(path)?null:Resources.Load<Sprite>(path);}
    private static bool TryLabel(GameObject go,out Text label){label=go.GetComponentInChildren<Text>(true);return label!=null;}
    private static bool TryFont(string familyName,out Font font){var resourcePath=familyName switch{"Press Start 2P"=>"BoomHudFonts/PressStart2P-Regular","lucide"=>"BoomHudFonts/lucide",_=>familyName};font=Resources.Load<Font>(resourcePath)??Resources.Load<Font>(familyName);return font!=null;}
    private static void ApplyBorder(GameObject go,Color color,float width){var outline=go.GetComponent<Outline>()??go.AddComponent<Outline>();outline.effectColor=color;outline.effectDistance=new Vector2(width,-width);outline.useGraphicAlpha=false;}
    private static Image EnsureImage(GameObject go){var image=go.GetComponent<Image>();if(image==null){if(go.GetComponent<CanvasRenderer>()==null)go.AddComponent<CanvasRenderer>();image=go.AddComponent<Image>();}return image;}
    private static RectTransform RectOf(Component component)=>component.GetComponent<RectTransform>();
    private static RectTransform RectOf(RectTransform rect)=>rect;
    private static string ResolveIconText(string? value)=>value switch{"cross"=>"\uE1E5","flame"=>"\uE0D2","flask-conical"=>"\uE0D5","moon"=>"\uE11E","shield"=>"\uE158","sparkles"=>"\uE412","sword"=>"\uE2B3","swords"=>"\uE2B4","wand"=>"\uE246","wand-2"=>"\uE357","wand-sparkles"=>"\uE357",_=>value??string.Empty};
    private static bool AsBool(object? value,bool fallback)=>value is bool b?b:value is string s&&bool.TryParse(s,out var parsed)?parsed:fallback;
    private static float AsFloat(object? value)=>value switch{float f=>f,double d=>(float)d,int i=>i,long l=>l,decimal m=>(float)m,string s when float.TryParse(s,NumberStyles.Float,CultureInfo.InvariantCulture,out var parsed)=>parsed,_=>0f};
    private static string AsString(object? value)=>value?.ToString()??string.Empty;
    private static Color ParseColor(string? value,Color fallback)=>!string.IsNullOrWhiteSpace(value)&&ColorUtility.TryParseHtmlString(value,out var color)?color:fallback;}
}
