using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.ComponentModel;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace BoomHud.Mvvm.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class BoomHudMvvmGenerator : IIncrementalGenerator
{
    private const string ViewModelForAttributeMetadataName = "BoomHud.Mvvm.BoomHudViewModelForAttribute";

    private enum MvvmFlavor
    {
        None,
        ReactiveUI,
        CommunityToolkit,
        Custom
    }

    private sealed record GeneratorConfig(MvvmFlavor Flavor, bool GenerateConcreteViewModels);

    private sealed record ViewModelTarget(INamedTypeSymbol ClassSymbol, string ViewName, Location? Location);

    private static readonly DiagnosticDescriptor MissingInterfaceDescriptor = new(
        id: "BHMVVM001",
        title: "Missing BoomHud ViewModel interface",
        messageFormat: "Could not find interface '{0}' for view '{1}', which should have been generated by Layer A and included in the compilation",
        category: "BoomHud.Mvvm",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor ClassMustBePartialDescriptor = new(
        id: "BHMVVM002",
        title: "BoomHud ViewModel class must be partial",
        messageFormat: "Class '{0}' must be declared partial to receive generated MVVM adapter code",
        category: "BoomHud.Mvvm",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor MultipleInterfacesDescriptor = new(
        id: "BHMVVM004",
        title: "Multiple BoomHud ViewModel interfaces found",
        messageFormat: "Found multiple interfaces named '{0}' for view '{1}', where only one I{{ViewName}}ViewModel should exist in the compilation",
        category: "BoomHud.Mvvm",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor MissingMvvmDependencyDescriptor = new(
        id: "BHMVVM005",
        title: "Missing MVVM dependency",
        messageFormat: "BoomHud MVVM flavor '{0}' requires type '{1}' which was not found in the compilation, so ensure the corresponding MVVM package reference exists",
        category: "BoomHud.Mvvm",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor ConcreteGenerationRequiredDescriptor = new(
        id: "BHMVVM006",
        title: "Concrete ViewModel generation disabled",
        messageFormat: "BoomHud MVVM flavor '{0}' is enabled, but no code will be generated because 'BoomHudMvvmGenerateConcreteViewModels' is not true",
        category: "BoomHud.Mvvm",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor FlavorNotSupportedDescriptor = new(
        id: "BHMVVM003",
        title: "MVVM flavor not supported",
        messageFormat: "BoomHud MVVM flavor '{0}' is not implemented yet by the adapter generator",
        category: "BoomHud.Mvvm",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(
                "BoomHudViewModelForAttribute.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8));
        });

        var config = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) => ParseConfig(provider.GlobalOptions));

        var targets = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                static (ctx, ct) => TryCreateTarget(ctx, ct))
            .Where(static t => t is not null)!
            .Select(static (t, _) => t!);

        var combined = targets.Collect().Combine(config).Combine(context.CompilationProvider);

        context.RegisterSourceOutput(combined, static (spc, triple) =>
        {
            var ((targetList, generatorConfig), compilation) = triple;

            if (generatorConfig.Flavor == MvvmFlavor.None)
                return;

            if (!generatorConfig.GenerateConcreteViewModels)
            {
                spc.ReportDiagnostic(Diagnostic.Create(ConcreteGenerationRequiredDescriptor, Location.None, generatorConfig.Flavor.ToString()));
                return;
            }

            foreach (var target in targetList)
            {
                switch (generatorConfig.Flavor)
                {
                    case MvvmFlavor.Custom:
                        EmitCustomConcreteViewModel(spc, compilation, target);
                        break;
                    case MvvmFlavor.ReactiveUI:
                        EmitReactiveUiConcreteViewModel(spc, compilation, target);
                        break;
                    case MvvmFlavor.CommunityToolkit:
                        EmitCommunityToolkitConcreteViewModel(spc, compilation, target);
                        break;
                    default:
                        spc.ReportDiagnostic(Diagnostic.Create(FlavorNotSupportedDescriptor, Location.None, generatorConfig.Flavor.ToString()));
                        break;
                }
            }
        });
    }

    private static GeneratorConfig ParseConfig(AnalyzerConfigOptions options)
    {
        var flavor = MvvmFlavor.None;
        if (options.TryGetValue("build_property.BoomHudMvvmFlavor", out var flavorText) &&
            !string.IsNullOrWhiteSpace(flavorText) &&
            Enum.TryParse<MvvmFlavor>(flavorText.Trim(), ignoreCase: true, out var parsed))
        {
            flavor = parsed;
        }

        var generateConcrete = false;
        if (options.TryGetValue("build_property.BoomHudMvvmGenerateConcreteViewModels", out var generateText) &&
            !string.IsNullOrWhiteSpace(generateText) &&
            bool.TryParse(generateText.Trim(), out var parsedBool))
        {
            generateConcrete = parsedBool;
        }

        return new GeneratorConfig(flavor, generateConcrete);
    }

    private static ViewModelTarget? TryCreateTarget(GeneratorSyntaxContext context, System.Threading.CancellationToken ct)
    {
        if (context.Node is not ClassDeclarationSyntax classDecl)
            return null;

        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl, ct) as INamedTypeSymbol;
        if (symbol is null)
            return null;

        var attr = GetAttribute(symbol, ViewModelForAttributeMetadataName);
        if (attr is null)
            return null;

        if (attr.ConstructorArguments.Length < 1)
            return null;

        var viewName = attr.ConstructorArguments[0].Value as string;
        if (string.IsNullOrWhiteSpace(viewName))
            return null;

        if (!classDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
        {
            return new ViewModelTarget(symbol, viewName, classDecl.Identifier.GetLocation());
        }

        return new ViewModelTarget(symbol, viewName, classDecl.Identifier.GetLocation());
    }

    private static void EmitCustomConcreteViewModel(SourceProductionContext spc, Compilation compilation, ViewModelTarget target)
    {
        if (!IsPartial(target.ClassSymbol))
        {
            spc.ReportDiagnostic(Diagnostic.Create(ClassMustBePartialDescriptor, target.Location, target.ClassSymbol.Name));
            return;
        }

        var interfaceName = "I" + target.ViewName + "ViewModel";
        var matchingInterfaces = compilation.GetSymbolsWithName(interfaceName, SymbolFilter.Type)
            .OfType<INamedTypeSymbol>()
            .Where(s => s.TypeKind == TypeKind.Interface && string.Equals(s.Name, interfaceName, StringComparison.Ordinal))
            .ToImmutableArray();

        if (matchingInterfaces.Length == 0)
        {
            spc.ReportDiagnostic(Diagnostic.Create(MissingInterfaceDescriptor, target.Location, interfaceName, target.ViewName));
            return;
        }

        if (matchingInterfaces.Length > 1)
        {
            spc.ReportDiagnostic(Diagnostic.Create(MultipleInterfacesDescriptor, target.Location, interfaceName, target.ViewName));
            return;
        }

        var iface = matchingInterfaces[0];

        var ns = GetNamespace(target.ClassSymbol);
        var accessibility = GetAccessibility(target.ClassSymbol);

        var source = GenerateCustomAdapterSource(ns, accessibility, target.ClassSymbol.Name, iface);
        var hintName = $"{(string.IsNullOrEmpty(ns) ? target.ClassSymbol.Name : ns.Replace('.', '_') + "_" + target.ClassSymbol.Name)}.BoomHudMvvm.Custom.g.cs";

        spc.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static void EmitReactiveUiConcreteViewModel(SourceProductionContext spc, Compilation compilation, ViewModelTarget target)
    {
        if (!IsPartial(target.ClassSymbol))
        {
            spc.ReportDiagnostic(Diagnostic.Create(ClassMustBePartialDescriptor, target.Location, target.ClassSymbol.Name));
            return;
        }

        var reactiveObject = compilation.GetTypeByMetadataName("ReactiveUI.ReactiveObject");
        if (reactiveObject is null)
        {
            spc.ReportDiagnostic(Diagnostic.Create(MissingMvvmDependencyDescriptor, target.Location, MvvmFlavor.ReactiveUI.ToString(), "ReactiveUI.ReactiveObject"));
            return;
        }

        var iface = TryResolveViewModelInterface(spc, compilation, target);
        if (iface is null)
            return;

        var ns = GetNamespace(target.ClassSymbol);
        var accessibility = GetAccessibility(target.ClassSymbol);
        var baseTypeName = reactiveObject.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var source = GenerateReactiveUiAdapterSource(ns, accessibility, target.ClassSymbol.Name, iface, baseTypeName);
        var hintName = $"{(string.IsNullOrEmpty(ns) ? target.ClassSymbol.Name : ns.Replace('.', '_') + "_" + target.ClassSymbol.Name)}.BoomHudMvvm.ReactiveUI.g.cs";

        spc.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static void EmitCommunityToolkitConcreteViewModel(SourceProductionContext spc, Compilation compilation, ViewModelTarget target)
    {
        if (!IsPartial(target.ClassSymbol))
        {
            spc.ReportDiagnostic(Diagnostic.Create(ClassMustBePartialDescriptor, target.Location, target.ClassSymbol.Name));
            return;
        }

        var observableObject = compilation.GetTypeByMetadataName("CommunityToolkit.Mvvm.ComponentModel.ObservableObject");
        if (observableObject is null)
        {
            spc.ReportDiagnostic(Diagnostic.Create(MissingMvvmDependencyDescriptor, target.Location, MvvmFlavor.CommunityToolkit.ToString(), "CommunityToolkit.Mvvm.ComponentModel.ObservableObject"));
            return;
        }

        var iface = TryResolveViewModelInterface(spc, compilation, target);
        if (iface is null)
            return;

        var ns = GetNamespace(target.ClassSymbol);
        var accessibility = GetAccessibility(target.ClassSymbol);
        var baseTypeName = observableObject.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var source = GenerateCommunityToolkitAdapterSource(ns, accessibility, target.ClassSymbol.Name, iface, baseTypeName);
        var hintName = $"{(string.IsNullOrEmpty(ns) ? target.ClassSymbol.Name : ns.Replace('.', '_') + "_" + target.ClassSymbol.Name)}.BoomHudMvvm.CommunityToolkit.g.cs";

        spc.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static INamedTypeSymbol? TryResolveViewModelInterface(SourceProductionContext spc, Compilation compilation, ViewModelTarget target)
    {
        var interfaceName = "I" + target.ViewName + "ViewModel";
        var matchingInterfaces = compilation.GetSymbolsWithName(interfaceName, SymbolFilter.Type)
            .OfType<INamedTypeSymbol>()
            .Where(s => s.TypeKind == TypeKind.Interface && string.Equals(s.Name, interfaceName, StringComparison.Ordinal))
            .ToImmutableArray();

        if (matchingInterfaces.Length == 0)
        {
            spc.ReportDiagnostic(Diagnostic.Create(MissingInterfaceDescriptor, target.Location, interfaceName, target.ViewName));
            return null;
        }

        if (matchingInterfaces.Length > 1)
        {
            spc.ReportDiagnostic(Diagnostic.Create(MultipleInterfacesDescriptor, target.Location, interfaceName, target.ViewName));
            return null;
        }

        return matchingInterfaces[0];
    }

    private static string GenerateCustomAdapterSource(string? @namespace, string accessibility, string className, INamedTypeSymbol viewModelInterface)
    {
        var sb = new StringBuilder();

        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(@namespace))
        {
            sb.Append("namespace ").Append(@namespace).AppendLine(";");
            sb.AppendLine();
        }

        var interfaceTypeName = viewModelInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.Append(accessibility).Append(" partial class ").Append(className).Append(" : ").Append(interfaceTypeName).AppendLine(", INotifyPropertyChanged");
        sb.AppendLine("{");
        sb.AppendLine("    public event PropertyChangedEventHandler? PropertyChanged;");
        sb.AppendLine();
        sb.AppendLine("    protected virtual void OnPropertyChanged(string propertyName)");
        sb.AppendLine("    {");
        sb.AppendLine("        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));");
        sb.AppendLine("    }");

        var props = viewModelInterface.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.GetMethod is not null)
            .OrderBy(p => p.Name, StringComparer.Ordinal)
            .ToArray();

        foreach (var prop in props)
        {
            var propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var fieldName = "_" + char.ToLowerInvariant(prop.Name[0]) + prop.Name.Substring(1);

            sb.AppendLine();
            sb.Append("    private ").Append(propType).Append(' ').Append(fieldName).AppendLine(";");
            sb.AppendLine();
            sb.Append("    public ").Append(propType).Append(' ').Append(prop.Name).AppendLine();
            sb.AppendLine("    {");
            sb.Append("        get => ").Append(fieldName).AppendLine(";");
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.Append("            if (!global::System.Collections.Generic.EqualityComparer<").Append(propType).Append(">.Default.Equals(").Append(fieldName).AppendLine(", value))");
            sb.AppendLine("            {");
            sb.Append("                ").Append(fieldName).AppendLine(" = value;");
            sb.Append("                OnPropertyChanged(nameof(").Append(prop.Name).AppendLine("));");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateReactiveUiAdapterSource(
        string? @namespace,
        string accessibility,
        string className,
        INamedTypeSymbol viewModelInterface,
        string baseTypeName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using ReactiveUI;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(@namespace))
        {
            sb.Append("namespace ").Append(@namespace).AppendLine(";");
            sb.AppendLine();
        }

        var interfaceTypeName = viewModelInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.Append(accessibility)
            .Append(" partial class ")
            .Append(className)
            .Append(" : ")
            .Append(baseTypeName)
            .Append(", ")
            .Append(interfaceTypeName)
            .AppendLine();

        sb.AppendLine("{");

        var props = viewModelInterface.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.GetMethod is not null)
            .OrderBy(p => p.Name, StringComparer.Ordinal)
            .ToArray();

        foreach (var prop in props)
        {
            var propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var fieldName = "_" + char.ToLowerInvariant(prop.Name[0]) + prop.Name.Substring(1);

            sb.AppendLine();
            sb.Append("    private ").Append(propType).Append(' ').Append(fieldName).AppendLine(";");
            sb.AppendLine();
            sb.Append("    public ").Append(propType).Append(' ').Append(prop.Name).AppendLine();
            sb.AppendLine("    {");
            sb.Append("        get => ").Append(fieldName).AppendLine(";");
            sb.AppendLine("        set => this.RaiseAndSetIfChanged(ref " + fieldName + ", value);");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateCommunityToolkitAdapterSource(
        string? @namespace,
        string accessibility,
        string className,
        INamedTypeSymbol viewModelInterface,
        string baseTypeName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using CommunityToolkit.Mvvm.ComponentModel;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(@namespace))
        {
            sb.Append("namespace ").Append(@namespace).AppendLine(";");
            sb.AppendLine();
        }

        var interfaceTypeName = viewModelInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.Append(accessibility)
            .Append(" partial class ")
            .Append(className)
            .Append(" : ")
            .Append(baseTypeName)
            .Append(", ")
            .Append(interfaceTypeName)
            .AppendLine();

        sb.AppendLine("{");

        var props = viewModelInterface.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.GetMethod is not null)
            .OrderBy(p => p.Name, StringComparer.Ordinal)
            .ToArray();

        foreach (var prop in props)
        {
            var propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var fieldName = "_" + char.ToLowerInvariant(prop.Name[0]) + prop.Name.Substring(1);

            sb.AppendLine();
            sb.Append("    private ").Append(propType).Append(' ').Append(fieldName).AppendLine(";");
            sb.AppendLine();
            sb.Append("    public ").Append(propType).Append(' ').Append(prop.Name).AppendLine();
            sb.AppendLine("    {");
            sb.Append("        get => ").Append(fieldName).AppendLine(";");
            sb.AppendLine("        set => SetProperty(ref " + fieldName + ", value);");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static bool IsPartial(INamedTypeSymbol symbol)
    {
        foreach (var decl in symbol.DeclaringSyntaxReferences)
        {
            if (decl.GetSyntax() is TypeDeclarationSyntax tds &&
                tds.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
            {
                return true;
            }
        }

        return false;
    }

    private static AttributeData? GetAttribute(INamedTypeSymbol symbol, string metadataName)
    {
        foreach (var attr in symbol.GetAttributes())
        {
            if (attr.AttributeClass is null)
                continue;

            if (string.Equals(attr.AttributeClass.ToDisplayString(), metadataName, StringComparison.Ordinal) ||
                string.Equals(attr.AttributeClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "global::" + metadataName, StringComparison.Ordinal))
            {
                return attr;
            }
        }

        return null;
    }

    private static string? GetNamespace(INamedTypeSymbol symbol)
    {
        var ns = symbol.ContainingNamespace;
        if (ns is null || ns.IsGlobalNamespace)
            return null;

        return ns.ToDisplayString();
    }

    private static string GetAccessibility(INamedTypeSymbol symbol)
    {
        return symbol.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            _ => "internal"
        };
    }

    private const string AttributeSource = @"namespace BoomHud.Mvvm
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    internal sealed class BoomHudViewModelForAttribute : global::System.Attribute
    {
        public BoomHudViewModelForAttribute(string viewName)
        {
            ViewName = viewName;
        }

        public string ViewName { get; }
    }
}
";
}
